### ISSUE TITLE
Fail to provision and edge device under Azure .cn (China) subscription 

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#101]
**Describe the bug**
I am trying to provision a device into IoTHub via DPS. I am using a SymetricKey provision type and a scope Id from a `azure.cn` subscription.
The provisioning command returns success but NO IoTEdge device entity is created by DPS.
Provisioning command used: Provision-EflowVm -provisioningType DpsSymmetricKey -symmKey "<SymKey>" -scopeId <MyCnScope> -registrationId <regId>

Accessing to the "/etc/iotedge/config.ymal" file I can see the property `provisioning > global_endpoint` is set to "https://global.azure-devices-provisioning.net".
Since we are using a .cn scope Id I think the `global_endpoint` should be set to "https://global.azure-devices-provisioning.cn".

Changing the `global_endpoint` in the config file manually and restarting the EFLOW VM. The Edge device entity is correctly created under the IoTHub portal (cn subscription).

Why is the service assuming the wrong global_endpoint if I am passing a .cn scope Id as a parameter?
Please let me know I can provide additional troubleshooting data.

**Expected behavior**
I expect that the IoTEntity war was created on IoTHub .cn portal without manually changing the `global_endpoint` property on the VM file.

**Windows Host OS (please complete the following information):**
 - Edition: [Pro]
 - EFLOW:  v1.1.2111.17111
 - Version: [19044.1348]
 - Physical Device located in Mainland China

**Comment by ngmartins** [comment]
Hello. 
I originally open this issue under the EFLOW repo issues page. Then it has been transferred to the iotedge repo.
I have also used the official MS support channels to report this. I had a quite disappointing answer about this being a feature request (which obviously is not).

We are aware of the workaround but it is not suitable for large-scale automated deployments.
Please let me know how can we help from our side to help. We will be happy to bring our MS Account Manager to the loof if it helps somehow.

Thanks,

Nuno

**Comment by huguesBouvier** [comment]
I discussed it internally, EFLOW  Team will work on it.
I have not visibility in their schedule but it could be part of January release.

**Comment by fcabrera23** [comment]
Hi @ngmartins,

This was fixed with our [latest release](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2112.20121). 

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hey,

Just confirmed it works as expected.
Thanks for implementing this :)

Just a quick note in case you are thinking to add this to the documentation. We should pass the endpoint with `https://` prefix.
