### ISSUE TITLE
Deploy-Eflow exits with error "Signer is not trusted" during Linux VM image verification

### ISSUE THREAD

**Issue by Abvik** [Azure/iotedge-eflow#102]
While doing the EFLOWVM deployment we are getting signer not trusted error.
This is happening intermittently. Not sure which scenario we will run into this.
We are using the "AzureIoTEdge LTS 1.1.2107.0.msi".
 We followed all the steps as per this ticket. But we are still facing this.
 https://github.com/Azure/iotedge-eflow/issues/33

Tried with the below policies, no luck with that.
Set-ExecutionPolicy -ExecutionPolicy Bypass -Force
Set-ExecutionPolicy AllSigned -Force

Can please help us what cloud be the wrong?

Attached the EFLOW logs here.
[eflowlogs.zip](https://github.com/Azure/iotedge-eflow/files/7661777/eflowlogs.zip)

**Comment by fcabrera23** [comment]
Hi @Abvik,

Thanks for your information.  I checked your logs and have two suggestions before asking for further information.

1. Use the latest EFLOW MSI - We've been introducing some bug fixes in the past updates, so make sure to use the latest version.
2. Check [EFLOW Issue 81](https://github.com/Azure/iotedge-eflow/issues/81).

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @Abvik,

I'm glad to hear that the issue was fixed. Could you please explain to me why your application is not compatible with the latest version?

Regarding backporting the issue to previous versions, we won't be able to do that.

Thanks,
Francisco

**Comment by Abvik** [comment]
Hi @fcabrera23 

One of our application module couldn't communicate with latest AzureIotEdge ( I think it's due Powershell compatibility issue). 

Thanks,
Vikram

**Comment by fcabrera23** [comment]
Hi,

Thanks for the update - We plan to always be up to date with the IoT Edge included in our VM composition.

Thanks,
Francisco
