### ISSUE TITLE
Eflow re-provisioning fails due to scp of cert

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/iotedge-eflow#103]
When I try to provision iotedge with `Provision-EflowVm` a second time it fails with
`scp  failed to execute [scp: /home/iotedge-user/certs/iot-edge-device-identity-eflow-dps-test.cert.pem: Permission denied] at line 3689`

Manually removing the cert and key file before starting second provisioning solves this issue

**To Reproduce**
1. Provision iotedge with `Provision-EflowVM`
2. Provision iotedge with `Provision-EflowVM` a second time
3. Confirm re-provision iotedge with `Y`
4. See error in output

**Expected behavior**
If a device is re-provisioned the existing cert and key files are overwritten with the newly presented ones passed as parameters to `Provision-EflowVM`

**Screenshots**
![image](https://user-images.githubusercontent.com/20863200/145387983-67424c3a-896c-405c-9831-4afc8c62d0f1.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows 11 Enterprise
 - Version: 10.0.22000 Build 22000
 - Virtual Machine: None
 
**Additional context**

**Comment by fcabrera23** [comment]
Hi @ChristianBeier,

Thanks for your detailed information. I was able to reproduce your error.  We will address this bug in the upcoming EFLOW updates. In the meantime, here's a workaround that you could use. 

1. Provision EFLOW VM using DPS with certs
2. Before reprovisioning, make sure to delete the previous certs -> `Invoke-EflowVmCommand "sudo rm -rf /home/iotedge-user/certs/*`
3. Provision EFLOW VM again. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @ChristianBeier,

This issue was fixed with the [EFLOW 1.1.2201.04022 update](https://aka.ms/AzEFLOW-1_1_2201_04022).

Thanks,
Francisco
