### ISSUE TITLE
TPM "-headless" provisioning parameter does not work as documented

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#104]
**Describe the bug**
According to the documentation of the  `Provision-EflowVM` command, the headless switch parameter should allow for the confirmation of a device reprovisioning.
Documentation:
```
 -headless [<SwitchParameter>]
        Headless mode for WAC, bypasses:
        - user input to confirm provisioning if iotedge was previously provisioned
```
However, using this parameter I am having the opposite behavior.

**To Reproduce**
Run the command ` Provision-EflowVM -provisioningType DpsTpm -scopeId <ScopeId> -registrationId <RegistrationId> -headless` to re-provisioning a device without user confirmation.

**Expected behavior**
Re-provision the device.

**Screenshots**
<img width="836" alt="image" src="https://user-images.githubusercontent.com/24669761/145897371-dcb27876-483e-47c6-99e9-a0c1ecfa11fe.png">

**Windows Host OS (please complete the following information):**
- Edition: [Pro]
- EFLOW: v1.1.2111.17111
- Version: [19044.1348]
- Physical Device

**Additional context**
The parameter seems to bypass the confirmation prompt but instead of allowing for the provision it just cancels the operation.
It has a huge impact on fleets migration's automation to the EFLOW.

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for your information.  From what I'm seeing in the screenshot, the issue is when trying to reprovision. Have you tried the parameter with 1st time provisioning?

Thanks,
Francisco

**Comment by ngmartins** [comment]
My implementation always uses the `-headless` parameter. However, for the first provisioning, no pop-up window is through and no user input is required. As so the parameter is irrelevant in this scenario.

As per my understanding, the documentation says that using the `-headless` parameter, the device should be reprovisioned however it behaves the other way around.

**Comment by fcabrera23** [comment]
Hi @ngmartins,

From what you are saying, my understanding is that the first provisioning using -headless works correctly, but if you try reprovisioning it will fail. I think the issue is that the reprovisioning it's not working, rather than the -headless is not working. 

Thanks,
Francisco

**Comment by ngmartins** [comment]
OK, we are moving in circles over here.
The parameter description on the documentation:
`user input to confirm provisioning if iotedge was previously provisioned`

The `-headless` parameter is to deal with previously provisioned devices. On the first provision, there is no input pop-up so no mether if you use or not the `-headless`.

On a device re-provisioning, there is a pop-up informing us that the device has been previously provisioned and questioning if we wish to reprovision it. In this scenario, the `-headless` parameter should allow us to programmatically `confirm provisioning`.
However, using the `-headless` parameter has the exact opposite effect.

**Comment by ngmartins** [comment]
Hello, any update on this?

**Comment by fcabrera23** [comment]
Hi @ngmartins,

The `-headless` flag is only used for WAC deployments and currently, it's not targeted for PowerShell deployments. However, I do agree that the documentation is incorrect and the description should be: _"If this flag is present, it determines whether the user needs to confirm in case a security warning is issued."_. 

We will update the documentation asap.  In the meantime, I think your issue is related to duplicate provisioning, which we have a similar [issue](https://github.com/Azure/iotedge-eflow/issues/103).  

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello @fcabrera23,

My issue is not being able to re-provision the device. My issue is not being able to do it in an automatic way because of the warning confirmation request.

I didn't come up with the `-headless` parameter from the top of my head. You give us this solution for a similar problem with another command. Please refer to [this issue](https://github.com/Azure/iotedge-eflow/issues/85).

According to you:
`We already support that, although is not documented, as we may change it in the future. When doing the Set-EflowVmFeature you can add the parameter -headless and it won't ask for confirmation.`

So I was expecting the `-headless` parameter to work in the same way for all the supported commands. It is not happening. We are using it with other EFLOW. 

Even changing the documentation won't solve this issue because for the Provision-EflowVM command the `-headless` parameter won't allow us to re-provision devices programmatically witch is definitely a deal-breaker.

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for your clarification regarding the use case. The `headless` parameter is used internally for WAC and may not work as expected for PowerShell `Provision-EflowVm`.  However, I understand your request and we plan to include that feature in the upcoming updates.

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello.

Great to know it will be working in the future. I will be tracking the release notes.

However, I would like to understand what is the official way of automating an edge device setup (install, deploy, and provision an eflow VM).
We are using intune to set up our edge device fleet so we are using the PowerShell commands to build an MSI app to automate the entire process. 

But we keep bumping on little issues. Maybe there is a better way to do it so. 

Thanks once again,


Nuno

**Comment by fcabrera23** [comment]
Hi,

There are multiple ways to automate and edge devices; Intune seems a reasonable approach and would like to further understand what are the issues you're facing.

If you want, we could set up a call to discuss other options with our WinIoT team.

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello @fcabrera23,

Intune provides us a straight forward way to install the flow .msi under a remote windows device.
All other steps like Hyper-V enabling, VM deploys and provisioning, etc need to be automated by us.

We are doing this using the PowerShell commands. 
The problem comes up when manual interaction is mandatory OR we cannot rely on the reported status.
As per my understanding, the iotedge-eflow team is very agile and receptive to community feedback. You already informed me by multiple times the team had plans to include changes in a direction to help us to overcome those issues and I appreciate that.

If you think more specific feedback or even an overview can be useful to you and your team, I will be glad to set up the call you mentioned. 

Thanks once again,

Nuno

**Comment by fcabrera23** [comment]
Hi @ngmartins ,

We will include a fix for the EFLOW version based on IoT Edge 1.2 in the future. In the meantime you can always reset provisioning before trying reprovisionioning using the command: `Invoke-EflowVmCommand "sudo cp /var/.eflow/config/config.yaml /etc/iotedge/config.yaml"`.

Thanks,
Francisco
