### ISSUE TITLE
Expired certificates of wssdagent.exe

### ISSUE THREAD

**Issue by bkarrlander** [Azure/iotedge-eflow#107]
Hi,

The certificate of wssdagent.exe has expired on **the previous two** releases of EFLOW (1.1.2109.0 and 1.1.2110.03111 ) so those versions of EFLOW can't be deployed on our production machines.

The certificate of **latest** EFLOW release is fine but we are currently using older versions of EFLOW because of the latest release's bug that prevents static IP.

Is there a scheduled release date for a new EFLOW release and is the static IP bug targeted in that release?

Best regards,
Björn

**Comment by fcabrera23** [comment]
Hi @bkarrlander,

We are targeting a new update in the first week of January. This update will fix the certificates issues, as well as static IP deployments. 

Thanks,
Francicso

**Comment by bkarrlander** [comment]
@fcabrera23, that's great! Thank you.

Björn
