### ISSUE TITLE
Cannot deploy Azure IoT Edge for Linux on Windows after a deploy was failed.

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/iotedge-eflow#11]
The first time I deployed Azure IoT Edge on my Windows PC was failed because of time out.
 I cannot deploy it again as the error: 'Unsupported: Device not clean, Azure IoT Edge for Linux on Windows components detected (Azure IoT Edge PS module)'

**Comment by TerryWarwick** [comment]
@Dolphinsimon,

Uninstalling Azure IoT Edge from the target device via Start - Settings - Apps should do the trick.  If you continue to experience the issue after performing an uninstall, please let us know.

Terry Warwick
Microsoft

**Comment by Dolphinsimon** [comment]
Yes, after uninstall the Azure IoT Edge from the app list, the checking is successful.
