### ISSUE TITLE
How to configure the certificates in config.yaml for the modules and downstream devices ?

### ISSUE THREAD

**Issue by niravjprabtani** [Azure/iotedge-eflow#113]
**Question Summary**
How to configure the certificates in config.yaml for modules and downstream devices?

**Detailed background**
I have just started EFLOW and am able to deploy / provision the device using commands but wanted to configure the certificates so modules and downstream devices can be authenticated.

I have tried to find out the solution over google but was not been able to find out it. Do I need to manually update the path into the config.yaml and restart the service or is there any way I can do it using commands only?

As of now, my deployment uses self generated certificate which is valid for 90 days.

![image](https://user-images.githubusercontent.com/49067519/150533164-7702e08a-ca0e-4e5b-a02d-b07af5c08e8a.png)

**Comment by fcabrera23** [comment]
Hi @niravjprabtani,

I would recommend checking [Eflow Utils](https://github.com/Azure/iotedge-eflow/tree/main/eflow-util) and check the `EflowUtil-SetEdgeCertificates` cmdlet.   These cmdlets are sample codes, so feel free to download and edit them to your best convenience. 

Thanks,
Francisco

**Comment by niravjprabtani** [comment]
Hi @fcabrera23 

Thanks for the immediate reply, I really appreciate it
