### ISSUE TITLE
Can't force the installation of IoTEdge Package during the deploymnet.

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#12]
**Describe the bug**
When I use the `-installPackages` parameter on the deployment command, the IoTEdge installation fails. Moby-engine installation happens without problems.

**To Reproduce**
1. Run the command:
>  `Deploy-Eflow -acceptEula yes -acceptOptionalTelemetry yes -mobyPackageVersion 19.03.11 -iotedgePackageVersion 1.1.0 -installPackages`

2. Output: 
>` [03/17/2021 04:33:27] Exception caught!!!`

>  ` ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i "C:\Program Files\Azure IoT Edge\id_rsa" iotedge-user@192.168.1.130 sudo dnf -y install azure-iotedge-1.1.0* failed to execute [Error: Unable to find a match: azure-iotedge-1.1.0*] at line 2336`

>` [03/17/2021 04:33:27] Exception caught!!!`

>`   Installing software in virtual machine failed (L762)`

>` [03/17/2021 04:33:27] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh`

**Expected behavior**
Successfully install the iotedgePackageVersion 1.1.0

**Windows Host OS (please complete the following information):**
 - Edition: 10 Enterprise
 - Version: build 18363.1440
 - Virtual Machine: N.A

**Comment by TerryWarwick** [comment]
@ngmartins,  

Actually Azure IoT Edge 1.1.0 is built into the current installation by default.  The additional parameters to specific the version of Azure IoT Edge are not fully enabled yet.  

Terry Warwick
Microsoft

**Comment by ngmartins** [comment]
Hi @TerryWarwick,
So for now it is not possible to specify the IoT Edge version, but this is something that is expected to be implemented in the future?
Thanks a lot for the answer,

Nuno

**Comment by fcabrera23** [comment]
Hi @ngmartins,

This is something we have planned for our incoming updates.  In the meantime, we will be using the 1.1.X LTS version.
