### ISSUE TITLE
Set "DpsTpm" feature failed in Windows Server 2022

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/iotedge-eflow#120]
**Describe the bug**
I cannot enable DpsTpm feature by Set-EflowVmFeature -feature "DpsTpm" -enable

**To Reproduce**
Just Set-EflowVmFeature -feature "DpsTpm" -enable in powershell.

**Expected behavior**
The feature should be enabled.

**Screenshots**
![Eflow](https://user-images.githubusercontent.com/4425053/154486872-497997aa-0569-47bb-9693-47dff1f77635.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows Server 2022
 - Version: 20348
 - Virtual Machine: Local VM

**Comment by fcabrera23** [comment]
Hi @Dolphinsimon,

Thanks for your information.  Could you please answer the following questions:

1) Are you using an Internal/External switch?
2) During _Deploy-Eflow_  everything worked fine?
3) Can you connect to the VM using the _Connect-EflowVm_ cmdlet?

Thanks,
Francisco

**Comment by Dolphinsimon** [comment]
1.External switch
2.Yes
3.Yes

**Comment by fcabrera23** [comment]
Hi @Dolphinsimon,

Can you connect to the EFLOW VM and run the following commands and share the output.

1. `sudo systecmtl statsu tpm`
2. `sudo arp -a`

Thanks,
Francisco

**Comment by Dolphinsimon** [comment]
Hi @fcabrera23 ,
1.Unit tpm.service could not be found.
2._gateway (192.168.1.1) at 00:00:00:00:00:00 [ether] on eth0

**Comment by fcabrera23** [comment]
Hi,

Thanks for your details. We are aware of an issue impacting TPM provisioning using External Switch. Please follow these steps to fix it.  

1. Uninstall the EFLOW (to make sure we start from a clean state)
2. Install EFLOW MSI
3. `Deploy-Eflow` using the same configuration you used last time (External Switch)
4. On the Windows host, open a PowerShell session and use the  `ipconfig /all` command to list the adapter and physical address (mac address). Take a note of the IP address and mac address used by the network connected to EFLOW (in your case the switch used to connect the Windows host to the external network).
5. Run `Invoke-EflowVmCommand "sudo arp -s 10.0.0.2 00:0c:29:c0:94:bf"` (e.g if the Windows IP was 10.0.0.2 and MAC was 00:0c:29:c0:94:bf - Replace the IP address and mac address with the one taken from the previous step . This step is to manually add the host IP information to the EFLOW VM)
6. Run `Invoke-EflowVmCommand "sudo arp -a"` to confirm the new entry created.
7. ` Set-EflowVmFeature -feature "DpsTpm" -enable` to enable TPM passthrough.

That should fix your problem. Also, are you using EFLOW 1.1 LTS or EFLOW CR?

Thanks,
Francisco

**Comment by Dolphinsimon** [comment]
Hi @fcabrera23 ,

I have fixed the problem with your solution. Thx!

I am using EFlow CR.

**Comment by fcabrera23** [comment]
We will address this issue in our upcoming updates.

Thanks,
Francisco

**Comment by Dolphinsimon** [comment]
@fcabrera23 How can I set the arp command auto run when a reboot was initialized? I have tried to modify the rc-local.service, but the file system is read-only.
Thanks.

**Comment by fcabrera23** [comment]
Hi @Dolphinsimon,

I would recommend you create a service and enable the service on boot. Check [Issue 131](https://github.com/Azure/iotedge-eflow/issues/131). If not check our [serial passthrough sample](https://aka.ms/AzEFLOW-SerialPassthrough). 

Thanks,
Francisco
