### ISSUE TITLE
Unable to deploy EFLOW VM

### ISSUE THREAD

**Issue by kbeaugrand** [Azure/iotedge-eflow#122]
**Describe the bug**
After reinstalling IoT Edge For Linux, we cannot deploy the EFLOW VM with command line.

**To Reproduce**
1. Execute Powershelle (Run as Admin): ``Deploy-Eflow -acceptEula 'yes' -acceptOptionalTelemetry 'yes' -vswitchName "EFLOW Switch" -ip4Address "169.254.61.100" -ip4GatewayAddress "169.254.61.1" -vswitchType 'Internal' -cpuCount 2 -memoryInMB 3072``

**Expected behavior**
The EFLOW should be deployed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9513635/157039867-2cbfc0d5-43fa-4452-bb89-34c4c721008c.png)

Error message is: 
```
C:\Program Files\Azure IoT Edge\nodectl.exe compute vm show --name CLBSI4IGWEFLOW1-EFLOW -o json failed to execute [Error: rpc error: code = NotFound desc = [Store] unable to filter entity from store for type[VirtualMachineInternal], FilterName[Name], FilterValue[CLBSI4IGWEFLOW1-EFLOW]: Not Found] at line 3689
```
**Windows Host OS (please complete the following information):**
 - Edition: Windows Server 2019 Datacenter
 - Version: 17763.2458
 - Virtual Machine: VM Ware Virtual Machine
 
**Additional context**

Tested on both  : 
- AzureIoTEdge_LTS_1.1.2111.17111
- AzureIoTEdge_LTS_1.1.2202.21022

**Comment by fcabrera23** [comment]
Hi @kbeaugrand,

Thanks for your information.  I have just finished setting up a similar environment and I was able to deploy EFLOW without any issues, so maybe there's something I'm missing. Could you please share the following information?

1. What VMWare product are you using? It's ESXi or Workstation? What version?
2. In the VM setup, under VBS, did you turn on _Enable Virtualization Based Security_?
3. Did you apply all the Windows Server updates?
4. Did you try creating another VM using the same switch? If so, did the VM get an IP address assigned?

Thanks,
Francisco

**Comment by kbeaugrand** [comment]
Hi Francisco, 

The initial installation was working well in fact. 
I suspect the issue coming from manually trying to update to from1.1.2111.17111 to 1.1.2202.21022 the EFLOW.

Since this try, we are unable to provision the VM with the issue mentioned.

**Comment by fcabrera23** [comment]
Hi @kbeaugrand,

Thanks for the update. Could you please explain your process?

1. Fresh MSI installation
2. Deploy-Eflow
3. Manually tried applying update from 1.1.2111 directly to 1.1.2202
4. Deploy-Eflow again?

To update from 1.1.211 to 1.1.2202, you'll need first to apply previous updates (1.1.2112 and 1.1.2201). 

Thanks,
Francisco

**Comment by adcoly** [comment]
Firstly I uninstall the 1.1.2111.17111 EFLOW, I installed the new one (1.1.2202.21022), and then I tried to deploy the EFLOW with the command written previously :
> 1. Execute Powershelle (Run as Admin): `Deploy-Eflow -acceptEula 'yes' -acceptOptionalTelemetry 'yes' -vswitchName "EFLOW Switch" -ip4Address "169.254.61.100" -ip4GatewayAddress "169.254.61.1" -vswitchType 'Internal' -cpuCount 2 -memoryInMB 3072`

That's all I have done to install and try to deploy the new EFLOW.

**Comment by kbeaugrand** [comment]
@fcabrera23 and @adcoly, 

When the 1.1.2111.17111 was uninstalled, the Eflow VM was deployed and working.

**Comment by fcabrera23** [comment]
Hi @adcoly , @kbeaugrand ,

Have you tried using a different IP address? Could you please share the logs under C:\ProgramData\wssdagent?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @adcoly, @kbeaugrand,

Also, please take a look at our official [EFLOW PS documentation](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06). When using Static IP and a custom switch, you need to provide five parameters during EFLOW deployment using `Deploy-Eflow`.

<html>
<body>


Parameter | Accepted values | Comments
-- | -- | --
vswitchName | Name of the virtual switch | Name of the virtual switch assigned to the EFLOW VM.
vswitchType | Internal or External | Type of the virtual switch assigned to the EFLOW VM.
ip4Address | IPv4 Address in the range of the DCHP Server Scope | Static Ipv4 address of the EFLOW VM.
ip4PrefixLength | IPv4 Prefix Length of the subnet | Ipv4 subnet prefix length, only valid when static Ipv4 address is specified.
ip4GatewayAddress | IPv4 Address of the subnet gateway | Gateway Ipv4 address, only valid when static Ipv4 address is specified.


</body>
</html>

I think you're issue is related to not providing the **ip4PrefixLength** parameter. 

Thanks,
Francisco

**Comment by kbeaugrand** [comment]
Hi @fcabrera23 , 

Thank you for this review !
Effectively, this is a missing parameter. 

Could you also tell us how it's suppose to work with the DNS ?

**Comment by fcabrera23** [comment]
Hi @kbeaugrand,

Thanks for the update - Did you manage to get the EFLOW VM deployed correctly?
Also, for DNS servers, there's an EFLOW PS cmdlet: `Set-EflowVmDnsServers`.

Thanks,
Franicsco
