### ISSUE TITLE
ADU Iot-Hub Device Update not available on EFLOW?

### ISSUE THREAD

**Issue by RichardHubertPtw** [Azure/iotedge-eflow#125]
Hi, we are concerned about seemingly contradictory messages regarding the use of IoT-Edge with Azure IoT-Hub Device Update (ADU) and the additional effort/risk it incurs in our product development. In particular this message:

[can-i-use-iot-hub-device-update-with-eflow](https://github.com/Azure/iotedge-eflow/wiki/Updates#can-i-use-iot-hub-device-update-with-eflow)

We tried using IoT-Edge on Windows native and it became increasingly difficult to keep up with the Linux curve and stability. As such, for IoT-Edge development, we made the same move to Linux that Microsoft did and we were thrilled to see the EFLOW strategy which would enable us to still support "windows native" for our customers. In the Linux context, the update mechanism of choice -- as provided and encouraged by Microsoft -- is ADU. So, we use this on Linux already. Now we read that this is not available on EFLOW. 

Can anyone clear up the logic behind this, and above all, what is the proposed strategy for IoT-Edge Update developers besides "figure it out and do it twice"?

Thanks for your help!

**Comment by fcabrera23** [comment]
Hi Richard,

I'm sorry to hear that the current documentation is not clear; we're working on a new set of docs to be published in the upcoming weeks.

Regarding EFLOW updates, the VM has a read-only rootFS and no package manager. All the package updates (CVEs or performance) are updated through Microsoft update as an A/B update. There's no need, and it's impossible to update each package by itself as you would with another Linux distribution using, for example, APT package manager. We keep up to date with all the CBL-Mariner CVE patches and stick to an SLA depending on the severity of the CVEs. As long as you have the Microsoft optional updates turned on, you won't need to worry about the package updates; we will take care of it through our EFLOW servicing updates. 

ADU is the recommended way to go when you're using IoT Hub on a Linux device. In this case, you do have a package manager, and you'll have to take care of the patching of the OS. EFLOW is a "border" case, as it's a Linux distribution, however, we manage it as a Windows feature, and ADU does not apply, as no package manager updates are needed. I hope that answers your question.

Thanks,
Francisco

**Comment by RichardHubertPtw** [comment]
Thank you Francisco for the reply. I understand your design priorities and trade-off selections. However, it also still competes with the recommended ADU approach on Linux. Actually, we use ADU on devices without apt/apt-get. The ADU is just installed as part of the BoardSupportPackage (firmware). So I do have one more last question for our EFLOW scenario where we have an iot-edge running with several custom modules: why couldn't ADU also be installed as an integral part of your Mariner distribution. We could still use ADU with most of its useful features. We'd just need to avoid using apt/apt-get in that scenario but we could still download our own scripts and update our infrastructure within the same ADU-context that we use for our native-Linux and Device scenarios. Just asking :) In any case, we appreciate the EFLOW approach. Regards!

**Comment by fcabrera23** [comment]
Hi Richard,

Thanks for your clarifications and feedback.  We haven't considered this scenario, but I'll do a further investigation, and we could consider it as a potential feature improvement for upcoming updates.

Thanks,
Francisco
