### ISSUE TITLE
Deploy Eflow VM failed

### ISSUE THREAD

**Issue by adcoly** [Azure/iotedge-eflow#126]
**Describe the bug**
Deploy fails while trying to instantiate VM.

**To Reproduce**
1. Execute powershell (run as an admin): `Deploy-Eflow -acceptEula 'yes' -acceptOptionalTelemetry 'yes' -vswitchName "EFLOW Switch" -ip4Address "169.254.61.100" -ip4GatewayAddress "169.254.61.1" -ip4PrefixLength 24 -vswitchType 'Internal' -cpuCount 2 -memoryInMB 3072`

**Expected behavior**
The Eflow VM should be deployed.

**Screenshots**
![image](https://user-images.githubusercontent.com/33126264/158784131-f5fa9854-3df1-4a61-a809-56d23d70108c.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows Server 2019 Datacenter
 - Version: 17763.2458
 - Virtual Machine: VM Ware virtual machine
 
**Additional context**
Iot edge version : AzureIoTEdge LTS 1.1.2202.21022
wssdagent.log: 
`[LOG: 03-17 10:41:0000045 TraceID: virtualmachine.go:48  d678a5362cf4ea766e185191518adb09] [VirtualMachineAgent] [Invoke] Request[VirtualMachineSystems:<name:"CARSI4IGWEFLOW-EFLOW" > ]
[LOG: 03-17 10:41:0000045 TraceID: virtualmachine.go:61  d678a5362cf4ea766e185191518adb09] [VirtualMachineAgent] [Invoke] Request[VirtualMachineSystems:<name:"CARSI4IGWEFLOW-EFLOW" > ] Response[], Error [Not Found
[Store] unable to filter entity from store for type[VirtualMachineInternal], FilterName[Name], FilterValue[CARSI4IGWEFLOW-EFLOW]
github.com/microsoft/moc/pkg/errors.Wrapf
	/home/johnson/go/pkg/mod/github.com/johnsonshih/moc@v0.10.8-alpha.10.0.20210526222753-7f9ed43aa602/pkg/errors/errors.go:118
github.com/microsoft/moc-pkg/pkg/store.(*ConfigStore).filterObjects
	/home/johnson/go/pkg/mod/github.com/johnsonshih/moc-pkg@v0.10.8-alpha.9.0.20211027045303-eae454bfa8d5/pkg/store/store.go:632
github.com/microsoft/moc-pkg/pkg/store.(*ConfigStore).ListFilter
	/home/johnson/go/pkg/mod/github.com/johnsonshih/moc-pkg@v0.10.8-alpha.9.0.20211027045303-eae454bfa8d5/pkg/store/store.go:563
github.com/microsoft/wssdagent/pkg/nodeagent/services/compute/virtualmachine.(*Client).Get
	/home/johnson/repos/wssdagent.js/pkg/nodeagent/services/compute/virtualmachine/client.go:437
github.com/microsoft/wssdagent/pkg/nodeagent/services/compute/virtualmachine.(*VirtualMachineProvider).Get
	/home/johnson/repos/wssdagent.js/pkg/nodeagent/services/compute/virtualmachine/virtualmachine.go:39
github.com/microsoft/wssdagent/pkg/nodeagent/server.(*virtualmachineAgentServer).Invoke
	/home/johnson/repos/wssdagent.js/pkg/nodeagent/server/virtualmachine.go:52
github.com/microsoft/moc/rpc/nodeagent/compute._VirtualMachineAgent_Invoke_Handler
	/home/johnson/go/pkg/mod/github.com/johnsonshih/moc@v0.10.8-alpha.10.0.20210526222753-7f9ed43aa602/rpc/nodeagent/compute/moc_nodeagent_virtualmachine.pb.go:1159
google.golang.org/grpc.(*Server).processUnaryRPC
	/home/johnson/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024
google.golang.org/grpc.(*Server).handleStream
	/home/johnson/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/home/johnson/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722
runtime.goexit
	/usr/lib/go-1.15/src/runtime/asm_amd64.s:1374]
[SPAN_START: 03-17 10:41:0000045 TraceID: d678a5362cf4ea766e185191518adb09] Name: VirtualMachine Get CARSI4IGWEFLOW-EFLOW  SpanID: 32393037313838343836616562633962  ParentSpanID: 61326637363739393162356161363137  Duration: 0.00s
[SPAN_END: 03-17 10:41:0000045 TraceID: d678a5362cf4ea766e185191518adb09] Name: VirtualMachine Get CARSI4IGWEFLOW-EFLOW  Duration: 0.00s
[SPAN_END: 03-17 10:41:0000045 TraceID: d678a5362cf4ea766e185191518adb09] Name: Received gRPC call to VirtualMachine Agent  Duration: 0.00s`

**Comment by fcabrera23** [comment]
Hi @adcoly,

I'm sorry to hear that you had an issue; it seems that it got fixed. From your information, you're running a Server VM on top of VMWare. This scenario needs a specific configuration to work, and sometimes you need to reboot the Windows VM after applying the configuration to get it to work. 

Because you were able to deploy it successfully, I'll close the issue and if you face the same problem again, feel free to reopen it. 

Thanks,
Francisco
