### ISSUE TITLE
Deploy-Eflow

### ISSUE THREAD

**Issue by ManuInNZ** [Azure/iotedge-eflow#129]
**Describe the Problem**
Installing EFlow CR on Windows 10 x64 using Powershell Core complains about types

**To Reproduce**
1. Use PowerShell Core (7.2.2)
2. Install [AzureIoTEdge.msi](https://aka.ms/AzEFLOWMSI-CR-X64)
3. Run deploy command:
```PowerShell
Deploy-Eflow -cpuCount 2 -memoryInMB 2048 -vmDataSize 20 -acceptEula yes -acceptOptionalTelemetry no
```
```PowerShell
[03/21/2022 20:31:05] Deploying Azure IoT Edge for Linux on Windows

 - WARNING: This is a Public Preview version of Azure IoT Edge for Linux on Windows Continuous Release, not intended for production use.
 - WARNING: A clean install may be required for production use once the final General Availability (GA) release is available. For more information, check https://aka.ms/AzEFLOW-CR.

[03/21/2022 20:31:24] Exception caught!!!

 - The type initializer for 'TelemetryHelper' threw an exception. (L1032)

[03/21/2022 20:31:24] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

OperationStopped: The type initializer for 'TelemetryHelper' threw an exception.
```

**Expected behavior**
Successful deployment of the EFLOW VM

**Screenshots**
![image](https://user-images.githubusercontent.com/7937408/159221838-d7870c02-ed5e-430c-a01c-ef9f4319b72f.png)

**Windows Host OS (please complete the following information):**
Edition	Windows 11 Enterprise
Version	21H2
OS build	22000.588
Experience	Windows Feature Experience Pack 1000.22000.588.0
Local Machine (Dev)
 
**Additional context**
Attempting the same command with Windows PowerShell (5.1.22000.588) seems to be working. _pending installation completion_

**Comment by fcabrera23** [comment]
Hi @ManuInNZ,

It seems to be an error with PS7. I'll try to repro it and will reach back.

Thanks,
Francisco

**Comment by ManuInNZ** [comment]
Just for other that might face the same issue.
The install is to be done using Windows PowerShell (version 5.1.x).
Until a next release of the msi package there might be tweaking required to the PowerShell module (C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1), if you face the issue.

First changing the way to get the version in the TelemetryHelper (thanks @fcabrera23 )
```powershell
    static [String] $version = (Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\' | Get-ItemProperty |  Where-Object {$_.DisplayName -eq 'Azure IoT Edge'}).DisplayVersion
```

and then if you have further issues on the check for windows update (e.g. it is present but enforced via MDM policies), then comment out to ignore this check.
![image](https://user-images.githubusercontent.com/7937408/160024930-0d125ff4-ae2a-458f-ae6c-a5a8101719cc.png)
