### ISSUE TITLE
Error deploying eflow through Azure Pipelines

### ISSUE THREAD

**Issue by ericvruder** [Azure/iotedge-eflow#13]
**Describe the bug**
Whenever I try to Deploy Eflow through Azure Pipelines, I get the following error:

```
[03/24/2021 10:56:36] Step 5: Installing and verifying virtual machine software 

 - Installing and verifying required virtual machine features (username: iotedge-user)

[03/24/2021 10:56:38] Exception caught!!!

 - Importing GPG key 0x3135CE90: at line 2324

[03/24/2021 10:56:38] Exception caught!!!

 - Installing software in virtual machine failed (L762)

[03/24/2021 10:56:38] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh
```

**To Reproduce**
- Install eflow
- Create a simple pipeline that tries to run `Deploy-Eflow -acceptEula 'yes' -acceptOptionalTelemetry 'no' -enableVtpm -vnetType 'ICS' -vnetName 'Default Switch'`
- Run that pipeline.
- It fails in step 5, everything else is completly sucessfully

**Expected behavior**
I would expect it to deploy it correctly. 

**Windows Host OS (please complete the following information):**
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎27-‎02-‎2021
OS build	19042.868
Experience	Windows Feature Experience Pack 120.2212.551.0
 
**Additional context**
The pipeline agent is running as NT Authority\System. After it fails, I can actually use the pipeline to remove the VM successfully. I can't log in to the machine and remove it though. Whenever I try to do that, I get the following error:

` C:\iotedge\nodectl.exe  compute vm list -o tsv --query "[*].name" failed to execute [Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"] at line 2336`

I have to remove the vm, uninstall Eflow, and then reinstall it to get it into a valid state again. 

If I logon to the machine and install it with an admin user, it successfully installs. 

If I then run the Verify-EflowVm in the pipeline, it fails with the following error:
`- Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"NodeAgent\")" at line 2324
`
This is the same error that I get after trying to deploy with pipeline, and then logging into the machine and running verify-eflowvm (or any other command associated with eflow, for that matter).

I am guessing there are issues using eflow from different users, but what can I do about the original error? (Importing GPG key 0x3135CE90)

**Comment by TerryWarwick** [comment]
@ericvruder,

Thank you for the detailed issue report.  I do not believe this is a scenario that we have considered thus far.  Perhaps the issue is that our script is making an assumption that it is running under an Admin account rather than a System account.  Can you invoke the command from the pipeline as an Admin rather than System account? 

I will file a bug on your behalf for this issue, but any additional information you can provide would be greatly appreciated. 

Terry Warwick
Microsoft
#32231675

**Comment by ericvruder** [comment]
@TerryWarwick, I am really sorry but that is not something I can easily do. I'll try to see if I can find time at a later time to install the agent to run with the administrator account, but unfortunately that is not something that is that straight forward in my current setup. 

But thank you for filing the rerpot!

**Comment by ericvruder** [comment]
@TerryWarwick , sorry for taking this long to test it out.

But it seems to work though if using a admin account. Created a Azure VM, installed eflow on it and then installed the agent on it using the admin user. 

I then got my agent to deploy agent to deploy to it. Or at least start the process, there where(are) some issues with vTpm and the VM. But this doesn't really matter - it started the process and got much further than previously. 

Things to note: 
- Verify-EflowVm fails if the VM has not yet been installed. So, straight after installing eflow, before deploying, it will fail. Not sure if this is intended or not - I would expect it to return false. 
- Admin user was called ericvruder. Pretty sure this doesn't matter, but the more info the better.

**Comment by fcabrera23** [comment]
Thanks @ericvruder  for your notes. We will take that into account in our future updates.
