### ISSUE TITLE
Systemd services created using Invoke-EflowVmCommand gets masked after reboot

### ISSUE THREAD

**Issue by bkarrlander** [Azure/iotedge-eflow#131]
Hi,

We are trying to ping the windows host from the VM, at every startup. We have created a systemd service for this and it works fine  every reboot when we create the service logged in with Connect-EflowVm or SSH.

But when we try to create the same thing using the same commands but through Invoke-EflowVmCommand in our automated EFLOW setup Powershell-script, then the service gets masked after reboot and never run.

This is the unit file, startup-ping.service:

```
[Unit]
Description=Ping host after reboot to recover from tpm2-socat failing to reach host after EFLOW restart
Requires=network-online.target
After=network-online.target
[Service]
ExecStart=/usr/bin/ping hostname.sdcad.se -c 1
[Install]
WantedBy=multi-user.target

```

And this is how we activate it. Works after every reboot:

```
sudo chmod 644 /etc/systemd/system/startup-ping.service
sudo systemctl enable startup-ping.service
```

Here's the PowerShell version of creating the same thing:

```
Function EnableStartupPing($hostname)
{
    # Create a systemd unit file
    $unitfile="startup-ping.service"
    Invoke-EflowVmCommand "sudo echo [Unit] > $unitfile"
    Invoke-EflowVmCommand "sudo echo Description=Ping host after reboot to recover from tpm2-socat failing to reach host after EFLOW restart >> $unitfile"
    Invoke-EflowVmCommand "sudo echo Requires=network-online.target >> $unitfile"
    Invoke-EflowVmCommand "sudo echo After=network-online.target >> $unitfile"
    Invoke-EflowVmCommand "sudo echo [Service] >> $unitfile"
    Invoke-EflowVmCommand "sudo echo ExecStart=/usr/bin/ping $hostname.sdcad.se -c 1 >> $unitfile"
    Invoke-EflowVmCommand "sudo echo [Install] >> $unitfile"
    Invoke-EflowVmCommand "sudo echo WantedBy=multi-user.target >> $unitfile"
    
    Invoke-EflowVmCommand "sudo mv $unitfile /etc/systemd/system/$unitfile"

    # Set permissions and enable 
    Invoke-EflowVmCommand "sudo chmod 644 /etc/systemd/system/$unitfile"
    Invoke-EflowVmCommand "sudo systemctl enable $unitfile"
}
```

And here's the service status after reboot after Powershell-script. i.e, the service is masked and won't run:

```
iotedge-user@BIOB124-EFLOW [ ~ ]$ sudo systemctl status startup-ping
* startup-ping.service
   Loaded: masked (Reason: Unit startup-ping.service is masked.)
   Active: inactive (dead)
```

I suspect we are we doing something wrong/crazy but can't figure out what. Or is this expected behavior?

**Versions**
Iot Edge version: 1.1.8
EFLOW version: 1.1.2112.20121
Hyper-V version: 10.0.19041.1
Windows Host: Windows 10 Pro 20H2, 19042.1288

Best regards,
Björn

**Comment by fcabrera23** [comment]
Hi @bkarrlander,

Could you please check the service creation section in our [serial sample code](https://github.com/Azure/iotedge-eflow/tree/main/samples/serial)?  Another approach of the same thing you're doing would be creating the service file on the Windows side and then copying it to the EFLOW VM. 

Also, make sure you reload the systemctl daemon before enabling the service: `sudo systemctl daemon-reload`.

**Comment by bkarrlander** [comment]
@fcabrera23 ,

Sorry for not answering sooner. We haven't had the chance to try your suggestion. For now, we're using a periodic ping from the host to the VM, which seems to have the same effect. 

Thank you
Björn

**Comment by fcabrera23** [comment]
Hi @bkarrlander,

Thanks for sharing your suggestion. We plan to fix this issue in upcoming versions of EFLOW. 

Thanks,
Francisco
