### ISSUE TITLE
Unable to deploy eflow vm with iotedge 1.1

### ISSUE THREAD

**Issue by LanceLiMS** [Azure/iotedge-eflow#132]
**Describe the bug**
Cx is following the doc: [Create and provision an IoT Edge for Linux on Windows device using symmetric keys - Azure IoT Edge | Microsoft Docs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-symmetric?view=iotedge-2018-06&preserve-view=true&tabs=azure-portal%2Cpowershell)

They are able to deploy eflow-vm with iotedge 1.2 but failed with iotedge 1.1

**To Reproduce**

1. Follow the docs to deploy eflow-vm with iotedge 1.2, works well
2. Uninstall iotedge 1.2 and then deploy eflow-vm with iotedge 1.1 from the scratch.
3. Got an exception after running Deploy-Eflow

	- Could not find a part of the path 'C:\Program Files\Azure IoT Edge\LICENSE\Azure IoT Edge for Linux on Windows - Standalone (free) Use Terms (11.1.21).rtf'. (L402)

**Expected behavior**
Able to deploy eflow vm with iotedge 1.1

**Screenshots**
![image](https://user-images.githubusercontent.com/77827376/160086151-59056d80-07b2-464c-ac60-2da674140d47.png)

**Windows Host OS  Win 11
 - Edition: Enterprise,
 - Version: [e.g. build  22000.556

**Comment by fcabrera23** [comment]
Hi @LanceLiMS,

Thanks for your information. From the installation logs, I can see that you're still using EFLOW CR (1.2) PSM- Note that after `Deploy-Eflow` it says "WARNING: This is a public preview version...".

If you uninstall EFLOW CR MSI and then install EFLOW 1.1 LTS MSI, you should close the PowerShell session and open a new one, if not the PSM loaded won't be the correct one. Another approach could be using `Remove-Module AzureEFLOW` after uninstalling, and then `Import-Module AzureEFLOW` after installing the new MSI. 

Hope that helps,
Francisco

**Comment by fcabrera23** [comment]
Hi @LanceLiMS,

Did you try my suggestion? Were you able to install EFLOW?

Thanks,
Francisco
