### ISSUE TITLE
Fix an IP address for the eflow VM

### ISSUE THREAD

**Issue by Gimly** [Azure/iotedge-eflow#14]
**Question Summary**
I would like to give the eflow VM (the Linux machine hosted on Hyper-V) a fixed IP address to make it "play nice" with our network structure. Alternatively, is there a way to configure it so that it works as a kind of "NAT" and share the host machine's IP address?

**Detailed background**
Our IT service wants us to fix the IP address of the eflow VM so that it can have a correct access to the required resources and to the internet. By default the machine gets a DHCP address but it doesn't work correctly with out internal network structure. We therefore need to fix the IP  for the VM.

**Comment by fcabrera23** [comment]
@Gimly ,

Thank you for the detailed question and background. I do not believe this is a scenario that we have implemented so far. We will try to include a way to specify a static IP on our next updates.

**Comment by TerryWarwick** [comment]
@Gimly, 

One change that we are considering is to change the machine name inside the VM to remove the GUID that is appended to the end of the name so that it is predictable.  Would simply appending "-EFLOW" to the hose machine name allow it to "play nicer" with your network structure?

Alternatively, as fcabrera23 mentions we can also look into allowing you to specify a static IP address.

Terry Warwick
Microsoft

**Comment by Gimly** [comment]
@TerryWarwick the issue we have with the network is a bit dumb, the Linux VM registers to the DHCP server with the 18 bytes HW-address instead of the more standard MAC address and it doesn't play nice with the DHCP server. The DHCP server is probably too old to manage that kind of things and would require an upgrade which is not easy unfortunately.

We have fixed the issue on our side for now by using the "Default Switch" on hyper-v for the Linux VM.

**Comment by ngmartins** [comment]
> @Gimly,
> 
> One change that we are considering is to change the machine name inside the VM to remove the GUID that is appended to the end of the name so that it is predictable. Would simply appending "-EFLOW" to the hose machine name allow it to "play nicer" with your network structure?
> 
> Alternatively, as fcabrera23 mentions we can also look into allowing you to specify a static IP address.
> 
> Terry Warwick
> Microsoft

Is it something you were already implemented?
When I tried EFLOW before this is one of the biggest limitations to our operation: Do not have an predictable host name or a static IP address.

Thanks,

Nuno

**Comment by fcabrera23** [comment]
@ngmartins,

As part of the [EFLOW GA release](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2106.1), we change the EFLOW VM host naming.  The new naming is generated by the Windows host device name + "-EFLOW".  You can check the name of the EFLOW VM following these steps:

1. Open an elevated PowerShell sesison
2. Start an SSH connection to the EFLOW VM using the command `Connect-EflowVm`
3. Run the command `cat /proc/sys/kernel/hostname` to check the hostname.

**Comment by fcabrera23** [comment]
Hi @Gimly,

We released our latest EFLOW update that supports static IP for ICS Default Switch.  For more information on our latest update, check [1.1.2107.0 Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0).  To set a Static IP, check [PowerShell functions for IoT Edge for Linux on Windows](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06).

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello, @fcabrera23 maybe I am missing something very obvious but I wasn't able to access a container web interface using `VM_HOSTNAME:port`. 
`VM_IP_ADDRESS:port` worked just fine. However, because the IP address is not static use the hostname would be preferable.

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Have you tried pining the hostname and check the hostname resolution is correct?
Also, we are releasing a new update that supports the static IP this week. Will that work?

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello,

I am using the hostame of the EFLOW VM. In fact, by pinging it from the hots machine the address is not resolved. 
But at the host machine level, it seems to be the only host that the DNS server isn't able to resolve.
Is this something I need to configure from the VM side?

Use fixed IP would work, but the host is something predictable. Having the chance, the hostname would always be my first choice.

Thanks once again, 
Nuno

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for your information. I'll look into your issue and will let you know if there's a fix.  In the meantime, I would suggest keeping up to date with the [latest releases](https://github.com/Azure/iotedge-eflow/releases).

Thanks,
Francisco

**Comment by Salavertus** [comment]
Hello, I am having troubles setting an satatic IP address to the Default Switch:

`Cannot set Static IP on ICS type virtual switch (Default Switch)
En C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1: 5074 Carácter: 13
+             throw "Cannot set Static IP on ICS type virtual switch (D ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot set Stat...Default Switch):String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot set Static IP on ICS type virtual switch (Default Switch)`

and then 

`Add-EflowVmEndpoint -vSwitchName "Default Switch" -vEndpointName "EFLOW" -ip4Address "172.17.44.246" -ip4GatewayAddress "255.255.255.240" -ip4PrefixLength "24"`

For the installation I have followed the steps in [this ](https://learn.microsoft.com/en-us/azure/iot-edge/quickstart?view=iotedge-1.4)MS Learn tutorial.

Thank you in advance.

**Comment by fcabrera23** [comment]
Hi @Salavertus,

The Default Switch does not support Static IP (by design of the virtual switch). For more information, check [IoT Edge for Linux on Windows networking](https://learn.microsoft.com/en-us/azure/iot-edge/iot-edge-for-linux-on-windows-networking?view=iotedge-1.4). 

Thanks,
Francisco

**Comment by Salavertus** [comment]
Thank you for your fast response, @fcabrera23, I was aware of that limitation but today I read one of your replies more than a year ago:

> We released our latest EFLOW update that supports static IP for ICS Default Switch. For more information on our latest update, check [1.1.2107.0 Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0). To set a Static IP, check [PowerShell functions for IoT Edge for Linux on Windows](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06).
> 
> Thanks, Francisco

I'm sure there is something else I don't understand about this, then.

In any case, Is there any way to connect from an IoT Edge module to the host without have an static IP? (I mean If I hardcode the direction and the IP changes that aproximation is not suitable) my plan is to build a C# module that queries an SQL Express DB running in the host (W10 outside que VM) but I am facing a lot of troubles and I cannot find documentation about that use case.

Any help would be very apreciated since I'm a bit lost now for days already. 

Thank you in advance,
Álvaro.

**Comment by fcabrera23** [comment]
Hi @Salavertus,

Thanks for the reference, but that seems to be quite old version and we removed that in newer versions.  If you are using Default Switch, you can use the EFLOW hostname + "mshome.net". So, if you're Windows host OS hostname is "DESKTOP-TEST", then the EFLOW VM hostname will be "DESKTOP-TEST-EFLOW", and you can use the full address to ping the IP, like "DESKTOP-TEST-EFLOW.mshome.net".

Thanks,
Francisco

**Comment by Salavertus** [comment]
Perfect, @fcabrera23. I think it can work. 

Since I need to connect to an SQL DB in the W10 host, my custom module should retrieve the EFLOW hostname and then remove the "-EFLOW" part and add the ".mshome.net" and I should be able to query my local Database from the Edge module.

Thank you.
