### ISSUE TITLE
Issue with AzureIoTEdge_LTS_1.1.2203.14042.msi

### ISSUE THREAD

**Issue by leeprtc** [Azure/iotedge-eflow#141]
**Describe the Problem**
Downloaded and installed EFLOW from https://aka.ms/AzEflowMSI. Getting the following error when calling Deploy-Eflow.

 - Could not find a part of the path 'C:\Program Files\Azure IoT Edge\LICENSE\Azure IoT Edge for Linux on Windows - Standalone (free) Use Terms (11.1.21).rtf'. (L402)

**To Reproduce**
1. Download from https://aka.ms/AzEflowMSI and install.
2. Run Deploy-Eflow cmdlet in PowerShell
3. See error

**Expected behavior**
Deploy-Eflow should complete successfully

**Screenshots**
PS C:\EFLOW> Deploy-Eflow -cpuCount 2 -memoryInMB 4096 -vmDiskSize 21 -vswitchName "Internal Switch" -vswitchType Internal

[04/27/2022 09:36:35] Deploying Azure IoT Edge for Linux on Windows

 - WARNING: This is a Public Preview version of Azure IoT Edge for Linux on Windows Continuous Release, not intended for production use.
 - WARNING: A clean install may be required for production use once the final General Availability (GA) release is available. For more information, check https://aka.ms/AzEFLOW-CR.
 - Configuration does not exist. Creating a default configuration...

[04/27/2022 09:36:35] Creating configuration

 - Configuration created successfully

[04/27/2022 09:36:36] Exception caught!!!

 - Could not find a part of the path 'C:\Program Files\Azure IoT Edge\LICENSE\Azure IoT Edge for Linux on Windows - Standalone (free) Use Terms (11.1.21).rtf'. (L402)

[04/27/2022 09:36:36] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

Could not find a part of the path 'C:\Program Files\Azure IoT Edge\LICENSE\Azure IoT Edge for Linux on Windows - Standalone (free) Use Terms (11.1.21).rtf'.

PS C:\EFLOW> dir "C:\Program Files\Azure IoT Edge"

    Directory: C:\Program Files\Azure IoT Edge

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/27/2022   9:36 AM                dda-drivers
d-----         4/27/2022   9:36 AM                mariner-files
-a----         4/15/2022   4:27 AM      560100153 AzureIoTEdgeForLinux-v1.cab
-a----         4/15/2022   4:26 AM          19215 EFLOWProvider.man
-a----         4/15/2022   4:32 AM         314776 EFLOWProxy.exe
-a----         4/15/2022   4:28 AM          15086 Install-Eflow.ps1
-a----         4/15/2022   4:25 AM              0 mariner-update.swu
-a----         4/15/2022   4:30 AM       18542488 nodectl.exe
-a----         4/15/2022   4:28 AM          20629 Uninstall-Eflow.ps1
-a----         4/15/2022   4:28 AM          28198 Update-Script.ps1
-a----         4/15/2022   4:30 AM       28323224 wssdagent.exe

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 Pro 
 - Version: build 19044.1645
 - Virtual Machine: None
 
**Additional context**
None

**Comment by fcabrera23** [comment]
Hi @leeprtc,

Thanks for your information. From the logs below, it seems that you had an EFLOW CR installation before, and probably uninstall and install the LTS version, but never closed the PowerShell session, so the loaded PSM is the one for EFLOW CR and not the for EFLOW LTS.

I would suggest, either closing the PS session, or using the `Remove-Module AzureEFLOW` and then `Import-Module AzureEFLOW` after MSI reinstallations. 

Thanks,
Francisco

**Comment by leeprtc** [comment]
Yes, I previously had install the EFLOW CR using the short link and did not close the PS session. Closing the PS session resolve the issue. 

Just a comment. It is not that intuitive that an uninstall of EFLOW does not remove everything. Granted, I'm not sure there is anything that could be done for an existing PS session with the loaded PSM. Maybe a popup during the uninstall to alert users to close any PS session would be helpful.

I'll close this issue.
