### ISSUE TITLE
DefenderIotMicroAgent Module

### ISSUE THREAD

**Issue by jdbelo** [Azure/iotedge-eflow#150]
Hi,
I've recently realized that a new module identity, whose name is DefenderIotMicroAgent, appeared on my devices modules list.

![Screenshot 2022-05-17 at 18 07 46](https://user-images.githubusercontent.com/10589275/168871083-feaac06e-9c50-49dd-acf4-32607fd0d414.png)

Does anyone have faced the same situation? Is it normal?
Many thanks.
Cheers

**Comment by fcabrera23** [comment]
Hi @jdbelo,

EFLOW CR version has Defender for IoT integrated by default, although it's turned off. The IoT Edge 1.2 runtime will check if this is present, and if so, will show that "module identity" in the Azure portal, although there's no actual D4IoT module running.  Even if you turn on the Defender service on, that doesn't mean that a new module will be running, it's already running as a service, so you don't have to worry about it.

Thanks,
Franciscco
