### ISSUE TITLE
Azure IoT Edge extension for Windows Admin Center might be stuck at the Settings page on Japanese version of Windows

### ISSUE THREAD

**Issue by riwaida** [Azure/iotedge-eflow#151]
**Describe the bug**
Azure IoT Edge extension for WAC might be stuck at the page "2.2 Settings" due to _ajax error 400_. I confirmed that the problem happens on Japanese version of Windows 10 and 11.
![2_2_Settings](https://user-images.githubusercontent.com/42270443/169013095-aa634d43-dda7-4310-972a-4364514282f0.png)

**Steps To Reproduce**
Please follow steps below on Japanese version of Windows.
1.  Follows steps [Install IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-symmetric?view=iotedge-2018-06&tabs=azure-portal%2Cwindowsadmincenter#install-iot-edge) to deploy IoT Edge.
2. The page does not show anything at the "2.2 Settings" page.
3. Press F12 key on your browser to open DevTools. The console shows an error as follows.
"ajax error 400"
4. Click Network tab of the DevTools pane, you will see an exception message as follows.
![network-preview](https://user-images.githubusercontent.com/42270443/169018825-fc4630e4-a971-442f-be4c-c29875983857.png)

**Expected behavior**
The page "Configuration Settings" will be shown like below.
![expected](https://user-images.githubusercontent.com/42270443/169020941-59ed78b0-87c2-4987-be58-b547b1bcc31e.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 or 11 Enterprise Japanese
 - Version: 21H2 19044 or 22000
 - Virtual Machine: Local VM
 
**Workaround**
If you enable "Beta: Use Unicode UTF-8 for worldwide language support" option then you can avoid this problem. 
The option can be enabled by following steps.
1. Enter Win+R key. Type "intl.cpl" at the Run dialog.
2. Click the Administrative tab.
3. Click the "Change system locale" button.
4. Enable "Beta: Use Unicode UTF-8 for worldwide language support".
5. Reboot the OS.

**Comment by fcabrera23** [comment]
Hi @riwaida,

Thanks for letting us know about the issue and workaround. Windows Admin Center EFLOW extension is currently under Public Preview, and we do not plan to release an update in the short term. I'll add this issue to our backlog for future development.

Thanks,
Francisco
