### ISSUE TITLE
EFLOW deployment failing

### ISSUE THREAD

**Issue by techipank** [Azure/iotedge-eflow#159]
**Describe the Problem**
Hi Team,
I followed [this](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-x509?view=iotedge-2020-11&tabs=azure-portal%2Cpowershell) document to deploy but having couple of issues as follows:

1. After following steps it installed Azure IoT Edge msi on my windows which i am unable to uninstall.
2. Provisioned failed and not able to connect to VM whenever i try to connect i am getting below error
`ERROR: 0x80072741`

**Windows Host OS (please complete the following information):**
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎12/‎17/‎2021
OS build	19042.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by fcabrera23** [comment]
Hi @techipank,

Thanks for your update - We will try to repro your issue. In the meantime, you can uninstall using the [Windows troubleshooter](https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d).

Please let me know if that works for you.

Thanks,
Francisco

**Comment by techipank** [comment]
Hi @fcabrera23 ,
Thanks for the info but Windows troubleshooter doesn't help and it completed with below screenshot:
![image](https://user-images.githubusercontent.com/5499405/174527688-a9e88976-561b-48f0-9b5e-04e2b64c17b2.png)

**Comment by fcabrera23** [comment]
Hi @techipank,

What's the error when you try uninstalling from Apps list?  Can you try the following steps:

1.	Download [Microsoft Program Install and Uninstall](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Ftopic%2Ffix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d&data=04%7C01%7Cfrancisco.cabrera%40microsoft.com%7C394dea9cf28a425eb72f08da0910aa2f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637832264462478124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mYkG9RF019Ru6YlwmB6a12thCdFYrelM4ikJSVWqyQw%3D&reserved=0)
2.	Run the downloaded tool
3.	Select Next and wait for the problem detection to end
4.	Select Uninstalling
5.	Wait for problem detection ends (can take some minutes)
6.	Select Azure IoT Edge LTS from the list
7.	Select Yes, try uninstall and wait for the uninstallation to finish

**Comment by techipank** [comment]
Hi @fcabrera23 ,
I did the same thing only but for me Step 4,5,6,7 is not coming after 3rd step i got the above screenshot.

**Comment by Nilas1994** [comment]
what i did is Stop-eflowVm and Start-eflowvm and it worked again.
