### ISSUE TITLE
Running Examples and getting RemoteCertificateValidationCallback error

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#16]
**Question Summary**
I'm running the Windows10IOT samples example  (console version) and getting a RemoteCertificateValidationCallback exception when I call the deviceClient.SetMethodHandlerAsync(...) call.   How can I track down this problem? 
**Detailed background**
I've followed ever step in the demo.  I've generated the certs and SCP'd them to eflow. 
Along the way I notice some things like : 
   Step 6: Configuring the edge device.  
     the instructions say to upload all the local files in the edgeCertificates\certs folder yet there is also a private folder and the instructions in the editiing the config.yaml point to needing the key.pem 
     When replacing the eflow hostname with the IP address.. the iotedge check command reports an error about the ip address but that seems not to be a causal problem (that I can tell as the device console client seems to make some sort of connection, if I use the hostname from my os I get a timeout on connect error)
Here is the error I see in the check command:
 config.yaml has correct hostname - Error
    config.yaml has hostname 10.0.13.80 but device reports hostname USWE-944TPV2-L-EFLOW-8cc59340.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.

I generated the certificate material by just  following the instructions here (although you have to replace openssl.dockerfile with dockerfile):
https://github.com/Azure-Samples/IoTEdgeAndMlSample/tree/master/CreateCertificates

I guess the sample's cert generation instructions could benefit from more clarity.  Like if I don't want to use a separate VM to just generate keys... a direct pointer to a couple of scripts would go a long way to eliminating ambiguity.  

But overall any pointers on debugging this problem?  

Thanks a ton!

In following the example instructions I ended up using .net core 5 (I think these samples were 3.1 originially... not sure that matters)

Ideally it would be nice to get down to the AmqpTransport layer and get more detailed logging as to what the problem is.  

also when I am ssh-eflowvm and in the EFLOW Linux os... when I run sudo iotedge version I get iotedge 1.1.0 ... is 1.2 out?  Should I be updating?     

Thanks!

**Comment by hooligan495** [comment]
I got past the RemoteCertificateValidation error.  It turned out I had an extra space in front of certificates in teh config.yaml.

Ugh... kills me every time.

**Comment by fcabrera23** [comment]
@hooligan495,

Thank you for the detailed information. Were you able to fix it? 

Regarding the EFLOW version, we are currently in version 1.0.1.0 and will be releasing version 1.0.2.0 next week.  Both versions have Azure IoT Edge 1.1 LTS.

**Comment by hooligan495** [comment]
Yes. I was.  It's working now.  Thanks!  and thanks for the information on the versions!   Will eflow eventually upgrade to Edge 1.2?

**Comment by fcabrera23** [comment]
Yes, we have a plan to upgrade in the future, but we will keep 1.1 LTS in our following updates.
