### ISSUE TITLE
how to install any rpm package in EFLOW

### ISSUE THREAD

**Issue by aakash-v-virani** [Azure/iotedge-eflow#165]
**Question Summary**
How to install any rpm packages in  EFLOW ?

**Detailed background**
Since EFLOW based on with CBL-mainer, not able to find a way to install rpm package.

**Comment by fcabrera23** [comment]
Hi @aakash-v-virani,

Thanks for your question. For security and servicing reasons, the EFLOW virtual machine has a read-only root filesystem and no package manager, so you cannot add packages to the original composition.  For more information, please check [EFLOW Security](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-for-linux-on-windows-security?view=iotedge-2020-11).

If you want to use a pure CBL-Mariner virtual machine (not the EFLOW one), you can check [CBL-Mariner](https://github.com/microsoft/CBL-Mariner). The package manager it's tdnf. 

Thanks,
Francisco
