### ISSUE TITLE
Issues while setting Proxy using - eflowautodeply

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [Azure/iotedge-eflow#171]
**Describe the Problem**
We have VM behind corporate proxy for which we configured the httpProxy in the network section of "eflow-userconfig" file but it is not setting it properly and edge runtime is not connecting to Iot hub, we checked the config.toml and other settings but the configuration of proxy is not reflecting in the files. whereas output shows "EFLOW VM deployment successfull." with all DNS and proxy setting as good.

**To Reproduce**
Eflow deployment behind a proxy.

**Expected behavior**
After successful deployment edge modules loads successfully to Eflow

**Screenshots**
![image](https://user-images.githubusercontent.com/64076463/186435169-46d19344-8291-4adf-be4e-98a32dcd81c6.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows Server 2019
 - Virtual Machine: Azure VM

**Comment by fcabrera23** [comment]
Hi @srjhunjhunwalacorp,

Thanks for reaching out. I've confirmed that there's an issue with the current proxy configuration. We will fix this issue as soon as possible and will let you know. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @srjhunjhunwalacorp,

@parameshbabu  has fixed the proxy issue - Could you please check the new documentation and try again? 

Thanks,
Francisco
