### ISSUE TITLE
Hyper-V Management Tools not getting enabled

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [Azure/iotedge-eflow#172]
**Describe the bug**
While running the eflowautodeploy , script starts failing when it has to create a New-Vmswitch, for which we need to enable the Hyper-V Management Tools manually,

**To Reproduce**
Run eflowautodeploy with "vswitchType" : "Internal".

**Expected behavior**
Script enables the Hyper-V Management Tools automatically and does not break.

**Screenshots**
![image](https://user-images.githubusercontent.com/64076463/186574772-08f2a9b5-4a31-41db-b617-71db12599781.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows 2019 Data Center
 - Virtual Machine: Azure VM

**Comment by fcabrera23** [comment]
Hi @srjhunjhunwalacorp,

Thanks for reaching out. What type of Azure VM are you using? Does it support nested virtualization?

Thanks,
Francisco

**Comment by srjhunjhunwalacorp** [comment]
Thanks @fcabrera23 it is resolve now
