### ISSUE TITLE
Issues with config.toml while setting Proxy using - eflowautodeply

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [Azure/iotedge-eflow#181]
**Describe the bug**
After the fix released for bug reported Azure/iotedge-eflow#171 we are able to set the proxies in the eflow VM but the communication over Websocket is not happening for which I referred to "https://learn.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-1.4" and tried to Configure the IoT Edge agent by updating the "/etc/aziot/config.toml".

The format given in the example is not working and had to put following from a blog to get it working. But still edge agent and hub is not loading.

```yaml
# "RuntimeLogLevel" = "debug"
 [agent]
 name = "edgeAgent"
 type = "docker"
 # imagePullPolicy = "on-create"   # "on-create" or "never". Defaults to "on-create"

 [agent.config]
 image = "mcr.microsoft.com/azureiotedge-agent:1.2"
 createOptions = { HostConfig = { Binds = ["/iotedge/storage:/iotedge/storage"] } }
 #"https_proxy" = ""
# [agent.config.auth]
# serveraddress = "example.azurecr.io"
# username = "username"
# password = "password"

 [agent.env]
# "RuntimeLogLevel" = "debug"
 "UpstreamProtocol" = "AmqpWs"
# "https_proxy" = ""
# "storageFolder" = "/iotedge/storage"
```

After putting this configuration 

**To Reproduce**
Eflow deployment behind a proxy.

**Expected behavior**
After successful deployment edge modules loads successfully to Eflow

**Screenshots**

**Windows Host OS (please complete the following information):**
Edition: Windows Server 2019
Virtual Machine: Azure VM
 
**Additional context**
[Sudo_Check.txt](https://github.com/Azure/iotedge/files/9661357/Sudo_Check.txt)

**Comment by jlian** [comment]
@srjhunjhunwalacorp does your `iotedge check` now show that the proxy settings are consistent and good?

**Comment by srjhunjhunwalacorp** [comment]
> @srjhunjhunwalacorp does your `iotedge check` now show that the proxy settings are consistent and good?

Hi Jilian,

I am getting below response where proxy address is same but IoT Edge Agent is prefixing the http:, and others not. I tried to change this from config.toml but no result. I have obfuscated the proxy address with "xx"
```yaml
"proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - Warning
    The proxy setting for IoT Edge Agent "http://xx:3128", IoT Edge Daemon "xx:3128", IoT Identity Daemon "xx:3128", and Moby "xx:3128" may need to be identical."
,,,,,,

**Comment by jlian** [comment]
Did you recreate the edgeAgent container? 
![image](https://user-images.githubusercontent.com/2320572/193645680-b504b005-1bf8-45e4-82ba-3341e7f975ad.png)

**Comment by fcabrera23** [comment]
Hi @srjhunjhunwalacorp,

There was an issue with the  _eflowAutoDeploy_ script. This issue should be fixed with https://github.com/Azure/iotedge-eflow/pull/183.

Could you please try your installation again?

Thanks,
Francisco
