### ISSUE TITLE
File Sharing Feature Supported EFLOW Build Number

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#195]
**Question Summary**
Hi Team,

https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-2018-06 

specifying 

Prerequisites
**Azure IoT Edge for Linux on Windows 1.3.1.30082 update or higher**. For more information about EFLOW release notes, see [EFLOW Releases](https://aka.ms/AzEFLOW-Releases).

But i am unable to find that version of build. Could you someone help me here OR is it by mistake build number is provided in documentation ?

Thanks,
Vishwa

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Thanks for reaching out. You can check the version number under Windows -> App or Remove Programs -> Azure IoT Edge and check the installed version.

Thanks,
Francisco

**Comment by post2vishwa** [comment]
Hi @fcabrera23 ,

Thanks for providing information.

But what I would like to share here is :

Microsoft documentation tells : EFOW  **1.3.1.30082**   (There is no such version I am observing)

https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-2018-06

but Windows->App Or Remove - Azure IoT Edge installed version is showing **1.3.1.02092**

Thanks 
vishwa

**Comment by fcabrera23** [comment]
Hi @post2vishwa ,

Thanks for catching up that error. I've just updated the documentation. Version 1.3.1.02092 should be fine. 

Thanks,
Francisco

**Comment by post2vishwa** [comment]
Thank you so much.

Regards,
Vishwa
