### ISSUE TITLE
Issue : Remove-EflowVmSharedFolder  Command is not working as expected.

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#198]
**Describe the Problem**
Issue : Remove-EflowVmSharedFolder  Command is not working as expected.

**To Reproduce**
Steps To Reproduce problem: (If required i will share the screen and walkthrough the steps).

Step 1. Install EFLOW - Latest version on Windows 11 - 22624 and above.
Step 2. Follow the steps provided at https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-1.4

'Add Shared Folder Steps'

Step 3: Once folders are mapped properly now execute

Remove-EflowVmSharedFolder -sharedfolderRoot 'C:\\Shared\\EFLOW-Shared' -hostFolderPath 'Read-Access'

It will get executed but 'Folder' on the target Linux machine still exsists. (i.e. no clean up is occuring is the issue)

Now say , we go and delete target machine folders that are mapped which are inside (/tmp/ ...) They will get deleted.

Now as we have done cleanup, execute again below command
Add-EflowVmSharedFolder -sharedFoldersJsonPath 'C:\\Shared\\EFLOW-Shared\\sharedFolders.json'

Issue : it will not create any mapping folders in target linux machine

**Expected behavior**
Remove-EflowVmSharedFolder  Command should clean up properly the folders which are on target machines.

**Windows Host OS (please complete the following information):**
 - Edition: Windows 11 - Professional,
 - Version: build 22621 and above

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Thanks for the detailed information. We will try to reproduce this issue on our end and will reach back. 

Thanks,
Francisco

**Comment by post2vishwa** [comment]
Hi @fcabrera23 ,

I opened a ticket to MS and dev team member suggested below.

•	Remove-EflowVmSharedFolder -sharedfolderRoot 'C:\\Shared\\EFLOW-Shared' -hostFolderPath 'Read-Access'
**•	Stop-eflowvm
•	Start-eflowvm**
•	Add-EflowVmSharedFolder -sharedFoldersJsonPath 'C:\\Shared\\EFLOW-Shared\\sharedFolders.json'

So basically after remove command, we need to stop and start eflow vm in order get rid of target machine orphan folders.

which worked so closing this issu.e

Thank you.
vishwa

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Correct - We will introduce the fix in future updates. In the meantime, the suggested approach will work.

Thanks,
Francisco

**Comment by post2vishwa** [comment]
Hi @fcabrera23 ,

Couple of other observation in this case are:

1. **If we provide path other than \tmp\... say for example :  \var\lib\read-only   ; then workaround suggested i.e.** 
• Remove-EflowVmSharedFolder -sharedfolderRoot 'C:\Shared\EFLOW-Shared' -hostFolderPath 'Read-Access'
**• Stop-eflowvm
• Start-eflowvm**
• Add-EflowVmSharedFolder -sharedFoldersJsonPath 'C:\Shared\EFLOW-Shared\sharedFolders.json'

is not working as expected.

**Second observation is  :**

Start-eflowVm  also not starting properly, like command stuck , I need to press Ctrl + C  to terminate it and next time if  use same command "Start-EflowVm" it will run as expected.
