### ISSUE TITLE
Add-EflowVmSharedFolder    command is successful if we provide targetFolderOnGuest path as "/mnt/vishwa/vishwa-read/

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#199]
*To Reproduce
Steps To Reproduce problem: (If required i will share the screen and walkthrough the steps).

Step 1. Install EFLOW - Latest version on Windows 11 - 22624 and above.
Step 2. Follow the steps provided at https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-1.4

**created sharedFolder.json file like below** 

[
				{
					"sharedFolderRoot": "C:\\ProgramData\\Vishwa\\EflowShared",
					"sharedFolders": [
						{   
							"hostFolderPath": "Vishwa-Read-Access", 
							"readOnly": true, 
							**"targetFolderOnGuest": "/mnt/vishwa/vishwa-read-access"** 
						},
						{   
							"hostFolderPath": "Vishwa-Read-Write-Access", 
							"readOnly": false, 
							**"targetFolderOnGuest": "/mnt/vishwa/vishwa-read-write-access"**
						}
					]
				}
			]'

Step3: Now execute "Add-EflowVmSharedFolder" command like below.

Add-EflowVmSharedFolder -sharedFoldersJsonPath 'C:\Shared\EFLOW-Shared\sharedFolders.json'

**Issue:** Command executes successfully but NO FOLDERS WILL BE CREATED inside /mnt/  folder of target linux machine. (i.e. when we navigate to /mnt/ ... no folders are created) though command is successful.

**Expected:** 
a) command should create folders successfully 

OR

b) Command should fail and provided proper error message if /mnt/ is a "Read-Only" file system

if we use "Get-EflowVmSharedFolder" it prints saying that target folders are available at /mnt/vishwa..... but we do not see any such folder in real.

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Thanks for the detailed information. We will try to reproduce the error, and we will reach back. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

This issue was fixed with the latest [1.4.3.23013](https://github.com/Azure/iotedge-eflow/releases/tag/1.4.3.23013.

Thanks,
Francisco
