### ISSUE TITLE
E-Flow - SSH problem

### ISSUE THREAD

**Issue by mjeannin2** [Azure/iotedge-eflow#2]
Hello all,

I'm facing a problem with the SSH key management in Eflow VM
Sometime, the SSh-Eflow-Vm command asks me the password 
I also tried with ssh command with the rsa file in argument with same result.

The VM seems to be well started (without any error)
Does it exists a workflowa that manage the SSH key between the host and the VM ?

Regards
Maxime

**Comment by TerryWarwick** [comment]
@mjeannin2, 

Are you still experiencing an issue with connecting to the EFLOW VM using SSH?  If you are, please let us know exactly what issues you are experiencing.  If you are no longer having an issue with this, please Close the issue report.

Thank you

Terry Warwick

**Comment by TerryWarwick** [comment]
Closing do to no response in 4 weeks
