### ISSUE TITLE
EFlow VM and your network configuration

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#20]
Just in case others run into this... AFter following the directions on installing EFLOW things were working great.  Then "randomly" (or so I thought) I couldn't SSH into the EFLOW vm.   After some investigation the VM wasn't getting an IP Address anymore.  It turns out that I had setup the EFLOW vm with my laptop plugged in to a network.. then when I went wireless, the VM wasn't getting an ip address anmore.  I went to Hypervisor and changed teh External adaptor (from the Switch Manager) to use my wireless and was back up and running again.   

Not sure there is a better way to manage this but if anyone runs into this problem I thought I'd post this experience here in the hopes of saving someone from deciding they must reinstall EFLOW

**Comment by TerryWarwick** [comment]
@hooligan495,
 
Thank you for posting your findings and the workaround that you found.  Please be aware that while this workaround concept is very relevant, after 4/28 we will be publishing an update that will require reinstallation and change the way we manage the lifecycle of our VM. Once this change is deployed, the EFLOW VM will behave similarly to WSL2 and no longer be visible in Hyper-V Manager.  We will be able to use command line tools like HCSDiag and HNSDiag to inspect the image.  Your scenario is very valid and we will be looking into methods to avoid this situation.  You will find information about this update in the release note tags here on Github.  In addition, we will provide troubleshooting guidance in the Wiki as soon as possible.

Terry Warwick
Microsoft

**Comment by hooligan495** [comment]
Thanks Terry!  

I figured the new update might eliminating this workaround. 

Jay McGaffigan

**Comment by hooligan495** [comment]
Hi Terry and TEam, 
Quick question .. Where will you announce that the update occurred?   On the main page to this repo?  some other MS portal?  Thanks
Jay

**Comment by fcabrera23** [comment]
Hi @hooligan495,

All the documentation of our releases will be posted on our [Releases section](https://github.com/Azure/iotedge-eflow/releases).  Also, we are working on how to indicate users that they are running an older version of EFLOW, probably through WAC.  

Thanks

**Comment by fcabrera23** [comment]
Hi @hooligan495,

As part of the [EFLOW GA release](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2106.1), we changed the EFLOW VM host naming. The new naming is generated by the Windows host device name + "-EFLOW". You can check the name of the EFLOW VM following these steps:

1. Open an elevated PowerShell session
2. Start an SSH connection to the EFLOW VM using the command `Connect-EflowVm`
3. Run the command `cat /proc/sys/kernel/hostname` to check the hostname
