### ISSUE TITLE
How about supporting on other Linux Distributions - Say for example : Ubuntu 20.04 LTS or Red Hat Enterprise 

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#200]
**Question Summary**
Hi Team,

How about "File Sharing Support" on other Linux Distributions - Say for example : Ubuntu 20.04 LTS or Red Hat Enterprise 

**Detailed background**
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-1.4

**Add-EflowVmSharedFolder** -sharedFoldersJsonPath "C:\Shared\EFLOW-Shared\sharedFolders.json"

As of now File Sharing command is supported on "Mariner Linux "

But some of our customers are having custom modules running on "Ubuntu 20.04 LTS" so we don't how those behave on "Marnier OS".

So could you throw some light on File Sharing Feature support for a different Linux OS

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Thanks for your question. If you are using IoT Edge directly on a Linux OS, you can use [IoT Edge storage bindings](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-use-create-options?view=iotedge-1.4). In this case, there's no need for folder sharing between Host OS and Guest OS.

Thanks,
Francisco

**Comment by post2vishwa** [comment]
Hi @fcabrera23 ,

Thank you for reply. 

Let me re-phrase the question like.

As of now if we install Eflow it will install Mariner Linux OS virtual machine. So instead of Mariner OS do we have any to install other distribution of Linux like Ubuntu or Cent OS etc.

The reason i am asking is : some of our customer built their modules (amd64 and arm64 )on Ubuntu OS and there stuff dependent on windows as well. So if they want to take advantage of Eflow, now customer modules are going to run on "Mariner OS" based linux. So they may run or may not run or some other issues may encounter. 

So if there is any provision for Eflow to support other distributions then it will be helpful for the customer as they are confident that their existing modules which are built for Ubuntu OS distribution will run 'as is'  with the Power of EFLOW.


Thanks,
Vishwa
