### ISSUE TITLE
Installing Defender for IoT micro agent and Azure Device Update service

### ISSUE THREAD

**Issue by arminghasemazar** [Azure/iotedge-eflow#204]
**Question Summary**
How one can install Defender for IoT micro agent and device update packages in EFLOW OS? We have a large fleet of edge devices (mostly Ubuntu) but we are expanding our portfolio of services and adding EFLOW option as well. So it's important for us to be able to secure these devices using Defender for IoT service and also have full control of device updates using new Azure Device Update service. I know that EFLOW gets updates from Windows Update Service and new versions of EFLOW includes updated IoT edge runtime and relevant packages. But it would also be good to be able to install desired packages as well. For Ubuntu, it can be done via APT. However, it's not applicable to EFLOW. Would appreciate to get some insights about it.

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

Thanks for your question. The EFLOW VM has a read-only rootFS and **no** package manager.  No extra packages can be installed, and we expect users to only run IoT Edge modules inside the VM.  These decisions are part of our design principles to provide better security and update experience, and we do not plan to change them shortly. 

Defender for IoT is already part of the EFLOW VM. You can enable it using the [Set-EflwoVmFeature](https://learn.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-1.4#set-eflowvmfeature). Update packages are not needed as we provide all the package updates with our EFLOW monthly update.

Thanks,
Francisco
