### ISSUE TITLE
Getting Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true  enable disable status from Guest OS

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#207]
Hi Team,

We are using EFLOW on a nested virtualization environment. So as part of this first by using below command

**Set-VMProcessor -VMName <VishwaWin2019> -ExposeVirtualizationExtensions $true**  

enabled nested virtualization. This enables/allows me to install "Hyper-V" on Guest Operating System machine (windows server 2019).

What we are looking is :

Is there any way from Guest OS, to fetch the information of Nested Virtualization enable / disable status.

I have navigated to below path on Guest OS and able to find ["HostName".](url) Similarly, any way / anywhere can i get nested virtualization information.

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Virtual Machine\Guest\Parameters
![On Host machine](https://user-images.githubusercontent.com/50254283/204673458-538c3603-0fd6-4820-b39e-0bd28817738d.jpg)
![On Guest Machine](https://user-images.githubusercontent.com/50254283/204673487-8e02837d-c50a-4f8f-9c1f-c1ec7a5c06f0.jpg)

Thanks,
Vishwa

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Thanks for your question. I'm not familiar with a way to determine that.  Maybe you could do the following:

1. Check that you're actually running on a VM
    ```
    PS C:\Windows\system32> Get-CimInstance Win32_BaseBoard
    
     Manufacturer : Microsoft Corporation
    Model        :
    Name         : Base Board
    SerialNumber : 4814-1269-8840-1470-5731-0676-20
    SKU          :
    Product      : Virtual Machine
    ```

2. Enable Hyper-V
3. **hvhost** service fails to come up when nested virtualization is not enabled or when virtualization was not enabled in firmware. Check that his service is running. If stopped, you must enable nested virtualization. 

    ```
    PS C:\Windows\system32> Get-Service -Name "hvhost"
    
    Status   Name               DisplayName
    ------   ----               -----------
    Stopped  hvhost             HV Host Service
    ```

Hope that helps.
Thanks,
Francisco

**Comment by post2vishwa** [comment]
Hi @fcabrera23 , Thanks much for help.
