### ISSUE TITLE
Module development and the version of .net it uses

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#21]
**Question Summary**
In using EFLOW (which we know is IOT Edge 1.1) are we constrained to using .net core 3.1 for our modules for now?  Or can I spin my own docker file to point to the 5.0 sdks?   or if I do that am I asking for more trouble than it's worth? 

**Detailed background**
We are developing some modules and may need some of the SDK support in 5.0.  But before I commit to using them I'm wondering if I shouldn't go there.  As IOT Edge itself runs on .net core, does it matter how we configure our modules' dockerfiles? 
Thanks!

**Comment by veyalla** [comment]
@hooligan495 Does your module use C# Azure IoT SDK for D2C messages, twin update, direct methods etc?

**Comment by hooligan495** [comment]
right now we are using the Device SDK (Microsoft.Azure.Devices.Client nuget package)

**Comment by veyalla** [comment]
While we have not tested this explicitly, I have no reason to believe that it won't work. 

I was going to ask you to check in the IoT C# SDK repo to make sure they support .NET 5.0 but saw this blog post today: [Azure IoT Hub SDK for .NET now support .NET5 (Preview)](https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-hub-sdk-for-net-now-support-net5-preview/ba-p/2304609). :)

Please try it out and open an issue in the[ IoT C# SDK repo](https://github.com/Azure/azure-iot-sdk-csharp/issues) if you run into any problems.
