### ISSUE TITLE
Deploy-Eflow  command option for suppressing reboot

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge-eflow#213]
Hi Team,

Question : In course of executing "Deploy-Eflow" command after 'stage 1"  message is prompting to user for Reboot of machine.

Ask is :  

1. Is there anyway to suppress this reboot ? (as before this reboot a machine reboot is occurring due to Hyper-V enabling ) So this reboot count is coming as "second reboot".

2. Exactly what part/step/feature of "deploy-eflow" command is required a reboot of machine. If we know this, so that we will install as a pre-requisite or after installing Hyper-V.

   -- Multiple times of reboot of machine are hampering our customers and user experience is becoming cumbersome. 
   -- while automation is running this install reboots are causing other issues.

Help on above is greatly apricated.

Thanks,
Vishwa

**Comment by fcabrera23** [comment]
Hi @post2vishwa,

Right now, we do not have a way to surpass that reboot. The second reboot is because Microsoft Update is not turned on. 

You can turn it on before doing `Deploy-Eflow` and turn it off back again after deployment finishes. Check [EFLOW Update](https://learn.microsoft.com/en-us/azure/iot-edge/iot-edge-for-linux-on-windows-updates?view=iotedge-1.4) for more information. 

Thanks,
Francisco

**Comment by post2vishwa** [comment]
Hi @fcabrera23 ,

Above information is helpful. Thanks much.

Regards,
Vishwa

**Comment by post2vishwa** [comment]
Hi @fcabrera23 ,

Below are my further observations on this:

While 'executing "Deploy-Eflow" command , Reboot is occurring due to "**VirtualMachinePlatform**" enabling (if not enabled) on "**Server Operating Systems**" only. 

So if  I enable "VirtualMachinePlatform" manually before I execute "Deploy-Eflow" command , then there is no reboot due to "Deploy-Eflow" command. 

![image](https://user-images.githubusercontent.com/50254283/208025753-1cd9ce1d-e186-4205-9345-bb7c77fefc93.png)


On "Client Operating Systems" (Win 10 ) , there is no reboot occuring while executing "deploy-eflow" command. 
Surprisingly "Checking the status of 'VirutalMachinePlatform' is NOT printing in course of "Deploy-Eflow" command 'step 1' process.  

**Is "VirtualMachinePlatform' enabling is NOT required on "Client Operating Systems" ?**

Potentially 'second reboot' might not be due to 'Microsoft Update Turn on ' as I am observing when I enable "virtualmachineplatform' on server 'Microsoft update is turned on ' but there is not reboot.

Attaching 
[Complete Terminal Messages On Server.txt](https://github.com/Azure/iotedge-eflow/files/10242832/Complete.Terminal.Messages.On.Server.txt)
[Complete Terminal Messages On Win10.txt](https://github.com/Azure/iotedge-eflow/files/10242833/Complete.Terminal.Messages.On.Win10.txt)
complete terminal messages printed for Server and Client OS.

Thanks.
Vishwa
