### ISSUE TITLE
IoTEdge 1.4 LTS TLS certificate configuration

### ISSUE THREAD

**Issue by sitaalbeMarp** [Azure/iotedge-eflow#214]
Dear IoTEdge team,
I have followed the guide of this Link:
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-1.4&tabs=windows

And I have noticed that the **/var/aziot** folder is by default created with 750 permissions.
This cause the IoTEdge runtime to fail. Services are not rebooted and docker containers not activated.

I changed the permissions to 755 for the following folders:
/var/aziot
/var/aziot/certs
/var/aziot/secrets

Because I've performed these commands:
```
sudo mkdir /var/aziot/certs -p
sudo mkdir /var/aziot/secrets -p
```

and the parent folder /var/aziot was not present (-p option).

Certificates have file permissions like the one listed in the official documentation.

I've experienced this with all the 1.4.x versions of EFLOW on Windows Server 2019/2022.

Is it right to use 755 permissions on the mentioned folders?
If yes, my suggestion is to update the documentation in order to avoid the failure of the runtime.

Thank you for helping!
Alberto S.

**Comment by jlian** [comment]
What error do you see? Is it similar to this? https://github.com/MicrosoftDocs/azure-docs/issues/102589#issuecomment-1350223722

**Comment by sitaalbeMarp** [comment]
@micahl Thank you!

@jlian Yes it is similar. The problem is that the official guide is not mentioning that these folders:
```
/var/aziot
/var/aziot/certs
/var/aziot/secrets
```
needs 755 permissions. Certificates permissions are fine, but by default the permissions on the above directory are not enough (750 is making the runtime failing).

This is my current situation: 
![image](https://user-images.githubusercontent.com/93998860/207793584-1e483c56-2753-410c-9404-8cd028d0571e.png)

after creating this:
```
sudo mkdir /var/aziot/certs -p
sudo mkdir /var/aziot/secrets -p
```
I have changed the permissions to 755 on all these three directories:
```
/var/aziot
/var/aziot/certs
/var/aziot/secrets
```

I have noticed that in the other issue that you have mentioned, the ownership of the above directories is different. Maybe this is the problem?

Thank you!

**Comment by sitaalbeMarp** [comment]
@jlian 
I've tested this: https://github.com/MicrosoftDocs/azure-docs/issues/102589#issuecomment-1352232066
And now it is working.

I think that this:  https://github.com/MicrosoftDocs/azure-docs/issues/102589#issuecomment-1352232066
is the solution so we can close this issue.

Thanks a lot!

**Comment by fcabrera23** [comment]
Hi @sitaalbeMarp,

Glad you were able to fix your issue. Thanks to @jlian and @micahl 

Thanks,
Francisco

**Comment by jlian** [comment]
To summarize, your problem was fixed once you did the `chown`?

**Comment by sitaalbeMarp** [comment]
Dear @jlian,
yes. The problem was solved performing these instructions:
```
# Give aziotcs ownership to certificate folder
# Read/write/execute for aziotcs, read and execute access for others
sudo chown aziotcs:aziotcs /var/aziot/certs
sudo chmod 755 /var/aziot/certs

# Give aziotks ownership to private key
# Read/write/execute for aziotks, no permission for others
sudo chown aziotks:aziotks /var/aziot/secrets
sudo chmod 700 /var/aziot/secrets
```
I think these needs to be updated in the official documentation.

Thank you.

**Comment by jlian** [comment]
FYI the docs update for permissions are now done

https://learn.microsoft.com/azure/iot-edge/how-to-manage-device-certificates#permission-requirements

Thanks @PatAltimore

**Comment by sitaalbeMarp** [comment]
@jlian, @PatAltimore
Thank you!
