### ISSUE TITLE
Edge Module connecting to Host 

### ISSUE THREAD

**Issue by Salavertus** [Azure/iotedge-eflow#216]
**Question Summary**
Hello all, I am meant to build an Iot Edge Module in C# that has to connect to a local SQL for get the information to upload it to the Hub. and I am facing difficulties and a lack of similar projects and information about it.

I have figured out how to ping to W10 host from EFLOW retrieving the EFLOW hostname and deleting the last "-EFLOW" string since the hostname is almost the same. But sometimes we have the "Temporary failure in name resolution" error and also we have to connect from the Module and the function "System.Net.Dns.GetHostName();" returns another hostname, not the EFLOW one. I don't know if its dockers one or module hostname.

Summary: I need a reliable approach to figure out the W10 hostname and connect from an IoT Edge module to a SQL database in the Windows 10 hosting EFLOW.

**Detailed background**
We are running the SQL 2019 Engine and the Iot Edge 1.4 in W10

Thank you.

**Comment by fcabrera23** [comment]
Hi @Salavertus,

Thanks for sharing your detailed scenario. My recommendation is to inject a variable with the EFLOW hostname into the module and then just remove the "-EFLOW".   Check [[How to get the hostname of the docker host from inside a docker container on that host without env vars](https://stackoverflow.com/questions/29808920/how-to-get-the-hostname-of-the-docker-host-from-inside-a-docker-container-on-tha)](https://stackoverflow.com/questions/29808920/how-to-get-the-hostname-of-the-docker-host-from-inside-a-docker-container-on-tha) or [How to get the host IP in a module?](https://github.com/Azure/iotedge/issues/1543)

Thnk

**Comment by cuongdouble** [comment]
hi @Salavertus @fcabrera23 , i install eflowvm using default switch. **How to connect to the host from a container?** I have tried several methods, but I couldn't make it work
