### ISSUE TITLE
Deploy-Eflow ignores -vmDataSize parameter

### ISSUE THREAD

**Issue by stonelose** [Azure/iotedge-eflow#229]
I'm trying to deploy EFLOW 1.4 on a small industrial PC, following this guide: [https://learn.microsoft.com/en-us/azure/iot-edge/quickstart?view=iotedge-1.4]. OS: Windows 10 Enterprise LTSC 1809 build 17763.3887

I have 17.5 Gb of free disk space (EFLOW minimum requirement is 10), yet the provision fails with insufficient disk space when I specify a vmDataSize of 2 Gb. It seems like it tries to deploy with a setting of 29Gb, which is the default for the vmDiskSize parameter. This should not come into play when I specify vmDataSize as I understand it.

Am I doing something wrong, or is the vmDataSize parameter being ignored?

Command:
`Deploy-Eflow -cpuCount 1 -memoryInMB 1024 -vmDataSize 2`

Output:
[02/06/2023 18:31:24] Step 1: Preparing host for Azure IoT Edge for Linux on Windows
[02/06/2023 18:31:24] Checking host for required features
 - Checking the status of 'Microsoft-Hyper-V'
 - Checking the status of 'Microsoft-Hyper-V-Management-PowerShell'
 - Checking the status of 'Microsoft-Hyper-V-Hypervisor'
 - Checking the status of 'OpenSSH.Client*'
 - Verifying whether Hyper-V is enabled and functional
 - Hyper-V core services are active
[02/06/2023 18:37:14] Checking for virtual switch with name 'Default Switch'
 - The virtual switch 'Default Switch' of type 'Internal' is present
[02/06/2023 18:41:45] Step 2: Validating pre-requisites and deployment parameters...
 - Verifying host requirements for selected configuration (29 GB disk size, 1024 MB memory, 1 CPUs)
[02/06/2023 18:42:24] Verifying Host OS can support requested EFLOW configuration
[02/06/2023 18:43:44] Verifying required storage, RAM and number of cores are available
 - Drive 'C:' has 18 GB free
 - A minimum of 31 GB disk space is required on drive 'C:'
[02/06/2023 18:44:15] Exception caught!!!
 - Not enough disk space is available on drive 'C:'. (L5257)

**Comment by chrisdats** [comment]
Hello, thanks for reporting this issue. We have confirmed that in certain instances, the minimum disk space check is greater than it should be. We are working on a fix and will address this in a future release.

**Comment by fcabrera23** [comment]
Hi @stonelose,

This issue was fixed with our latest release - https://github.com/Azure/iotedge-eflow/releases/tag/1.4.6.04053

Thanks,
Francisco
