### ISSUE TITLE
Uable to add installation path to Autodeployment

### ISSUE THREAD

**Issue by realjonas** [Azure/iotedge-eflow#231]
**Describe the Problem**
error when trying to add installpath and vhdxpath,

ConvertFrom-Json : Unrecognized escape sequence. (157): {
    "schemaVersion":"1.0",
    "version":"1.0",
    "eflowProduct" : "Azure IoT Edge 1.4 LTS X64",
    "installOptions":{
        "installPath": "D:\VMs\eflow",
        "vhdxPath": "D:\VMs\eflow"
    },
 

$jsonContent = @'
{
    "schemaVersion":"1.0",
    "version":"1.0",
    "eflowProduct" : "Azure IoT Edge 1.4 LTS X64",
    "installOptions":{
        "installPath": "D:\VMs\eflow",
        "vhdxPath": "D:\VMs\eflow"
    },
    "enduser":{
        "acceptEula" : "Yes",
        "acceptOptionalTelemetry" : "Yes"
    },
    "network":{
        "adapterName": "Ethernet",
        "vswitchType" : "External",
        "vswitchName" : "EFLOW-Switch"
    },
    "vmConfig":{
        "cpuCount" : 2,
        "memoryInMB" : 4096,
        "vmDataSize" : 20
    },
    "eflowProvisioning":{
        "provisioningType" : "",
        "devConnString" : ""
    }
}
'@

Br
Jonas

**Comment by fcabrera23** [comment]
Hi @realjonas,

Thanks for reaching out.  In some cases, when using a Path as a string, you need to use "\\" instead of "\". Could you please try replacing your installPath and vhdxPath to use double \ ?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @realjonas,

Did you try my suggestion? Were you able to fix the issue?

Thanks
Francisco

**Comment by realjonas** [comment]
Hi
Sorry for late response
It worked when removing both path and let it use default.

Thanks

/Jonas

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Francisco Cabrera ***@***.***>
Skickat: Tuesday, March 7, 2023 12:45:42 AM
Till: Azure/iotedge-eflow ***@***.***>
Kopia: Jonas Börjesson ***@***.***>; Mention ***@***.***>
Ämne: Re: [Azure/iotedge-eflow] Uable to add installation path to Autodeployment (Issue #231)


Hi @realjonas<https://github.com/realjonas>,

Did you try my suggestion? Were you able to fix the issue?

Thanks
Francisco

**Comment by fcabrera23** [comment]
Thanks for the update - Closing this issue
