### ISSUE TITLE
Upgrade to EFLOW 1.4 fails - Password required ? 

### ISSUE THREAD

**Issue by mwilcox12014** [Azure/iotedge-eflow#239]
Windows Server 2019 
HyperV enabled (Passthrough)
	VM Options, enable VBS (Enable Virtualization based Security)
	Use External switch and turn on ‘Allow promiscuous mode’ 	
	EFLOW VM 1.1 in use 

Bug/Problem Description:

We are trying to update from Linux (Eflow version) 1.1 to 1.4  
However, the Linux VM is able to acquire the IP address and it begins an ssh connection but it asks me for a password which I do not have.  What is the password ?  Can it be reset to a default password ? 

Separately, when I try to use the newest version (1.4) the setup fails to acquire the IP and is unable to ssh into the machine.

**Comment by fcabrera23** [comment]
Hi @mwilcox12014,

Thanks for sharing your information. I'll go ahead and close this issue. 

Thanks,
Francisco
