### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by sportbilly21** [Azure/iotedge-eflow#24]
Hi
I had a look in the internet and I could not find a clear answer in the following question:
Does Azure IoT Edge for Linux on Windows (eflow) supports Nvidia GPU for deploying  CNN models for inference?
And if yes can you please guide if there is somewhere relevant documentation?
Many thanks

**Comment by chrisdats** [comment]
Thanks for your interested in EFLOW. While GPU passthrough is currently not supported, it is an area of active investigation. Would you mind sharing for which GPUs you are seeking support?

**Comment by fcabrera23** [comment]
Hi @sportbilly21 ,

Today we release our GA version that supports NVIDIA T4 and GeForce/Quadro cards in preview. Please check the documentation at [https://aka.ms/AzEFLOW-GPU](https://aka.ms/AzEFLOW-GPU).
