### ISSUE TITLE
High Memory Usage in Azure IoT Edge LTS with Custom Modules

### ISSUE THREAD

**Issue by rabergerik** [Azure/iotedge-eflow#240]
**Describe the bug**
I am running Azure IoT Edge LTS 1.4.4.03033 with two custom modules. The custom modules collect data over TCP from simulators and send messages upstream to an IoT Hub in Azure. After running for some minutes or hours without issues, the message transmission suddenly stops.

Inspecting the system logs (journalctl --system) shows a container runtime error and a watchdog checking the runtime status but not receiving a response:

Mar 30 15:04:12 ELX210922-EFLOW aziot-edged[1243]: 2023-03-30T15:04:12Z [WARN] - container runtime error
Mar 30 15:04:12 ELX210922-EFLOW aziot-edged[1243]: Caused by:
Mar 30 15:04:12 ELX210922-EFLOW aziot-edged[1243]:     deadline has elapsed
Mar 30 15:05:06 ELX210922-EFLOW aziot-edged[1243]: 2023-03-30T15:04:13Z [INFO] - Auth for edgeHub failed: runtime operation error: top module "edgeHub"
Mar 30 15:05:06 ELX210922-EFLOW aziot-edged[1243]: 2023-03-30T15:04:13Z [INFO] - --> 403 {"content-type": "application/json"}
Mar 30 15:05:06 ELX210922-EFLOW aziot-edged[1243]: 2023-03-30T15:04:22Z [INFO] - --> 500 {"content-type": "application/json"}
Mar 30 15:05:06 ELX210922-EFLOW aziot-edged[1243]: 2023-03-30T15:04:25Z [INFO] - <-- POST /modules/%24edgeHub/genid/638152555084779677/encrypt?api-version=2020-07-07 {"accept": "application/json", "host": "workload.sock:80", "connection": "close", "content-type": "application/json", "content-length": "574"}

Following this, there is no log output until the system seems to run out of memory about 1.5 hours later:

Mar 30 16:35:48 ELX210922-EFLOW systemd[1]: systemd-journald.service: State 'stop-watchdog' timed out. Killing.
Mar 30 16:35:48 ELX210922-EFLOW systemd[1]: systemd-journald.service: Killing process 577 (systemd-journal) with signal SIGKILL.
Mar 30 16:35:48 ELX210922-EFLOW kernel: systemd-resolve invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0

During this time, the vmmem process on Windows reaches its maximum CPU usage, and the VM becomes extremely sluggish or unresponsive. The only way to restore the system is by killing the vmwp process. This issue has occurred multiple times under the same conditions.

**To Reproduce**
1. Set up a Windows machine with Azure IoT Edge installed, and deploy an EFLOW VM. Provision the VM to connect to the IoT Hub.
2. Deploy two custom modules that collect data over TCP from simulators and send messages upstream to an IoT Hub in Azure.
3. Monitor the message transmission and wait for it to stop suddenly.
4. Observe the high CPU usage by the vmmem process on Windows and the sluggishness or unresponsiveness of the EFLOW VM.
5. Kill the vmwp process to restore the system.
6. After restoring the system, inspect the system logs using journalctl --system within the EFLOW VM and observe the container runtime error and deadline elapsed message. Continue reviewing the logs to find the out-of-memory event and the 'stop-watchdog' timed out message.

**Expected behavior**
The custom modules should consistently collect data over TCP from the simulators and send messages upstream to the IoT Hub without interruptions. The EFLOW VM should remain stable, with no high CPU usage by the vmmem process on Windows or sluggishness. The system should not encounter out-of-memory events, and there should be no need to kill the vmwp process to restore the system.

**Windows Host OS (please complete the following information):**
 - Edition: Microsoft Windows 10 Enterprise LTSC
 - Version: Version	10.0.17763 Build 17763
 - Virtual Machine: None
 
**Additional context**
Attached logs from the system, the relevant parts are from after 2023-03-30T14:30:00Z UTC, where I have removed the "HEALTHCHECK" statement from the dockerfile for my custom modules, which is what I originally thought might cause the issue since it after some time of execution was getting an error: 
Mar 29 15:28:45 ELX210922-EFLOW dockerd[17107]: time="2023-03-29T15:28:45.192132862Z" level=error msg="stream copy error: reading from a closed fifo"

[logs.zip](https://github.com/Azure/iotedge-eflow/files/11120878/logs.zip)

**Comment by fcabrera23** [comment]
Hi @rabergerik,

Thanks for reaching out.  I suspect that the issue could be related to two different things

1) Memory leak - Could you please check that there's no memory leak in your modules? You can connect to the EFLOW VM and then use the `sudo docker stats` command to check memory, IO, and CPU usage. 

2) Logs - Could you please check your logs usage?

Finally, if possible, try to increase both the memory and storage of the EFLOW VM. Maybe you're in a corner case, and by increasing both parameters you get your VM running correctly. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @rabergerik,

It seems to me that you're using a 1GB EFLOW VM. In the past, we've seen that when using "almost over the limit" memory assignment, the memory paging swapping system will start doing a lot of swaps and hence there's a memory CPU spike. I'd recommend assigning ~300/400MB more to the VM.

Thanks
Francsico

**Comment by rabergerik** [comment]
@fcabrera23 Thank you, yes you’re right. I doubled the memory on Friday, on your suggestion, and it has been running smoothly since then. Thanks again for your time.
