### ISSUE TITLE
Hoe to automate pn.json updation with addition/modification of new tags

### ISSUE THREAD

**Issue by Priyanka-L-Dalawai** [Azure/iotedge-eflow#244]
**Question Summary**
How to add. modify tags in opcnodes array in pn.json? As count of tags increase it is really hard to update it manually
**Detailed background**
Additional details required to frame the context of your question.
Which is best way to update it

**Comment by fcabrera23** [comment]
Hi @Priyanka-L-Dalawai,

Thanks for reaching out. Could you please provide a detailed background of your issue? What are OPCNodes? Are you using a sample app? Is this related to EFLOW or a module?

Thanks,
Francisco

**Comment by Priyanka-L-Dalawai** [comment]
In OPC Publisher we have to configure tags in publishnodes.json, Whenever we have to add.modify new tags we do it manually, instead how we can automate this
https://learn.microsoft.com/en-us/azure/industrial-iot/tutorial-publisher-configure-opc-publisher#configuration-via-configuration-file

**Comment by fcabrera23** [comment]
Hi @Priyanka-L-Dalawai,

This is not an EFLOW issue - I'll transfer it to the appropriate repo.

Thanks,
Francisco
