### ISSUE TITLE
Installing EFLOW 1.4.5 on Windows 2019 Core results in 'wssdagent is unreachable'

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge-eflow#245]
**Describe the bug**
I try to install EFLOW 1.4.5 on a Windows 2019 Core Azure Virtual machine.
I have created an internal VM switch and a network:

![image](https://user-images.githubusercontent.com/3605786/234535265-24a15bfc-a5ce-402b-8df2-346e2fd36c3d.png)

![image](https://user-images.githubusercontent.com/3605786/234535389-4c7dedd2-cdc0-4853-9572-6cfd9be504ad.png)

The [EFLOW 1.4.5 msi](https://download.microsoft.com/download/6/4/9/64957901-60c0-4e83-8545-74e2784e3680/AzureIoTEdge_LTS_1.4.5.30033_X64.msi) has been installed.

Afterwards, I execute this command:

```
Provision-EflowVm -provisioningType ManualConnectionString -devConnString "<my-connectionstring>"
```

And this results in this error:

![image](https://user-images.githubusercontent.com/3605786/234536073-1f1fed00-cacf-43d2-9272-7e8a22394c45.png)

This is run from Powershell 5.1:

![image](https://user-images.githubusercontent.com/3605786/234536529-81424dca-1fef-4778-969f-48e4a99f9cbd.png)

(I use Powershell instead of Powershell Core since I remember running into issues when installing previous versions of EFLOW using Powershell Core).

**Additional context**

I think it is good to know that:

- a previous installation of EFLOW was installed on the same VM earlier (and running successfully).  However, I've removed this older version by executing `msiexec /x "{guid-representing-eflow}" /qn`

- an (older) version of IoT Edge for Windows is running on the same VM.  We want to run both EFLOW and this IoT Edge for windows on the same machine concurrently to test out a migration path.

**Windows Host OS (please complete the following information):**
 - Edition: Windows Core
 - Version: 2019
 - Virtual Machine: Azure VM

**Comment by fgheysels** [comment]
In the meantime, I've installed powershell core and tried to install it via pwsh, but I run into the same issue.

**Comment by fcabrera23** [comment]
Hi @fgheysels,

Thanks for reaching out. You need to `Deploy-Eflow` before provisioning. Please follow installation instructions for deployment and then provisioning.

Thanks,
Francisco

**Comment by fgheysels** [comment]
OMG, I'm terribly sorry.  Looks like i skipped a part of my own documentation. //

Anyway, before executing Deploy-Eflow, I need to create a VM Switch (internal).  After that, I set up port forwarding, but it goes wrong there. 
The command fails with the message `Add-NetNatStaticMapping : The object already exists.`:

![image](https://user-images.githubusercontent.com/3605786/234614500-bb9951f1-4263-4e11-ba49-b0a354f3a178.png)

**Comment by fcabrera23** [comment]
Hi @fgheysels,

Please make sure to erase any NetNat you had from previous attempts. Also, I'd suggest you follow https://learn.microsoft.com/en-us/azure/iot-edge/how-to-create-virtual-switch?view=iotedge-1.4.

Thanks,
Francisco

**Comment by fgheysels** [comment]
I retried this: removed the VM-Switch, removed the network, uninstalled EFLOW and started again, but I ran into the same issue.

**Comment by fcabrera23** [comment]
HI @fgheysels,

Are you still facing the same issue? Were you able to fix it?

Thanks,
Francisco
