### ISSUE TITLE
Unsupported: Required feature 'Microsoft-Hyper-V-Hypervisor' is not available in this Windows edition. (Windows Server 2019 Datacenter as Azure VM)

### ISSUE THREAD

**Issue by geebinge** [Azure/iotedge-eflow#25]
**Describe the bug**
Hi, we try to setup EFLOW with Windows Server 2019 Datacenter on a Azure VM (Standard D8ds_v4 (8 vcpus, 32 GiB memory))

Based on https://docs.microsoft.com/en-us/azure/virtual-machines/acu this VM should have Hyper-threaded and capable of running nested virtualization. We also make a try with Standard_D4s_v4, with the same result. 

on the step 7 (Windows Admin Center) in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=windowsadmincenter#create-a-new-deployment we get a 

"Unsupported: Required feature 'Microsoft-Hyper-V-Hypervisor' is not available in this Windows edition. (Windows Server 2019 Datacenter as Azure VM)"

**To Reproduce**
we follow https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows 
all steps in detail. Including to add Hyper-V 
![image](https://user-images.githubusercontent.com/32458010/117800349-58fdf480-b253-11eb-8c47-5e2c3c14cf25.png)

We check the Hyper-V Network Adapter. At that point the documentation is not clear. 
![image](https://user-images.githubusercontent.com/32458010/117800458-716e0f00-b253-11eb-96ea-687234dc648d.png)

We did not any changes on Virtual Machine Migration and Default Stores page. 

The server runs including Hyper-V 
![image](https://user-images.githubusercontent.com/32458010/117800841-e3465880-b253-11eb-8e63-de2516c63008.png)

Result of` (Get-WmiObject Win32_OperatingSystem).OperatingSystemSKU = 8 `

Result of `Get-WindowsOptionalFeature -Online -FeatureName \*Hyper-V\*  `

> FeatureName      : Microsoft-Hyper-V
> DisplayName      : Hyper-V
> Description      : Hyper-V
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
>                    ServerComponent\Description : Hyper-V provides the services that you can use to create and manage
>                    virtual machines and their resources. Each virtual machine is a virtualized computer system that
>                    operates in an isolated execution environment. This allows you to run multiple operating systems
>                    simultaneously.
>                    ServerComponent\DisplayName : Hyper-V
>                    ServerComponent\EventQuery : Virtualization.Events.xml
>                    ServerComponent\Id : 20
>                    ServerComponent\Type : Role
>                    ServerComponent\UniqueName : Hyper-V
>                    ServerComponent\Version\Major : 1
>                    ServerComponent\Version\Minor : 0
>                    ServerComponent\BestPractices\Model\Id : Microsoft/Windows/Hyper-V
>                    ServerComponent\Deploys\Update\Name : Microsoft-Hyper-V-Offline
>                    ServerComponent\Deploys\Update\Name : Microsoft-Hyper-V-Online
>                    ServerComponent\Configuration\RootClassMofDefinition :            class ServerComponent_HyperV
>                         {               String VirtualSwitchNetworkAdapters[];               String
>                    DefaultVirtualMachinePath;               String DefaultVirtualHardDiskPath;               BOOLEAN
>                    EnableVirtualMachineMigration;               String VirtualMachineMigrationAuthenticationType;
>                         };
>                    ServerComponent\SystemServices\SystemService\DefaultMonitoring : true
>                    ServerComponent\SystemServices\SystemService\Name : vmms
> 
> 
> FeatureName      : Microsoft-Hyper-V-Offline
> DisplayName      : Hyper-V Offline
> Description      : Hyper-V Offline
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
> 
> 
> FeatureName      : Microsoft-Hyper-V-Online
> DisplayName      : Hyper-V Online
> Description      : Hyper-V Online
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
> 
> 
> FeatureName      : RSAT-Hyper-V-Tools-Feature
> DisplayName      :
> Description      :
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
>                    mum2:customInformation\ServerComponent\Description : Hyper-V Management Tools includes GUI and
>                    command-line tools for managing Hyper-V.
>                    mum2:customInformation\ServerComponent\DisplayName : Hyper-V Management Tools
>                    mum2:customInformation\ServerComponent\Id : 464
>                    mum2:customInformation\ServerComponent\InstallWithParentByDefault : true
>                    mum2:customInformation\ServerComponent\Parent : RSAT-Role-Tools
>                    mum2:customInformation\ServerComponent\Type : Feature
>                    mum2:customInformation\ServerComponent\UniqueName : RSAT-Hyper-V-Tools
> 
> 
> FeatureName      : Microsoft-Hyper-V-Management-Clients
> DisplayName      : Hyper-V Management Console
> Description      : Hyper-V Management Console
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
>                    ServerComponent\Description : Hyper-V GUI Management Tools includes the Hyper-V Manager snap-in and
>                    Virtual Machine Connection tool.
>                    ServerComponent\DisplayName : Hyper-V GUI Management Tools
>                    ServerComponent\Id : 301
>                    ServerComponent\InstallWithParentByDefault : true
>                    ServerComponent\Parent : RSAT-Hyper-V-Tools
>                    ServerComponent\Type : Feature
>                    ServerComponent\UniqueName : Hyper-V-Tools
>                    ServerComponent\Version\Major : 1
>                    ServerComponent\Version\Minor : 0
>                    ServerComponent\Deploys\Update\Name : Microsoft-Hyper-V-Management-Clients
>                    ServerComponent\Relationships\OptionalCompanionFor\Prerequisite : Server-Gui-Mgmt
>                    ServerComponent\Relationships\OptionalCompanionFor\Type : RSAT
>                    ServerComponent\Relationships\OptionalCompanionFor\UniqueName : Hyper-V
> 
> 
> FeatureName      : Microsoft-Hyper-V-Management-PowerShell
> DisplayName      : Hyper-V PowerShell cmdlets
> Description      : Hyper-V PowerShell cmdlets
> RestartRequired  : Possible
> State            : Enabled
> CustomProperties :
>                    ServerComponent\Description : Hyper-V Module for Windows PowerShell includes Windows PowerShell
>                    cmdlets for managing Hyper-V.
>                    ServerComponent\DisplayName : Hyper-V Module for Windows PowerShell
>                    ServerComponent\Id : 457
>                    ServerComponent\InstallWithParentByDefault : true
>                    ServerComponent\Parent : RSAT-Hyper-V-Tools
>                    ServerComponent\Type : Feature
>                    ServerComponent\UniqueName : Hyper-V-PowerShell
>                    ServerComponent\Version\Major : 1
>                    ServerComponent\Version\Minor : 0
>                    ServerComponent\Deploys\Update\Name : Microsoft-Hyper-V-Management-PowerShell
>                    ServerComponent\Relationships\OptionalCompanionFor\Type : RSAT
>                    ServerComponent\Relationships\OptionalCompanionFor\UniqueName : Hyper-V
> 

Windows Admin Center / Version 2103 / Build 1.3.2103.01006

**Windows Host OS (please complete the following information):**
![image](https://user-images.githubusercontent.com/32458010/117802046-45ec2400-b255-11eb-8682-b8fbf7de91e5.png)
 
![image](https://user-images.githubusercontent.com/32458010/117802139-61efc580-b255-11eb-8884-19076d1844f1.png)

![image](https://user-images.githubusercontent.com/32458010/117802177-6e741e00-b255-11eb-97c1-aad3bac3e2cf.png)
![image](https://user-images.githubusercontent.com/32458010/117802189-72a03b80-b255-11eb-8482-6e64e1159f78.png)

**Comment by geebinge** [comment]
`Get-WindowsOptionalFeature -Online -FeatureName *Hyper-V*` you can find in the issue report there is nothing disabled.

**Comment by iconics-rich** [comment]
I'm seeing the same behavior on my Windows Server 2019 Standard (Version 1809; OS Build 17763.1817) system. `Get-WindowsOptionalFeature -Online -FeatureName *Hyper-V*` shows that all Hyper-V related features are Enabled, but am returned a "Unsupported: Required feature 'Microsoft-Hyper-V-Hypervisor' is not available in this Windows edition." in the Windows Admin Center.

However, I noticed that "Microsoft-Hyper-V-Hypervisor" feature is not listed (nor is it OP's post), despite the fact that Hyper-V is installed and running on my system.
![image](https://user-images.githubusercontent.com/66848248/120714723-93913080-c491-11eb-82fa-9a2aa466a82e.png)
![image](https://user-images.githubusercontent.com/66848248/120714779-a99ef100-c491-11eb-9dd0-516dcca8b43a.png)


 `Enable-WindowsOptionalFeature -Online -FeatureName "Microsoft-Hyper-V-Hypervisor" -All` returns: 
Enable-WindowsOptionalFeature : Feature name Microsoft-Hyper-V-Hypervisor is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName "Microsoft-Hyper-V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

Maybe detection of Hyper-V needs to be handled differently on Server OS vs. Windows 10?

I did run "Start-Process -Wait msiexec -ArgumentList "/i","AzureIoTEdge.msi","/lv","log.log","/qn" as suggested above (log attached), but now Windows Admin Center reports:
Unsupported: Device not clean, Azure IoT Edge for Linux on Windows components detected (Azure IoT Edge PS module)

[log.log](https://github.com/Azure/iotedge-eflow/files/6594334/log.log)

**Comment by fcabrera23** [comment]
Hi @iconics-rich,

Thanks for your detailed information.  Before trying to install EFLOW, please make sure you don't have an active "broken" installation.  If that's the case you need to begin by removing EFLOW from the target device by following this step:

1. Open Settings on Windows 10
2. Select Add or Remove Programs
3. Select Azure IoT Edge app
4. Select Uninstall

Once the Azure IoT Edge app is correctly removed from the target device, you can start the deployment process again.

**Comment by iconics-rich** [comment]
Thanks. After doing so, I'm back to the original error of:
Unsupported: Required feature 'Microsoft-Hyper-V-Hypervisor' is not available in this Windows edition.

It still seems like Hyper-V is not properly detected on Server 2019.

**Comment by fcabrera23** [comment]
@iconics-rich  - Just to clarify, are you using Windows Admin Center (WAC) for the deployment? We are aware of open bug when deploying using WAC on  Windows Server. Could you please try using [PowerShell](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=powershell)?

**Comment by iconics-rich** [comment]
@fcabrera23 
> are you using Windows Admin Center (WAC) for the deployment?

That's correct, I was using WAC for the deployment.

> We are aware of an open bug when deploying using WAC on Windows Server

OK, it sounds like that's what I'm running into then. Will this be fixed in an upcoming release?

> Could you please try using PowerShell?

This worked for me, my EFLOW VM is now running and provisioned successfully. Thanks!
