### ISSUE TITLE
Unable to Navigate into inside container on EFLOW machine

### ISSUE THREAD

**Issue by Vishwanath-Reddy-M** [Azure/iotedge-eflow#251]
Issue : Unable to Navigate into inside container on EFLOW machine

Reproduction Steps:

Step 1: Install latest version of EFLOW on Windows 10 or Windows 11.
Step 2: Deploy any module from IoTHub portal on to the EFLOW machine.
Step 3: try to navigate inside container  by using below commands.
          a) docker ps   ==> will show all modules running.
          b) docker exec -it <module name> <entry point> (for example : docker exec -it edge_module_sdk_module bash

Expected: we must be able to log into the module successfully.
Actual: "failed to create runc console socket: listen unix /tmp/pty<number>/pty.sock: bind: operation not permitted: unknown  

error is appearing. 
![On Ubuntu 22 Docker Bind Works](https://user-images.githubusercontent.com/50254283/236027730-da7ac28a-d528-4c20-ad58-22835fae919d.jpg)

On normal Ubuntu Linux machine or any other Linux machine with same docker version above steps are successful.
![docker bind issue](https://user-images.githubusercontent.com/50254283/236027690-c3677b18-2421-4a85-b267-22138eaa14db.jpg)

Attaching screenshots. 

Please let me know if anything required on reproduction standpoint. Thanks.

**Comment by nlcamp** [comment]
Transferring back to iotedge-eflow after chatting with @fcabrera23.

**Comment by jagadishmurugan** [comment]
map to a folder /tmp (/tmp/sharedfolder) instead of to /tmp

**Comment by Vishwanath-Reddy-M** [comment]
Thanks @jagadishmurugan . We will check this option internall and update you. 

Regards,
Vishwa

**Comment by Vishwanath-Reddy-M** [comment]
Hi @jagadishmurugan  (@fcabrera23  - FYI) as of now we are going ahead with /tmp/<sub-folder> path in file share.

But potentially this (File Sharing command) should either work smoothly no matter whatever target folder specified (we mean command should inform )  OR documentation should tell to end user,  ONLY target Linux machine sub-folders under following root lever folders are allowed in current version) .

![image](https://github.com/Azure/iotedge-eflow/assets/50254283/130bb0d9-a9f8-4d46-baca-b0100f425425)


From other thread:

**[2:33 PM] Jagadish Murugan**

**we will update documentation to clarify -** 

 "When an existing folder is used for FolderSharing (mounting to an existing folder), Linux redirects IO to/from that folder to the mounted device at that location - so the previous contents are effectively hidden. Once foldersharing is reverted, the old folder contents should appear again"
for the above reason, do not mount to any of the system created folders

Thanks,
Vishwa
