### ISSUE TITLE
Get-EflowLogs does not work in powershell core

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge-eflow#253]
**Describe the Problem**
When executing the `get-eflowlogs` command from a powershell core prompt, you'll run into the error that says:

```
[05/30/2023 09:16:01] Exception caught!!!

 - The term 'get-eventlog' is not recognized as a name of a cmdlet, function, script file, or executable program.      
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. at line 6529 
```

The `get-eventlog` cmdlet is not available in Powershell Core.  In Powershell core, you should use  `get-winevent` instead.

**To Reproduce**
1. open a pwsh prompt on a machine that has EFLOW installed
2. execute the `get-eflowlogs` cmdlet

**Expected behavior**
`get-eflowlogs`should work on both Powershell and Powershell Core.

**Comment by fcabrera23** [comment]
Hi @fgheysels,

Our PS support is limited to PS5.1 and PS7. Could you please share why you need PS Core?

Thanks,
Francisco

**Comment by fgheysels** [comment]
Isn't powershell core the way forward ?

**Comment by fcabrera23** [comment]
Hi @fgheysels,

PowerShell core has it's advantages and disadvantages that are out of EFLOW's scope. Unfortunately, we don't have a plan to support it in the short term.

Thanks,
Francisco
