### ISSUE TITLE
Deploy-Eflow failure/could not track signature to the microsoft root certification at line 5945

### ISSUE THREAD

**Issue by dilipkumar04** [Azure/iotedge-eflow#258]
Error Description:
Facing this error "could not track signature to the microsoft root certification at line 5945" after running Deploy-Eflow on a Windows PowerShell. I have taken a look at the closed issue #158. With reference to that issue. 

1). I had make sure that my windows was updated
2). In Certification manager under Trusted Publishers/Certificates/Microsoft Code Signing PCA 2011

Certification Information 
This certificate is intended for the following purpose(s):
    - Ensures software came from software publisher
    - Protects software from alteration after publication
    - Microsoft Publisher
Issued to : Microsoft Corporation
Issued by : Microsoft Code Signing PCA 2011
Valid from : 17-03-2023 to 15-03-2024

These above mentioned details are present in my certificate 

I would like you to inform that, I am facing error "could not track signature to the microsoft root certification at line 5945" but in issue #158 the person faced the same error but in line 5480. 

My system information :
Windows edition : Windows 10 Pro 
System type: 64-bit Operating System, x64-based processor 

Please help me to resolve this issue ASAP. Thank you.

**Comment by fcabrera23** [comment]
Hi @dilipkumar04,

Thanks for reaching out.  Do you have the Microsoft Root CA certificate?  Under Computer Certs -> Trusted Root Certificate Authority -> Certificates -> Microsoft Root Certificate Authority 2011?

Thanks,
Francisco

**Comment by dilipkumar04** [comment]
Thanks for your support issue now resolved
