### ISSUE TITLE
Container create options in edge module

### ISSUE THREAD

**Issue by Priyanka-L-Dalawai** [Azure/iotedge-eflow#260]
**Question Summary**
How to map ports 443 in host port to tcp 443 as it is not allowing

**Detailed background**
Additional details required to frame the context of your question.

**Comment by fcabrera23** [comment]
Hi @Priyanka-L-Dalawai,

Please check [How to configure container create options for IoT Edge modules](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-use-create-options?view=iotedge-1.4 for port mapping.

Thanks,
Francisco
