### ISSUE TITLE
Eflow deploy failed while verifying host binaries

### ISSUE THREAD

**Issue by mihir-shah-bh** [Azure/iotedge-eflow#264]
### Need help to complete the offline setup of EFLOW.

We have an on-premise firewall-guarded Windows Server 2019 VM (running on top of VM Ware ESXi). We followed the necessary documentation to enable nested virtualization and 'Default Switch' configuration.

Now our EFLOW deployment is failing in binary verification. Please note that this is an offline VM without any connectivity to the internet.

The image below captures the exact error we are facing.

![876ba965-499b-4514-b3aa-3c91e54448c4](https://github.com/Azure/iotedge-eflow/assets/58750257/3f899d2e-51b2-41ea-88e3-3f82a143b1b5)

**Kindly guide steps we need to take to resolve this issue and to ensure the offline setup is completed successfully.**

**Comment by fcabrera23** [comment]
Hi @mihir-shah-bh,

Thanks for reaching out. Probably you don't have the required certificates, and hence the installation will fail. Please, review #79 or [AKS-EE Windows offline certs](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-offline-install). 

Thanks,
Francisco

**Comment by mihir-shah-bh** [comment]
@fcabrera23 thanks for the prompt response. 

The steps, to install certificates offline, mentioned in [AKS-EE Windows offline certs](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-offline-install) solved our problem.

Appreciate your help.

Cheers! 
Mihir
