### ISSUE TITLE
IoT defender micro agent with EFLOW

### ISSUE THREAD

**Issue by beckerben** [Azure/iotedge-eflow#266]
**Question Summary**
Does the IoT defender micro agent make sense or even work in this scenario?

**Detailed background**
We are exploring using the EFLOW vm to enable some of our windows hosts to act as azure iot edge connected devices which our modules can work with.  I see that the IoT defender micro agent service is installed but it does not start with EFLOW vm.  

After thinking this through more, I am not entirely sure it even makes sense in the context of the vm as really we would be interested in monitoring the windows host ultimately rather than the vm so I am just confirming my assumption that the IoT defender micro agent service is not applicable for the EFLOW usage scenario and instead the standard defender on the host OS is to be used? Am I mis-understanding?

**Comment by fcabrera23** [comment]
Hi @beckerben,

[Microsoft Defender for IoT - Microagent](https://learn.microsoft.com/en-us/azure/defender-for-iot/device-builders/overview-security-agents) has multiple features that EFLOW users could leverage; I'd encourage you to go over the documentation to understand the feature set offered by this agent.  Also, just to let you know, you must enable this extension as part of EFLOW deployment. 

When it comes to monitoring the Windows host OS, you can check [Microsoft Defender for IoT](https://www.microsoft.com/en-us/security/business/endpoint-security/microsoft-defender-iot). This would be a separate solution running on the Windows host OS. 

Thanks,
Francisco
