### ISSUE TITLE
EFLOW External Switch Networking Issue

### ISSUE THREAD

**Issue by vermyas** [Azure/iotedge-eflow#269]
We are deploying EFLOW on Windows VM which is hosted on VMWare Exsi.We have followed the Microsoft documentation. 

[link](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-symmetric?view=iotedge-1.4&tabs=azure-portal) for the same.

**For Deployment we have created an external switch** 

![eflow deploy](https://github.com/Azure/iotedge-eflow/assets/97602435/22ccbfe2-3353-4301-a1cc-db5fac9a8db8)

**The configuration and creation of external switch are** :

![eflowswitch](https://github.com/Azure/iotedge-eflow/assets/97602435/a7d89705-de74-4d77-852b-5ef77835384e)

![switchconf](https://github.com/Azure/iotedge-eflow/assets/97602435/2c4e8b97-9def-4be4-9385-43ea7beadf37)

Right now, we are able to deploy eflow Successfully and able to ping Ip address from Linux VM to Windows host VM but not able to ping the gateway address from eflow linux vm to windows host vm .

![linustowin](https://github.com/Azure/iotedge-eflow/assets/97602435/f0d273a0-2848-4bc9-8db7-0be8d389c200)

moreover, we are able to ping dns from windows host vm but not from Linux vm 

![dnsping](https://github.com/Azure/iotedge-eflow/assets/97602435/57fdb46c-a8e5-4d8f-aa9f-53b9e09176c3)

So, we need help in understanding what can be the root cause of why we are not able to connect to gateway or any other Ip from Linux vm to outside world.

**Comment by fcabrera23** [comment]
Hi @vermyas,

Thanks for reaching out.  A couple of things:

1. The EFLOW VM will drop all traffic by default, unless a specific port/rule is added to the firewall. To do so, you can use the `Invoke-EflowVmCommand "iptables -A INPUT -p icmp -j ACCEPT" and try pinging.
2. If you use ESXi with an External switch, ensure to [Configuring promiscuous mode on a virtual switch or portgroup](https://kb.vmware.com/s/article/1004099).

Thanks,
Franicsco

**Comment by KamalAman** [comment]
@fcabrera23 We are running into this same issue. When deploying in a DMZ with an external switch, we can ping the host machine, but cannot ping the gateway. Enabling Promiscuous mode in ESXi might be the solution there, but we currently cannot make a change to that setting on ESXi at the moment. 

Is there a solution to use an Internal Switch but still maintain internet connectivity through the host machine?  
Or is there a way to configure the static ip address on ESXi so that the External switch will accept the traffic?

**Comment by KamalAman** [comment]
We were able to enable Promiscuous mode on the portgroup, and now network communication is working. 

However my question first question still stands, is there a way to achieve the same with with network access with an Internal Switch?

**Comment by RalfVDL** [comment]
We also run into this issue, just as #265. We see the requirement to enable promiscuous mode on the port group in ESX.

Can anyone elaborate on the details of why this is needed?

**Comment by jagadishmurugan** [comment]
Thats the recommendation from VMWare. Please contact VMWare support for details.
