### ISSUE TITLE
Does the updating process remove customizations?

### ISSUE THREAD

**Issue by beckerben** [Azure/iotedge-eflow#271]
**Question Summary**
I see the EFLOW VM can be updated as part of the windows update process which is great, but I was wondering if we had some customizations, like a firewall rule for instance that has been added to the EFLOW instance, are we at risk of losing this if the EFLOW VM is updated?

**Detailed background**
One of our modules are deployed to the docker "HOST" network and require some firewall rules be applied to the EFLOW VM in order for our windows host to be able to access the container running within EFLOW.  I see the [Set-FirewallRules](https://github.com/Azure/iotedge-eflow/blob/main/eflow-util/firewall-rules/Set-FirewallRules.ps1) utility but was thinking of doing something in the EFLOW VM and use "iptables-save" to save the rules so we wouldn't have to apply them on each start of the EFLOW VM.  If I did this, I wonder if on updates if we are at risk of losing this customization.  I read through all the documentation I could find and could not find this answer.

**Comment by fcabrera23** [comment]
Hi @beckerben,

Thanks for reaching out.  For more information, check [EFLOW VM composition & updates](https://learn.microsoft.com/en-us/azure/iot-edge/iot-edge-for-linux-on-windows-updates?view=iotedge-1.4).  Our update mechanism works by using A/B updates, and only the read-only partition is modified. All content that was added to the writable partition wont be modified after updates. 

For your scenario, if you need to enable specific firewall rules, you can use the `iptables-save` command, and you will be able to have the rule persist across reboots and updates.

Thanks,
Francisco

**Comment by beckerben** [comment]
Got it thanks, I had seen that link but it wasn't clear if the A/B updates saved customizations like the ```iptables-save```, glad it does, so thanks for the clarification!
