### ISSUE TITLE
The shared folders are created without errors, but the files and subfolders in the host folder are missing.

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/iotedge-eflow#276]
**Describe the bug**
We create shared folders by 
```powershell
Add-EflowVmSharedFolder -sharedFoldersJsonPath "C:\temp\sharedFolders.json"
```
The shared folders are created without errors, but the files and subfolders in the host folder are missing when we are trying to access them in the EFlowVM.

**To Reproduce**
1. `Add-EflowVmSharedFolder -sharedFoldersJsonPath "C:\temp\sharedFolders.json"`
2. Connect-EFlowVM, navigate to the shared path, the folder is empty.

**Expected behavior**
All files and subfolders in the host folder should be accessible in EFlowVM

**Screenshots**

**Windows Host OS (please complete the following information):**
 - Edition: Windows10 Enterprise LTSC 2019
 - Version:  build 17763
 - Virtual Machine: None
 
**Additional context**
We have tested the folder with:

```powershell
 Get-EflowVmSharedFolder -sharedfolderRoot "C:\temp" -hostFolderPath @("iotedgegateway")
hostFolderPath readOnly targetFolderOnGuest hostFolderFullPath
-------------- -------- ------------------- ------------------
iotedgegateway    False /srv/IoTEdgeGateway C:\temp\iotedgegateway
```
The sharedfolder.json content:
```json
[
    {
        "sharedFolderRoot": "C:\\temp",
        "sharedFolders": [
            {   
                "hostFolderPath": "iotedgegateway", 
                "readOnly": false, 
                "targetFolderOnGuest": "/srv/IoTEdgeGateway" 
            }
        ]
    }
]
```

**Comment by Dolphinsimon** [comment]
ls output in windows：
```powershell
PS C:\temp\iotedgegateway> ls

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2023/10/14     17:30                Cache
-a----         2021/6/3     21:46         151950 module.json
```
/srv/IoTEdgeGateway sudo ls output in EFlowVM is empty.

**Comment by aidassimkus** [comment]
I seem to have the same issue. Shared folders are created without errors (although they have to pre-exist in the VM), but files which are put in the shared folders are not showing up when I connect to VM. If I connect to VM and create some files in the shared folder, they also don't show up in the host.

**Comment by Dolphinsimon** [comment]
@aidassimkus Do you use the same Windows10 Enterprise LTSC 2019?
I think I've found the reason; the shared folder feature is not supported in Windows10 Enterprise LTSC 2019. The [Prerequisites](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-share-windows-folder-to-vm?view=iotedge-1.4#prerequisites) OS is Windows 10/11 (21H2) or higher.

**Comment by Dolphinsimon** [comment]
See this [issue](https://github.com/MicrosoftDocs/azure-docs/issues/99691).

**Comment by jagadishmurugan** [comment]
Yes, SharedFoder is only supported on Client OS (Win11, Win10)...
