### ISSUE TITLE
EFLOW does not create Hyper-V VM? So then how is it virtualized?

### ISSUE THREAD

**Issue by smoms** [Azure/iotedge-eflow#277]
Hi,

I have installed EFLOW on VM (Azure VM, Windows 10). I was assuming to see EFLOW as a VM within Hyper-V in my machine since it requires Hyper-V to be enabled.. But the Hyper-V manager is empty. So I am wondering how EFLOW is virtualized. How does its VM run within Windows?

**Comment by fcabrera23** [comment]
Hi @smoms,

Thanks for reaching out - Please check #50 for more information.

Thanks,
Francisco

**Comment by smoms** [comment]
@fcabrera23 ok thanks. But then why Hyper-V is still required, to be enabled?

**Comment by fcabrera23** [comment]
@smoms,

Hyper-V is used to create the EFLOW VM but uses a different API (HCS instead of VMMS), so it won't show up in Hyper-V Manager. 

Thanks,
Francisco

**Comment by smoms** [comment]
@fcabrera23 last thing on this: when in the other ticket you say "but instead appear more like WSL2 VM in HCS" you mean that it is still using Hyper-V as virtual platform though? And not WSL2..
