### ISSUE TITLE
Azure EFLOW CBL Mariner Size expanded to big footprint

### ISSUE THREAD

**Issue by smoms** [Azure/iotedge-eflow#278]
Hi,

Azure EFLOW is based on CBL Mariner OS. The 2.0 is given as small as [67MB](https://microsoft.github.io/CBL-Mariner/announcing-mariner-2.0/) however its VM size on the host is about 3,5GB (800MB just as ISO size). Why such big size difference?

thanks

**Comment by jagadishmurugan** [comment]
The size is expected due to the inclusion of various packages included by default to enable features we deem important for EFLOW customers (like DDA)
