### ISSUE TITLE
EFLOW: Provisioning via DPS using TPM

### ISSUE THREAD

**Issue by jdbelo** [Azure/iotedge-eflow#28]
I have been exploring Azure IoT Edge for Linux on Windows, a feature that is still in preview. 

Following the [documentation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=powershell#tabpanel_bHGHmlrG6S_powershell) I realized the device provisioning via DPS using TPM is not included. 

Does anyone know why it is not included? Does it mean that TPM attestation mechanism is not supported?

**Comment by fcabrera23** [comment]
Hi @jdbelo,

The documentation is correct; we do not currently support DPS using TPM. However, this feature that we will include in our next update, probably in the following weeks. Once the feature is added, we will update the documentation on how to use DPS with TPM. 

Thanks, 
Francisco
