### ISSUE TITLE
Sending Custom Module from vscode to target machine Eflow

### ISSUE THREAD

**Issue by vermyas** [Azure/iotedge-eflow#280]
**Question Summary**
We have created iot edge custom module in vscode using iotedge extension and we need to deploy custom module to the target eflow machine but we are facing issue in getting custom module reported in eflow device.

**Detailed background**

This is the below error we are facing while we are deploying sample module.
![image](https://github.com/Azure/iotedge-eflow/assets/97602435/9a264c25-4e98-41f6-8268-ee6dacb3699a)

In eflow machine we can see edgeAgent ,edgeHub and simulatedtemperaturesensor modules are running but not able to see sample module which is mandatory to send data to IoTHub
![MicrosoftTeams-image (28)](https://github.com/Azure/iotedge-eflow/assets/97602435/2f93d514-f33c-4a36-bf00-e33570fb7ee7)

so, we need suggestion on why we are getting this error.

**Comment by SummerSmith** [comment]
Hi @vermyas , If this issue still persists in recent versions of EFLOW, please create a new GitHub issue. Thank you!
