### ISSUE TITLE
What is v1.4.11 and why is the update failing?

### ISSUE THREAD

**Issue by KamalAman** [Azure/iotedge-eflow#284]
We have a deployment that went down a few days ago when EFLOW updated to v1.4.11
<img width="300" alt="Screenshot 2024-01-31 at 2 09 01 PM" src="https://github.com/Azure/iotedge-eflow/assets/2692357/3a01a776-057b-4376-aac0-64a1fc0a1803">

It does not seem like a [v1.4.11 release exists](https://github.com/Azure/iotedge-eflow/releases)

<img width="300" alt="Screenshot 2024-01-31 at 2 10 11 PM" src="https://github.com/Azure/iotedge-eflow/assets/2692357/c43a4559-c665-4bc4-a20f-360be53b3d81">

This is the error log from event viewer
<img width="300" alt="Screenshot 2024-01-31 at 2 10 20 PM" src="https://github.com/Azure/iotedge-eflow/assets/2692357/0f64c595-f42f-402e-9ad4-5c92f6a47ca9">

`hcsdiag list` returns nothing.

**Comment by KamalAman** [comment]
It seems like v1.4.11 has been just released, we will keep an one how our other deployments handle this update

**Comment by KamalAman** [comment]
1.4.12.05024 rolled out and took down another one of our deployments out in the wild due to windows update failures. 

This seems like it is going to be a reoccurring issue

**Comment by KamalAman** [comment]
@fcabrera23 Can we please get some eyes on this.

**Comment by SummerSmith** [comment]
Hi @KamalAman and @rabergerik , if you are still experiencing this issue on recent EFLOW releases, please open a new GitHub issue and we will take a look. Thank you!
