### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by sitaalbeMarp** [Azure/iotedge-eflow#286]
Is there a pre-release version that supports .NET 8? Also regarding azure-iotedge for Ubuntu server?

Thanks!

**Comment by SummerSmith** [comment]
@sitaalbeMarp is this still an open question? If so, please reopen this with more details. Thank you!

**Comment by SummerSmith** [comment]
@bishal41 is this a question for Iot Edge?

**Comment by sitaalbeMarp** [comment]
> [@sitaalbeMarp](https://github.com/sitaalbeMarp) is this still an open question? If so, please reopen this with more details. Thank you!

No, thank you!,
Kind regards.
