### ISSUE TITLE
Error  - Failed to provision at line 2411 Failed to provision

### ISSUE THREAD

**Issue by Nilas1994** [Azure/iotedge-eflow#289]
**Describe the Problem**
when trying to provision a eflow vm with  Provision-EflowVM -provisioningType "DpsTpm" -scopeId "xxxxxxxxx" -registrationId "xxxxxxxxxxxxxxxxx"

cannot give the info about provisioning but i get the error where it failed what indicates this error on line 2411 its not very descriptive id like to know what went wrong.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Host OS (please complete the following information):**
 - Edition: [Windows Iot Enterprise]
 - Version: [e.g. build 17763]
 - Virtual Machine: [Local VM]
 
**Additional context**

**Comment by SummerSmith** [comment]
Hi @Nilas1994 , if this issue still persists on recent EFLOW releases, please open a new issue on GitHub and we will take a look! Thank you!
