### ISSUE TITLE
Serial Port support

### ISSUE THREAD

**Issue by joemcfall** [Azure/iotedge-eflow#29]
With previous/current versions of iotedge, I was able to support passing physical comports from the host machine to a running module in a windows host/windows container or linux host/linux container setup.

I understand that iotedge linux-on-windows will be the recommended configuration moving forward.

Is it or will it be possible to pass a physical comport from the windows host to a running linux container?

If this is currently possible, how is this set up?

Thanks in advance!

**Comment by TerryWarwick** [comment]
@joemcfall, 

That is correct, you can find the sample for serial support in our code repository
https://github.com/Azure/iotedge-eflow/tree/main/samples/serial 

Terry Warwick
Microsoft

**Comment by joemcfall** [comment]
@TerryWarwick just curious whether there are plans to either support Windows containers OR support passing serial ports from windows hosts into Linux containers in future versions of iotedge (without having to use tcp sockets). I ask because our organization has been using iotedge with this kind of configuration, and I'm hoping we won't be orphaned in future versions, or have to choose other technologies for what we want to do.
