### ISSUE TITLE
IoT Edge 1.5

### ISSUE THREAD

**Issue by maggiojoe2** [Azure/iotedge-eflow#290]
When will EFLOW be updated for IoT Edge 1.5? 1.4 LTS end of life is this November. Would like to start planning the upgrade process.

**Comment by nelsonmorais** [comment]
Any updates on this topic?

**Comment by ryanwinter** [comment]
@Azure/iotedge-eflow - Can you please answer this question?

**Comment by SummerSmith** [comment]
Hi @maggiojoe2, we are currently working on the EFLOW release with IoT Edge 1.5. This will be released before the 1.4 EOL date, but we do not have a specific date to share at this time.

**Comment by maggiojoe2** [comment]
@SummerSmith there are now 12 days until IoT Edge 1.4 is end of life. When is the 1.5 release for eflow planned? Do we have any information on how the upgrade will work? This is cutting very close on how long we will have to update our devices.

**Comment by SummerSmith** [comment]
@maggiojoe2 , @ryanwinter , @nelsonmorais , we released a new EFLOW version with support for IoT Edge 1.5LTS last week. You can find the release notes [here](https://github.com/Azure/iotedge-eflow/releases)
