### ISSUE TITLE
Azure IoT Edge for Linux on Windows Update Fails

### ISSUE THREAD

**Issue by rabergerik** [Azure/iotedge-eflow#291]
**Describe the bug**
The installation of Azure IoT Edge for Linux on Windows, which is installed automatically via Windows updates, has been consistently failing during the last couple of updates. Initially, the issue was that the "wssdagent" service was marked as disabled after the update. In the latest update (x64 Version 1.4.14.24074), the "wssdagent" service is removed altogether, and attempts to reinstall the service result in an error, making it impossible to start the service.

**To Reproduce**

Wait for the automatic installation of Azure IoT Edge for Linux on Windows (x64 Version 1.4.14.24074) via Windows Update.
Observe that the installation fails.
Attempt to reinstall the "wssdagent" service by running wssdagent.exe install in the directory C:\Program Files\Azure IoT Edge\.
See the error message: "wssdagent registry key already exists" while the service is not running.

**Expected behavior**
The update should successfully install Azure IoT Edge for Linux on Windows, and the "wssdagent" service should be running as expected after the installation without manual intervention.

**Screenshots**

**Windows Host OS (please complete the following information):**
Windows 10 IoT Enterprise LTSC 2019
 
**Additional context**
The issue is occurring at a customer site, making it uncomfortable to perform manual changes to the system. Previously, a workaround involved remotely accessing the machine via TeamViewer, restarting it, and retrying the installation. However, with the latest update, the "wssdagent" service has been removed entirely. After trying to reinstall the service, the error "wssdagent registry key already exists" appears, but the service is not running. We are unsure if manually removing the registry key is the correct approach and would prefer a more reliable solution.

**Comment by SummerSmith** [comment]
@rabergerik are you still experiencing this issue?

**Comment by SummerSmith** [comment]
@rabergerik , I will close this, please open a new issue if you are still facing the same issue.
