### ISSUE TITLE
EFLOW VM doesn't contain proper host name in hosts file

### ISSUE THREAD

**Issue by iconics-rich** [Azure/iotedge-eflow#30]
Not sure if this a bug or not, but we noticed a quirk of the hosts file on the VM that is causing us trouble in connecting to the edgeHub module. Here's the content of /etc/hosts in the EFLOW VM:

```

# Begin /etc/hosts (network card version)

::1         ipv6-localhost ipv6-loopback
127.0.0.1   localhost.localdomain
127.0.0.1   localhost
127.0.0.1   efl-vm
# End /etc/hosts (network card version)

```

Notably, there's no entry there that contains the actual host name of the EFLOW VM, in our case W10IOT-EFLOW-458b3451. On the standard Ubuntu and Raspbian systems we've tested with, there's been an entry included in the hosts file like "127.0.1.1   DeviceHostname"

Is this intentional? By the way, looking at my Preview Preview EFLOW VM, it looks like there was such an entry included.

Not having this entry there seems to result in a failure to connect to the edgeHub. We are using Microsoft.Azure.Devices.Client.ModuleClient.CreateFromEnvironmentAsync(TransportSettings) and TransportSettings are created as new Microsoft.Azure.Devices.Client.ITransportSettings[] { new AmqpTransportSettings(Microsoft.Azure.Devices.Client.TransportType.Amqp_Tcp_Only) }
which are doing based on the example [here](https://github.com/Azure-Samples/iot-edge-sample-dotnet/blob/master/modules/SampleModule/Program.cs)

Once we manually add the missing entry to the hosts file, we're able to connect to the edgeHub successfully.

**Comment by fcabrera23** [comment]
Thanks @iconics-rich for your detailed information. 

Could you please provide us the following information?

1.	What was the deployment method used? (WAC/PowerShell)
2.	What version of EFLOW are you using? You can check the version by following these instructions:
a.	Open Settings on Windows 10
b.	Select Add or Remove Programs
c.	Select Azure IoT Edge app
d.	Check the version number 
1.	Are you using an external or default switch?
2.	Could you please send us the logs? You can get the logs using the Get-EflowLogs command
3.	Could you please send us the following files?
a) /etc/hostname
b) /etc/hosts
c) /etc/iotedge/config.yaml (**make sure no secret information is shared**)


Thanks,
Francisco

**Comment by iconics-rich** [comment]
Hi @fcabrera23 ,
Sorry for the delay. Here's the info you requested:

> What was the deployment method used? (WAC/PowerShell)

I used WAC on Windows 10 (21H1), but I'm seeing similar behavior on a Server 2019 VM where PowerShell was used.

> What version of EFLOW are you using?

1.0.2.0

> Are you using an external or default switch?

External


I've also attached file EFLOW logs and files you requested.

[eflowlogs.zip](https://github.com/Azure/iotedge-eflow/files/6657340/eflowlogs.zip)
[files.zip](https://github.com/Azure/iotedge-eflow/files/6657343/files.zip)

**Comment by fcabrera23** [comment]
Thanks @iconics-rich - We are currently investigating this issue.  Could you please provide us  **/var/log/cloud-init.log** and **/var/log/cloud-init-output.log** files?

**Comment by iconics-rich** [comment]
Here you go.
[cloud-init.zip](https://github.com/Azure/iotedge-eflow/files/6677921/cloud-init.zip)

Thanks,
Rich

**Comment by fcabrera23** [comment]
HI @iconics-rich,

Thanks for your providing the logs.  We have successfully identified the problem and will be fixed in our next update.

Thanks for your help,
Francisco

**Comment by iconics-rich** [comment]
Sounds great, thank you for your help here Francisco.

**Comment by fcabrera23** [comment]
@iconics-rich,

Thanks for your patience. We have released our Generally Available version - Please check out [our latest release](https://aka.ms/AzEFLOW-Latest).

**Comment by iconics-rich** [comment]
@fcabrera23 , That's great news! A quick question on this item from those release notes:

> Windows Admin Center (WAC) Azure IoT Edge extension updated to 1.61.0 to support new EFLOW GA functionalities – WAC IoT Edge extension remains in preview.

I'm not sure what the implications of that are. Does the WAC extension being in preview mean that an EFLOW VM created via WAC will be different to one created via PowerShell?

**Comment by fcabrera23** [comment]
@iconics-rich

The EFLOW VM creation is exactly the same when using PowerShell and WAC. What we mean by saying that WAC Extension is still in Preview, is that the features that are included there for managing the VM using WAC extension are in Preview. We plan to keep improving and adding features in the following updates to our extension. 

Again, to make it clear, EFLOW is GA, but the Azure IoT Edge Extension will continue Preview while we add more features.

**Comment by iconics-rich** [comment]
Ah ok, that makes sense. Thanks for clarifying.

--
Rich Henderson, US QA Manager
t: +1 508 543 8600 • iconics.com<https://iconics.com>
ICONICS – A Group Company of Mitsubishi Electric
Register HERE<https://iconics.com/connect2021> for ICONICS Connect 2021!
***@***.***D76911.A6323DF0]<https://iconics.com/newsletter> [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/iconics>  [A picture containing animal, bird  Description automatically generated] <https://www.twitter.com/ICONICS>  [A picture containing kit, drawing  Description automatically generated] <https://www.facebook.com/ICONICSInc>  [A picture containing drawing  Description automatically generated] <https://www.youtube.com/user/IconicsVideo>
