### ISSUE TITLE
Deploy-Eflow exits with error "Signer is not trusted" during Linux VM image verification

### ISSUE THREAD

**Issue by owainc** [Azure/iotedge-eflow#33]
**Describe the bug**

As per title, following the powershell instructions here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=powershell#create-a-new-deployment

During the "Verifying expected Linux VM image" phase the following error occurs:

```
[06/24/2021 14:48:30] Verifying installation

 - Verifying expected Windows host binaries
 - Verifying expected Linux VM image

[06/24/2021 14:48:57] Exception caught!!!

 - Signer is not trusted (file: C:\Program Files\Azure IoT Edge\AzureIoTEdgeForLinux-v1.cab, certificate thumprint: ) at line 4284

[06/24/2021 14:48:57] Exception caught!!!

 - Verification of Azure IoT Edge for Linux on Windows installation failed (L897)

[06/24/2021 14:48:57] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

Verification of Azure IoT Edge for Linux on Windows installation failed
```

**Windows Host OS**

Attempted on two machines with same result:

- Windows 10 Enterprise LTSC 1809 build 17763.1282
- Windows 10 Pro build 21390.2025

**Comment by TerryWarwick** [comment]
@owainc 

Please make sure that you have set the execution policy for the powershell module per step 3 of the install instructions.

![image](https://user-images.githubusercontent.com/12146834/123299283-33a90b00-d4ce-11eb-8a40-09d94c69fcd1.png)

Terry Warwic

**Comment by owainc** [comment]
Hi, thanks for prompt response.  I have confirmed that execution policy for local machine is `AllSigned` on both machines;

![image](https://user-images.githubusercontent.com/72195676/123300556-9c19db80-d512-11eb-9340-93599080bc0c.png)

**Comment by TerryWarwick** [comment]
@owainc,

The file that you are having issues with is actually signed by Microsoft Corp, perhaps you have an Anti-Virus enabled that is blocking the installation?   These utilities are notorious for issues like this.  Please try disabling and retry the install.

![image](https://user-images.githubusercontent.com/12146834/123313771-acb05e80-d4de-11eb-9288-c7ca40109e54.png)

If disabling your Anti-Virus does not help, we would like you to collect a logfile.  In step Step 2 of the installation process, please use the following command to collect an install logfile

`Start-Process -Wait msiexec -ArgumentList "/i","$([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))"**,"/lv","AzureEFLOWInstall.log",**"/qn"`

Search the logfile for "AzureIoTEdgeForLinux-v1.cab" to see if there are any errors reported and reply with a snippet of the logfile.   If you need to send the full LOG file we can make special arrangements for that rather than posting it here in a public forum.

Terry

**Comment by owainc** [comment]
Thanks for response.  I checked the signature of the cab, confirmed valid chain etc. which was why I was stumped, and only virus checker is Defender.

A quick bit of debugging and it seems it's because I ran in PowerShell (5.1) - it works fine in "Core"/7; `System.Management.Automation.Signature, System.Management.Automation, Version=3.0.0.0` that PowerShell 5 uses doesn't have the `SignerCertificate` property hence the script error.

It may be worth updating docs (or the script) - I'm sure sure there must be other LTSC folks stuck in the past who might run into same problem :).

**Comment by TerryWarwick** [comment]
@owainc, 

Thank you so much for reporting back your findings.  This is great information for anyone else that may encounter the same issue.  We will incorporate this info into either our docs or Wiki here on Github.  Until then, at least anyone else encountering this issue will find your solution.

If you are satisfied with the state of this issue, please go ahead and close this issue.

**Comment by nenright** [comment]
Ran into the same issue as the original post but trying to install using Powershell 7.1 produced:

```
PS C:\Windows\System32> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       AllSigned

PS C:\Windows\System32> deploy-eflow
deploy-eflow: The 'deploy-eflow' command was found in the module 'AzureEFLOW', but the module could not be loaded. For more information, run 'Import-Module AzureEFLOW'.
PS C:\Windows\System32> import-module azureeflow
Import-Module: File C:\Program Files\WindowsPowerShell\Modules\azureeflow\AzureEFLOW.psm1 cannot be loaded. The contents of file C:\Program Files\WindowsPowerShell\Modules\azureeflow\AzureEFLOW.psm1 might have been changed by an unauthorized user or process, because the hash of the file does not match the hash stored in the digital signature. The script cannot run on the specified system. For more information, run Get-Help about_Signing..
```

In attempt to get it working I:

```
PS C:\Windows\System32> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -ForceU
Set-ExecutionPolicy: A parameter cannot be found that matches parameter name 'ForceU'.
PS C:\Windows\System32> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
PS C:\Windows\System32> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    Unrestricted
```

then deploy-eflow produced:

```
[06/25/2021 09:54:07] Exception caught!!!

 - The term 'EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. (L4601)

[06/25/2021 09:54:07] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

Write-EventLog: C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1:4611
Line |
4611 |          Write-EventLog -LogName $LogName -Source $AppName -EventID $E …
     |          ~~~~~~~~~~~~~~
     | The term 'Write-EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
```

If I switch back to powershell 5.1 I get past the Write-EventLog error but back at:

```
[06/25/2021 09:52:26] Exception caught!!!

 - Signer is not trusted (file: C:\Program Files\Azure IoT Edge\AzureIoTEdgeForLinux-v1.cab, certificate thumprint: ) at line 4284
```

any ideas?

**Comment by nenright** [comment]
update: I was able to get past the write-eventlog error by using compatiblity mode;

```
Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell
```

but still fail (using powershell 7.1) with:

```
...
[06/25/2021 10:27:13] Creating vnet (name: Default Switch)


[06/25/2021 10:27:13] Verifying installation

 - Verifying expected Windows host binaries
 - Verifying expected Linux VM image

[06/25/2021 10:27:19] Exception caught!!!

 - Signer is not trusted (file: C:\Program Files\Azure IoT Edge\AzureIoTEdgeForLinux-v1.cab, certificate thumprint: ) at line 4284

[06/25/2021 10:27:19] Exception caught!!!

 - Verification of Azure IoT Edge for Linux on Windows installation failed (L897)

[06/25/2021 10:27:19] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

Verification of Azure IoT Edge for Linux on Windows installation failed
```

**Comment by owainc** [comment]
@nenright You're right, I hadn't had chance to try my "solution" until now and can confirm it doesn't work in PowerShell 7.1 for me either.

**Comment by nenright** [comment]
I just probably infected my whole company with malware but got past the error and was able to install by putting the cab's signer cert in the trusted publisher store - DOHI! :0

**Comment by owainc** [comment]
@nenright Ah yes, the cab is signed with a different certificate (`ABDCA79AF9DD48A0EA702AD45260B3C03093FB4B`) then the other binaries (`3D7E1E393BF85A02007094B249E1EBA19D945D32`).

@TerryWarwick  Not sure where the source for `AzureEFLOW.psm1` is but:

```
    # Since the signature is valid, we may assume SignerCertificate is set
    $certificate = $signature.SignerCertificate
    if (-Not (Test-Path -Path (Join-Path -Path 'Cert:\LocalMachine\TrustedPublisher' -ChildPath $certificate.Thumbprint))) {
        throw $("Signer is not trusted (file: $filePath, certificate thumprint: ${certificate.ThumbPrint})")
    }
```
Is the check causing the issue - perhaps change for `if (-Not (Test-Certificate $certificate)) {`.

**Comment by fcabrera23** [comment]
@owainc,

Thanks for your update. Have you tried using PowerShell 5.1?

**Comment by scout208** [comment]
I'm on PowerShess 5.1 and having the same issue. 

![image](https://user-images.githubusercontent.com/9426329/123695995-dcce6900-d820-11eb-9f57-15ae1fee4438.png)
![image](https://user-images.githubusercontent.com/9426329/123696024-e657d100-d820-11eb-9769-ead8851f79e8.png)

**Comment by owainc** [comment]
@fcabrera23 The `Test-Certificate` method worked - you might want to specify a `-Policy` though.  The whole 5.1 thing was red herring, there are some missing properties on the `Signature` object in 5.1 compared to 7 but `SignerCertificate` isn't one.

The issue is that some installs don't have the `Microsoft Corporation` code signing cert with thumbprint `ABDCA79AF9DD48A0EA702AD45260B3C03093FB4B` in local machine \ trusted publishers - it is valid though.

@scout208 if you edit `C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1` and modify line `4287` to be:

```
if (-Not (Test-Certificate $certificate)) {
```

Restart PowerShell and it'll work.

**Comment by scout208** [comment]
@owainc Thanks! I had to change execution policy to Bypass instead of All-Signed then it worked.

**Comment by TerryWarwick** [comment]
@owainc,

Thank you.  This information is extremely helpful.  We're investigating and will close the loop here shortly.

Terry Warwick
Microsoft

**Comment by katriendg** [comment]
Adding here that I ran into the same error message as posted at the top of this issue. Tried PowerShell 7.1 which gave me other error messages, then followed @owainc workaround with the PSM1 file change and that worked well. Install successful, now going to the next steps.

My test is going through the quickstart and using an Azure VM (picked a VM size that supports nested virtualization as documented).

**Comment by ms-vincent** [comment]
Just came across the same issue and the workaround suggested here works. To clarify, here's the steps that I went through:


1)	edit C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1 and modify line 4283 from:
    if (-Not (Test-Path -Path (Join-Path -Path 'Cert:\LocalMachine\TrustedPublisher' -ChildPath $certificate.Thumbprint))) {

to:
    if (-Not (Test-Certificate $certificate))

2)	Change the execution policy to bypass the verification process:
   Set-ExecutionPolicy -ExecutionPolicy Bypass -Force
3)	Run deployment:
   Deploy-Eflow

**Comment by fcabrera23** [comment]
@owainc, @scout208, @ms-vincent, @nenright,

Thanks for your help finding this problem. The issue was solved and we have released a [new version](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2106.1). You can now download the latest MSI and install EFLOW. 

Thanks,
Francisco
