### ISSUE TITLE
Using External Switch in EFLOW GA?

### ISSUE THREAD

**Issue by iconics-rich** [Azure/iotedge-eflow#34]
Is it possible to change the switch the EFLOW VM is using from the Default Switch to an External Switch? Typically I'd just update a VM's settings in Hyper-V Manager, but as of the GA release, EFLOW VM's are no longer included in Hyper-V Manager.

Our IoT Edge modules send and receive UDP broadcasts to communicate with devices on the host machine's network, so we want the VM to get an IP address on that network, rather than the 172.x.x.x IP address it gets from a default switch.

**Comment by TerryWarwick** [comment]
@iconics-rich,

Currently we are only able to support Default Switch, but we are looking into the feasibility of enabling your scenario.

Terry Warwick
Microsoft

**Comment by fcabrera23** [comment]
Hi @iconics-rich,

We have released our latest EFLOW update that adds the functionality to assign a virtual switch to the EFLOW VM during deployment. By adding this, we support **Internal**, **External**, and **ICS** switches.  For more information on our latest update, check 1[.1.2107.0 Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0).

Thanks,
Francisco
