### ISSUE TITLE
Is the Eflow Edge Device a real iothub device?

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#35]
**Question Summary**
The Iothub allows devices to use it's File Upload API handshake to upload files to Blob storage using SAS Tokens.   Can the EFLOW device leverage this api workflow too?  And if so Could I think have a module leverage it through EFLOW? 

Just wondering

**Comment by veyalla** [comment]
The file upload API is limited to device identities and cannot be used in IoT Edge since edge only uses module identities. 

Perhaps the blob storage module can help? https://docs.microsoft.com/en-us/azure/how-to-store-data-blob?view=iotedge-2018-06

**Comment by hooligan495** [comment]
THanks! 

That link didn't take me anywhere.  but googling found what I think you are referring too, 
 .. if you had a requirement to rotate SAS tokens how does that works?   Desired properties (as the article implies?  The advantage of the File Upload API on iothub is that my device doesn't have to hold onto a long term credential.  and I get to leverage the security channel of IOT Hub.  If I took the desired property approach outlined I'd have to orchestrate something from the cloud that generates and replaces SAS tokens for thousands (or hopefully more) devices.   That seems inefficient. 

And I'm not sure but it doesn't seem like I can send messages to modules from the cloud?   Sending a message from a module for a new token and hoping it gets filled and either a property updated or Direct method invocation seems complex.   

According to your understanding are these my options?  

Tahnks for all your help!

**Comment by veyalla** [comment]
Fixed link in my previous comment.

Agreed, it is not ideal but currently the only option with IoT Edge. For SAS token rotation, you could leverage [layered deployments](https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring?view=iotedge-2020-11#layered-deployment) - create a layer that adds the blob storage module to your devices and then any updates to the layer will get sent to all devices.
