### ISSUE TITLE
Provision EFLOW via DPStpm

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#36]
First off... I'm not an expert with TPMs in general.   so if any of my questions are truly ignorant please forgive me...

I'm installing the new EFLOW release and wanted to provision it using the DPSTpm.   And I'm getting lost trying to follow the documentation with respect to this provisioning path.  I have my laptop that I want to setup the EFLOW install as an Edge device in the hub. 
I've installed Eflow and can connect to it.  But now I want Provision.  And the documentation points to "simulating a TPM For your device".  My laptop has a real tpm.   the Eflow instance should have a pass through to it.   So shouldn't I be able to get an endorsement key/Registration key for Eflow with out using a simulated TPM?   Is there a linux command that will show me this info? 

Or am I thinking about how this should work all wrong?  
Thanks!

**Comment by fcabrera23** [comment]
Hi @hooligan495,

Thanks for your question.  The sample code we provide is a simulator that has the option to retrieve the EK from the physical TPM. That's the easiest way to get the EK. Just download the sample code using your preferred programming language, then run it with the -e flag, and you will get the EK you need to set up on the DPS service on Azure. 

Thanks,
Francisco

**Comment by hooligan495** [comment]
Ah!  I missed that nuance... thanks francisco that helps me a ton.

**Comment by hooligan495** [comment]
Back again.. .so I did what I thought I read on the documentation... On my windows OS (not sure this part is important or not) I ran the C# sample to get the Enrollement key (dotnet run -e) ... then did a hash of the E key to create teh registration id.... (then created an individual TPM enrollment  for my edge device with this info in my iothub)  Then I run Provision-EflowVm command with teh scope id and it fails saying "TPM provisioning information not available"  ... I've tried this multiple times from scratch to the same problem... I know I'm not giving you a lot of context but any thoughts on how to debug?

**Comment by fcabrera23** [comment]
@hooligan495,

Thanks for reaching out. I created a PS function to retrieve the information easier. Please download [here](https://github.com/Azure/iotedge-eflow/blob/main/samples/scripts/EflowTpmProvisioningInfo.ps1) and import the module using an elevated PowerShell session.  Once imported, run `Get-EflowVmTpmProvisioningInfo` and make sure you can get the EK

Thanks,
Francisco

**Comment by hooligan495** [comment]
@fcabrera23  thanks!  I tried running that and it failed.  (thanks a ton for the script tho.. that confirms that I was 'doing it wrong' :) 


In looking at your PS function I sshed into eflow and ran the tpm_device_provision command I'm getting this output

iotedge-user@USWE-6FM1693-L-EFLOW [ ~ ]$ sudo /usr/bin/tpm_device_provision
Gathering the registration information...
Error: Time:Mon Jun 28 21:16:56 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/deps/utpm/src/tpm_codec.c Func:TSS_CreatePersistentKey Line:217 Failed calling TPM2_ReadPublic 0xa
Error: Time:Mon Jun 28 21:16:56 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c Func:initialize_tpm_device Line:459 Failure calling creating persistent key for Endorsement key
Error: Time:Mon Jun 28 21:16:56 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c Func:hsm_client_tpm_create Line:492 Failure initializing tpm device.
Error: Time:Mon Jun 28 21:16:56 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/src/prov_auth_client.c Func:prov_auth_create Line:307 failed create device auth module.
failed creating security device handle

Press any key to continue:

think I need to try and reinstall eflow?  Happy to try that...Jay

**Comment by fcabrera23** [comment]
@hooligan495,

Do you have TPM enabled? To check, please open an elevated PowerShell and run `Get-EflowVmFeature -feature "DpsTpm"`

**Comment by hooligan495** [comment]
it says True

**Comment by fcabrera23** [comment]
Ok, can you try using the Windows key + R keyboard shortcut, type the tpm.msc command and upload the result? Are you sure you have a physical TPM2.0?

**Comment by hooligan495** [comment]
![image](https://user-images.githubusercontent.com/4496/123709872-c41f7c80-d83b-11eb-9cce-6d38d1d8e0d8.png)

I thought I did but maybe now I am not so sure...

**Comment by fcabrera23** [comment]
@hooligan495,

It seems that you have a TPM2.0, so that's not a problem.  Can you open a command prompts as Administrator, and type `sc query eflowproxy`. Also, have you tried shutting down your host? I think maybe there's an issue with the TPM passthrough proxy

**Comment by hooligan495** [comment]
SERVICE_NAME: eflowproxy
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\windows\system32>


Rebooting now to see if anything happens

**Comment by hooligan495** [comment]
after reboot the powershell command you gave me seems to hang (and connecting to eflow the tpm_device_provision command seems to hang too

**Comment by fcabrera23** [comment]
Ok thanks - Can you try to get into the VM and run ` sudo /usr/bin/tpm_device_provision` again?

**Comment by hooligan495** [comment]
Ok... super braindead thing I did.. I did a sudo reboot in the eflow vm.... Could not start/stop it or connect to it across multiple reboots.   
Uninstalled Eflow, installed, enabled TPM feature, and can now provision with DpsTpm.  

Thanks for your help @fcabrera23 something must have been wrong with my eflow installation or something... but now seems good...

**Comment by hooligan495** [comment]
Just to leave this here:

I am doing development on my laptop... When I closed my laptop last night and opened it this moring.. running the tpm_device_prvovision command returned these results:
Gathering the registration information...
Error: Time:Tue Jun 29 13:12:24 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/deps/utpm/src/tpm_codec.c Func:TSS_CreatePersistentKey Line:217 Failed calling TPM2_ReadPublic 0xa
Error: Time:Tue Jun 29 13:12:24 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c Func:initialize_tpm_device Line:459 Failure calling creating persistent key for Endorsement key
Error: Time:Tue Jun 29 13:12:24 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c Func:hsm_client_tpm_create Line:492 Failure initializing tpm device.
Error: Time:Tue Jun 29 13:12:24 2021 File:/usr/src/mariner/BUILD/azure-iot-sdk-c/provisioning_client/src/prov_auth_client.c Func:prov_auth_create Line:307 failed create device auth module.
failed creating security device handle

Press any key to continue:

The rest of the EFLOW vm seemed to be working fine in terms of connecting to it etc.

doing a Stop-Eflowvm and Start-EflowVM seemed to correct the problem... (But not a reboot of my whole machine)

**Comment by fcabrera23** [comment]
@hooligan495,

Thanks for your update - I will try to repo your scenario and we will try to fix it asap.

**Comment by hooligan495** [comment]
If there are any logs I could try to find on my instance of Eflow just let me know.. thanks!
Jay

**Comment by ArchanaMSFT** [comment]
hello hooligan495, 

I was able to repro the issue with following steps:
stop-eflowvm, start-eflowvm, connect-eflowvm, sudo /usr/bin/tpm_device_provision. 
If the host device is rebooted, the tpm works fine.
In your case of host sleeping, I think the "KeepAlive TCP detect" is taking time to comeback alive. The time TPM takes to come back is set as a regkey on the host device. It can be configured.
More information - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc782936(v=ws.10) 
Could you please shorten the keepalive setting so that TCP comes back alive sooner? 

If this isn't the issue you are talking about, please let me know the repro steps. Thank you.

**Comment by fcabrera23** [comment]
@hooligan495,

Could you try Archana's fix? If so, could you fix the problem?

Thanks,
Francisco
