### ISSUE TITLE
TPM endorsement key in GA?

### ISSUE THREAD

**Issue by ericvruder** [Azure/iotedge-eflow#37]
**Question Summary**
In previous versions of eflow, I was able to fetch the TPM endorsement key and registration id assigned to the VM by running the following command:

```powershell
 Get-EflowVmTpmProvisioningInfo
 ```

That command no longer exists - how can I fetch that information in GA?

**Detailed background**
I need this information in order to be able to create an individual enrollment in the DPS service.

**Comment by fcabrera23** [comment]
Hi @ericvruder,

Thanks for submitting the issue. We will consider adding the command in our next update. In the meantime, please check our [TPM Provisioning](https://aka.ms/AzEFLOW-TPM) documentation. There's a sample code to simulate a TPM device that will help you get the EK of your hardware TPM.

**Comment by fcabrera23** [comment]
@ericvruder,

I've added a sample script that allows you to get the EK of the TPM. Please follow these steps to use the function

1. Download the [sample PS module](https://github.com/Azure/iotedge-eflow/blob/main/samples/scripts/EflowTpmProvisioningInfo.ps1)
2. Open an elevated PowerShell session
3. Import the downloaded module
4. Run `Get-EflowVmTpmProvisioningInformation`
