### ISSUE TITLE
Cannot Start Service EFlowProxy

### ISSUE THREAD

**Issue by scout208** [Azure/iotedge-eflow#38]
**Describe the Problem**
I am trying to follow the [documentation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-tpm-linux-on-windows?view=iotedge-2018-06&tabs=powershell#configure-the-device-with-provisioning-information) for setting up auto-provisioning using TPM attestation.  I have installed IoT Edge for Linux on Windows already using the `Deploy-Eflow` command from the previous steps, but I am getting an error when I try to run the command `Provision-EflowVM -provisioningType "DpsTpm" -scopeId "<scope id>"` with my scope id. 

**To Reproduce**
1. Install IoT Edge for Linux on Windows
2. Setup DPS individual enrollment using endorsement key from TPM and copy scope id
3. Run `Provision-EflowVM -provisioningType "DpsTpm" -scopeId "<scope id>"` with scope id from DPS

**Expected behavior**
Expect to run successfully with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/9426329/123712949-f8456e00-d838-11eb-8d2a-1aec5b8b6ebb.png)

**Windows Host OS**
 - Edition: IoT Enterprise
 - Version: 17763.1935
 - Virtual Machine: None

**Comment by hooligan495** [comment]
what does :  Get-EflowVmFeature -feature "DpsTpm" 
return?
If falso then you need to set it to true
Set-EflowVmFeature
I just got TPM dps working with Eflow (I have an open issue that describes the fun I had)

**Comment by ngmartins** [comment]
Hi, 

I am running into the same problem,
Then I tried: `Get-EflowVmFeature -feature "DpsTpm"` and it returns false.
However, if I run `Set-EflowVmFeature -feature 'DpsTpm' -enable` I ran into the same exception:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/24669761/124440599-afc70c80-dd72-11eb-96ee-1df040958fef.png">

The `sc query eflowproxy` does nothing on my host machine. My host's TPM management pages says TOM is ready to use: 

Already tried to re-install the EFLOW VM and restart the host machine.

**Comment by scout208** [comment]
So I tried going into services and starting the EFlowProxy service manually since the problem seems to be with starting that. This is the error I got trying to do that.

![image](https://user-images.githubusercontent.com/9426329/124671649-68787300-de7b-11eb-84f9-45f35d648810.png)

**Comment by fcabrera23** [comment]
Hi @scout208,

Could you please share the EFLOWProxy log. Please follow these steps

1. Launch Event Viewer
2.  Export the events under "Applications and Services Log\Microsoft\EFLOW\EFLOWProxy\Operational"

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/21229385/124851626-e5394900-df70-11eb-8ca7-f14fe949374c.png)

Thanks,
Francisco

**Comment by scout208** [comment]
@fcabrera23 It looks like there are 0 events in that log, unless I'm looking in the wrong spot?

![image](https://user-images.githubusercontent.com/9426329/124942659-70e2c200-dfd1-11eb-9105-7cbff6281ff2.png)

**Comment by fcabrera23** [comment]
@scout208,

Thanks for providing that information. You were looking in the right spot, but apparently the error is happening even before the EFLOWProxy service started. Could you please provide the following logs:

1) Windows log -> System
2) Windows log -> Application

![application](https://user-images.githubusercontent.com/21229385/124984476-427fd980-e007-11eb-9f4d-1ebe1ebf65bd.png)

**Comment by scout208** [comment]
@fcabrera23 It wouldn't let me upload the files straight here so I shared them using OneDrive.

1. Windows log -> System: https://monnarch-my.sharepoint.com/:u:/g/personal/cearly_monarcsport_com/EaKwjB680mZIgWNsqQOUFE4BQxrROq50c49gowPajsERfw?e=ixHWNG
2. Windows log -> Application: https://monnarch-my.sharepoint.com/:u:/g/personal/cearly_monarcsport_com/EVhk3eaDR19JjFvQFdnis-YBPTZ551lV2GhK8SauF_KW0w?e=HVQApU

Let me know if you have any trouble accessing those.

**Comment by fcabrera23** [comment]
Hi @scout208,

Thanks for your logs. EFLOWProxy.exe needs C++ runtime in order to run.  You can install it using the following [link](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0). 

Thanks,
Francisco
