### ISSUE TITLE
Using the Copy-EflowVmFile command from host machine to Eflow and my module can't read it due to permissions

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#39]
I'm trying to copy a file to the Eflow VM... The new copy command allows me to copy the file. 
My deployment.template.yaml is setup to bind a location from Eflow to the Module container
When I run my module I get permission denied on reading the file. 
If I manually  go into eflow (connect-eflowvm) and change the permissions of the file I created to 666 I my module can now read the file.  
Is this something I shoudl be able to address in teh deployment yaml ? (Maybe I'm  missing something in teh binding) or in how the module is launched?  or is there something else?  

Prior to GA this wasn't a problem so I'm not sure where to start
Thanks!

**Comment by fcabrera23** [comment]
Hi @hooligan495,

I imagine you are having a problem with the permissions/ownership of the file you are copying.  Remember that if you are running a module using IoT Edge, then the service is running with the user "iotedge". When you copy a file, the owner of that file it's "iotedge-user" user.  Maybe you could try copying the file to the VM and then user the Invoke-EflowVmCommand to run the Linux command `chown` to change the ownership. 

Thanks,
Francisco

**Comment by hooligan495** [comment]
Interesting... thanks!   I wonder why my code worked beforre (when I was using scp from the host directly) without this issue..   Oh well I can do this... thanks!
Thanks!
Jay
