### ISSUE TITLE
Eflow connectivity

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#40]
We are doing some testing with Eflow and somehow Eflow go into a state where:
I try to ssh into the VM in powershell and got a"The authenticity of host '172.18.13.248 (172.18.13.248)' can't be established.ECDSA key fingerprint is SHA256:XyRA7zu7SXgRR5hKs4S91qwlN2Cz/zIpHaYlDhNvoqs.
Are you sure you want to continue connecting (yes/no)?" prompt.   when using the Connect-EflowVm command. 

We had been just using the Copy-EflowVmFIle powershell command to move some files into EFlow.    

Any thoughts of what could cause this state? and what one should do about it?

**Comment by fcabrera23** [comment]
@hooligan495,

Thanks for your question - Are you trying to establish an SSH session using the "Connect-EflowVm" cmmdlet? Also, are you doing that using the same user that installed the EFLOW VM?

**Comment by hooligan495** [comment]
yes we are using the Connect-EflowVm command and our file copies were dong using the new Copy-EflowVmFile command. 

I have a .net program that is uysing the Powershell API to invoke the new commands to copy files and I am copying multiple files in parallel.   I'm wondering is it possible that I have to sequentially do the copy?

**Comment by fcabrera23** [comment]
Hi @hooligan495,

Yes, I suspect that the parallel copy may be the problem. Can you try again using a fresh install of EFLOW and using sequential copy?

**Comment by hooligan495** [comment]
sequential copy seems better... but I need to do more testing I guess... Why shouldn't I be able to have multiple threads copying files at teh same time tho.?

**Comment by fcabrera23** [comment]
@hooligan495,

We do not support parallels copying due to how we manage the SSH connection and the known_host file.  I will track an enhancement for our futures updates, in the meantime please use sequential copying. 

Thanks,
Francisco
