### ISSUE TITLE
Default-Switch not able to get IP

### ISSUE THREAD

**Issue by Thanga-Abbott77** [Azure/iotedge-eflow#41]
**Describe the Problem**
With the latest version of AzureIoTEdge (AzureIoTEdge LTS 1.1.2106.0) Deploy-Eflow is failing with error “Failed to acquire IP address for the VM”.

This version of EFLOW is using Default-Switch.

We are using Windows 10 Version 1809. Issue is happening after applying Baseline security policies (Windows 10 Version 1809 and Windows Server 2019 Security Baseline).

Issue is not seen if we did not apply Baseline security policies.

Note: Earlier version of AzureIoTEdge (#1.0.x) is working fine even with Baseline security policies in place. This version is using External Switch.

**To Reproduce**
1. Install AzureIOTEdge 1.1 LTS with host having security baseline updates 
2. On Admin Powershell execute Deploy-Eflow

**Expected behavior**
Successful EFLOW deployment  

**Windows Host OS (please complete the following information):**
 - Edition: [Windows 10  IoT Enterprise 1809]
 - Version: [build 17763]
 - Virtual Machine: [Azure VM EFLOW]

**Comment by ArchanaMSFT** [comment]
Hi @Thanga-Abbott77, 
Thanks for submitting your issue. 

Could you please send us the logs? You can get the logs using the Get-EflowLogs command.
Just to confirm, you are deploying EFLOW on Azure cloud VM - is that right?

**Comment by Thanga-Abbott77** [comment]
Here are the logs.
[deploy-logs.txt](https://github.com/Azure/iotedge-eflow/files/6743479/deploy-logs.txt)
[eflowlogs (3).zip](https://github.com/Azure/iotedge-eflow/files/6743480/eflowlogs.3.zip)

Thanks,

**Comment by ArchanaMSFT** [comment]
Thank you @Thanga-Abbott77 

EFLOW GA Version works with Internal switch and not external switch.
Could you please confirm if your host device is cloudVM or WindowsVM or baremetal device?
Also, could you please check if the latest EFLOW (GA version) can be deployed successfully without Baseline security policies?

**Comment by Thanga-Abbott77** [comment]
Our setup: 
Windows 10 IOT 1089 with Baseline security policy applied. 
Installed EFLOW as WindowsVM through widows admin central / powershell command.
It works when baseline policy is not applied.

**Comment by ArchanaMSFT** [comment]
Thank you @Thanga-Abbott77 .
I am sorry that it is taking awhile to figure this out. 
Could you please give me the exact build number (you can get that by running winver command)? Also, please let me know if windows is running on baremetal or if it is a VM?

**Comment by Thanga-Abbott77** [comment]
1) iotedge 1.1.3
2) windows10 1809 V 17763.2028
3) Windows is running on actual PC and not on VM.

Thanks.

**Comment by ArchanaMSFT** [comment]
Thank you @Thanga-Abbott77 .
I am able to repro it now. I will get back to you with more information once we investigate the root cause.

**Comment by ArchanaMSFT** [comment]
Hello @Thanga-Abbott77 
It is likely that some policy is blocking one of the deployment steps. The issue is being investigated. Please expect an update by mid next week. Thank you.

**Comment by omarine** [comment]
Hello,

same issue here  !

Regards,

**Comment by omarine** [comment]
Hello ,

after reboot i went into a new issue 

![image](https://user-images.githubusercontent.com/13197345/125045823-b40a6700-e09d-11eb-9c83-e8b7949765bd.png)


Why the install is trying to create a default switch ?when the hyper-v is enabled the default switch is there by default.

Regards,

**Comment by omarine** [comment]
after i was able to have an ip for the vm but then the install/ps couldn't ssh into the vm

![image](https://user-images.githubusercontent.com/13197345/125051715-89231180-e0a3-11eb-833c-1192f203738b.png)

and no repository with the  name known_hosts could be found either !

thans

**Comment by omarine** [comment]
Hello,

i updated to 21h1 then everything worked as expected !

Default switch seems to be causing the issue on windows 1809 and other issues...

Regards,

**Comment by ArchanaMSFT** [comment]
hello @Thanga-Abbott77 ,
I am pasting the investigation results we shared in another channel for this issue below:

A firewall policy is changed in the security baseline which causes the eflow vm not getting IP address.

Computer
Software\Policies\Microsoft\WindowsFirewall\PublicProfile
AllowLocalPolicyMerge
DWORD:0

The policy value should be 1.

Please refer to the firewall policy document and adjust the policy value, [Firewall CSP - Windows Client Management | Microsoft Docs](https://docs.microsoft.com/en-us/windows/client-management/mdm/firewall-csp)

Please let us know if you have more questions.
Thank you!
