### ISSUE TITLE
Powershell commands

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#42]
When running the Powershell commands for EFLOW (like Copy-EflowVmFile) if I'm running in Powershell 7 I see the following type of output:
```
PS C:\Temp> Copy-EflowVmFile -fromFile C:\Temp\packaged_metadata.json -toFile /home/iotedge-user/storage -pushFile
Write-EventLog: C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1:4611
Line |
4611 |          Write-EventLog -LogName $LogName -Source $AppName -EventID $E …
     |          ~~~~~~~~~~~~~~
     | The term 'Write-EventLog' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

```

I think I get it that Write-EventLog isn't available in PS7... due to it being cross platform... it seems this error doesn't cause the command to fail.. but should I always be able to count on that?  Is there a way to get this error to go away?   (either by pulling in some sort of extension or some flag?)   

I'm writing a .net program (using .net 5 adn pulled the Powershell SDK in which is also based on PS7 and this same error shows up there too... Seeing errors always gives be agita ;)

Thanks!

**Comment by fcabrera23** [comment]
Hi @hooligan495,

We do not currently support PowerShell 7.  Can you try using an [older version](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/)  of the PowerShell SDK? We will consider adding PS7 compatibility in the future. 

Thanks,
Francisco

**Comment by hooligan495** [comment]
I'm running powershell commands from a .net 5 applicaiton.. .I"ll see if I can pull PS5 in...

**Comment by fcabrera23** [comment]
Hi @hooligan495,

FYI - The latest [EFLOW 1.1.2202.21022](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2202.21022) added support for PowerShell 7 and PowerShell SDK.

Thanks,
Francisco
