### ISSUE TITLE
Create an Azure IoT Edge for Linux on Windows deployment stops with 404 error

### ISSUE THREAD

**Issue by tickledblue3** [Azure/iotedge-eflow#43]
**Describe the Problem**
Get 404 Using Windows Admin Center to create a new Azure IoT Edge for Linux on Windows deployment.

**To Reproduce**
1. In Windows Admin Center, click on + Add
2. Click on "Create new" for Azure IoT Edge
3. Click Next on Prequequisites
4. Accept license agreement and click Next
5. Diagnostic data - keep off, click Next: Deploy
6. Select target device - click on Select to evaluate (get "Supported"), and then click Next
7. Settings - keep all the defaults and click Next
8.  Momentarily see deployment page, but get error:
**Deployment failed with errors**
Duration: 0 minutes 0 seconds
The remote server returned an error: (404) Not Found.

**Expected behavior**
Expected a successful deployment.

**Screenshots**

**Windows Host OS**
 - Edition: Windows 10 Enterprise LTSC
 - Version: 1809
 - Virtual Machine: None (installed on H/W)
 
**Additional context**
Have successfully deployed EFLOW previously on this same machine.   Completely uninstalled Windows Admin Center and Azure IoT Edge for Linux on Windows more than once before with no issues.

**Comment by TerryWarwick** [comment]
@tickledblue3,

Thank you for reporting this issue.  We had a broken link, but it has been fixed.  Please refresh your Windows Admin Center session and try again.  Let us know if you continue to see the 404 error.  If this issue is resolved, please close this issue request confirming that the link now works for you.

Terry Warwick

**Comment by tickledblue3** [comment]
That fixed it, thanks for the quick resolution.
