### ISSUE TITLE
Connect-EflowVM fails with non-descriptive error and no way to troubleshoot

### ISSUE THREAD

**Issue by dmaxwe22** [Azure/iotedge-eflow#48]
Connect-EflowVM results in following error: 

ssh : GetConsoleMode on hOutputConsole failed with 6
At C:\Program Files\WindowsPowerShell\Modules\AzureEFLOW\AzureEFLOW.psm1:2213 char:17
+ ...             ssh -o LogLevel=ERROR -o UserKnownHostsFile="$HostKeySess ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (GetConsoleMode ...e failed with 6:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**To Reproduce**
1. Successful Deploy-Eflow
2. Successful Provision-EflowVm
4. Successful telemetry with Azure IoT Hub and metrics view OK. All is OK. 
5. Connect-EflowVM fails. 

**Expected behavior**
Expected to be able to connect to the EFLOW virtual machine. 
Troubleshooting documentation is scarce. 

Get-EflowLogs runs for a while but I have to stop it. 

PS C:\WINDOWS\system32> Get-EflowLogs
[07/15/2021 20:48:12] Collecting Logs from Deployment...
[07/15/2021 20:48:12] Collecting configuration
[07/15/2021 20:48:12] Collecting 'Azure IoT Edge for Linux on Windows' event logs
[07/15/2021 20:48:12] Collecting virtual machine logs

-- stopped it here because it hung up ---

How do I find out where the problem is in connecting to the EflowVM?

**Comment by TerryWarwick** [comment]
@dmaxwe22,

Just a hunch, but by any chance are you using Remote PowerShell when you are invoking the Connect-EflowVM command?  Both of these commands require SSH, which would be attempting a double-hop which any combination of Remote PowerShell and SSH do not allow.  It would be possible from a Remote Desktop session, but not a Remote Powershell session.

Terry Warwick
Microsoft

**Comment by dmaxwe22** [comment]
I am not using a remote PowerShell attempt to connect. The deployment is using a PowerShell ISE on the same Windows 10 IoT Enterprise 2019 computer and running it in the administrative mode. I chose the PowerShell method of implementing the deployment because the Windows Admin center method was more complicated than needed. Everything worked well and the DPS with X509 deployment worked and telemetry is streaming to the IoT Hub. Except three things are not normal and blocking further work. 

1. I cannot connect using this Connect-EflowVM. An error as stated above results.
2. I cannot get logs. It seems to shut down the VM and does not complete. Maybe this is coincidence. After restarting the VM (Start-EflowVM), I tried again and same results.
3. I cannot see the IoT Edge Linux VM in the Hyper V manager on the computer. It seems a ghost and yet telemetry is streaming. 

One additional clue. This same computer was used for the windows version of Azure IoT Edge but I uninstalled it and the iotedge folder is gone.  

Where is the documentation or where is the source code for the PowerShell modules so that I can get clues why the errors occur? If not, I would appreciate help here in this issues area. Thank you.

**Comment by fcabrera23** [comment]
Hi @dmaxwe22,

Thanks for your detailed information. 

For your questions 1 and 2 - Can you try using PowerShell with elevated permissions instead of using PowerShell ISE?
For your third question - Unfortunately, this interface won't longer be available to manage the EFLOW VM since GA. To introduce GPU support for the VM, we had to change our VM management interface from WMMS to HCS.  As such, the EFLOW VM will no longer be visible in Hyper-V but instead, appear more like WSL VM in HCS.  

Thanks,
Francisco

**Comment by dmaxwe22** [comment]
Thanks, @fcabrera23, using PowerShell with elevated permissions instead of PowerShell ISE with elevated permissions seems to have worked. I am now able to Connect-EflowVM and use commands like sudo iotedge list and so on.
