### ISSUE TITLE
Expose a modules PORT on the host machine / statically on the network

### ISSUE THREAD

**Issue by KamalAman** [Azure/iotedge-eflow#51]
**Question Summary**
How can you EXPOSE a PORT for a module that such that it is tied to the Windows host machines IP Address instead of the EFlowVM's IP address

**Detailed background**
It seems like under certain conditions the EFLOW VM IP address changes, this does not provide a reliable address to access modules running in the EFLOW VM.

**Comment by fcabrera23** [comment]
Hi @KamalAman,

Thanks for your information. As part of the EFLOW GA release, we changed the EFLOW VM host naming. The new naming is generated by the Windows host device name + "-EFLOW".  Maybe you could try using the EFLOW VM hostname instead of the IP address. 

Thanks,
Francisco

**Comment by KamalAman** [comment]
Interesting, is `Windows host device name + "-EFLOW"` documented anywhere?  I will try this out.

I think the original question about exposing it though the host is still valid,
It's not ideal that an end user would be subject to the complexity of having to know that an application is running in EFLOW for them to access an endpoint on a module with a web application running.

**Comment by fcabrera23** [comment]
@KamalAman,

This was documented as part of our [GA release notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2106.0) under **Changes from Public Preview**.

I would like to clarify your initial question. From my understanding, you would like to expose the EFLOW VM port to external devices. In this case, external devices should be able to connect directly with the IoT Edge module that has an X open port. Is that correct?

**Comment by milijan** [comment]
I have tried running in a simple flask web app in my environment and I could reach the app with the ip shown by `Get-EflowVmAddr` but it doesn't work using the VM hostname `Windows host device name + "-EFLOW"`

**Comment by KamalAman** [comment]
My statement is `external devices should be able to connect directly with the IoT Edge module through the hosts IP address that has an X open port forwarded to a Z modules port.`

Client connect to Host Port X -> forwarded to EFLOW Port Y -> forwarded to module Port Z

In the EFLOW hosting a web application on the edge Use Case, the end user to not know or care about EFLOW nor should they have to.

**Comment by fcabrera23** [comment]
Hi @KamalAman,

There are two different approaches to solve this problem.

1.  Use an external switch assigned to the EFLOW VM - In this case, the EFLOW VM will have an IP in the address range of the other external devices, and these devices will be able to connect directly to the EFLOW VM using the IP.  We have released our [latest update](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0) that includes the functionality to assign.
2. Use an internal switch and do port redirection in the EFLOW Windows host. In this case, the EFLOW VM is accessed through an internal network and the external devices are not aware of the existence of the EFLOW VM.  To solve this, the external devices will use the EFLOW Winows host IP to communicate, and then this host will take care of redirecting the traffic to EFLOW VM. 

For more information on our latest update, check 1[.1.2107.0 Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0).

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @KamalAman,
 
FYI - If you are using an external switch, you can set up a static IP using the systemd-networkd configuration file. Please check [Network configuration with networked](https://kinvolk.io/docs/flatcar-container-linux/latest/setup/customization/network-config-with-networkd/) for further information.
