### ISSUE TITLE
The naming and casing of hostname of provisioned EFLOW VM.

### ISSUE THREAD

**Issue by jamesclu** [Azure/iotedge-eflow#52]
**Describe the bug**
Deploy-Eflow seems to always append “-EFLOW” to Windows hostname. In my case, I have my Windows hostname in lowercase and the provisioned EflowVm actually has my Windows hostname changed to uppercase with “-EFLOW” appended to it!?

**To Reproduce**
$msiPath = $([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest "https://aka.ms/AzEflowMSI" -OutFile $msiPath
Start-Process -Wait msiexec -ArgumentList "/i","$([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))","/qn"
Deploy-Eflow

**Expected behavior**
Assuming a Windows 10 with hostname 'mywindows', after running Deploy-Eflow command, the provisioned EFLOW VM, when using Connect-EflowVm, should have the hostname as 'mywindows-eflow', instead of what it is - MYWINDOWS-EFLOW.

**Screenshots**

**Windows Host OS (please complete the following information):**
 - Edition: [e.g. Professional, IoT Enterprise, Server, etc]
 - Version: [e.g. build 17763]
 - Virtual Machine: [eg. Azure VM, Local VM, None]
 
**Additional context**

**Comment by johnsonshih** [comment]
deploy-eflow gets host computer name from the environment variable $env:COMPUTERNAME and appends '-EFLOW' to the host computer name as eflow vm hostname.  You can change your environment variable to lower case if you want.  for the '-EFLOW ' suffix, it's in upper cases by design.

**Comment by jamesclu** [comment]
Okay, but it can create a problem for your samples, such as interop-textmsg-consoleapp. Specifically, in Step 4 – Create Certificates for Authentication where self-signed certificates are generated with CN (hostname) in lowercase, which invalidates the cerificates!

Thanks,
           ____
 __    /  /  /
/  /_ / /  /__
\___/____ /
James Lu
||| Director, Software Development
Aspen Technology, Inc. ||| +1 781-221-6463 ||| www.aspentech.com<http://www.aspentech.com/>
Developing Microsoft Azure Solutions
***@***.***D77D82.529B2A00]

**Comment by fcabrera23** [comment]
Thanks @jamesclu,

We will update the documentation to make sure the user is aware of the naming scheme used. 

Thanks,
Francisco
