### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by ancaantochi** [Azure/iotedge-eflow#54]
**Describe the Problem**
It seems that step 7 is not valid anymore and documentation need to be updated: https://github.com/Azure/iotedge-eflow/blob/main/samples/interop-textmsg-consoleapp/Documentation/Configuring%20the%20IoT%20Edge%20Device.MD

**Expected behavior**
Customer reported an issue when following the steps, it seems that id_rsa is missing, instead they should use: Copy-EflowVmFile that replaced the scp procedure.

**Comment by fcabrera23** [comment]
HI @ancaantochi ,

Thanks for noticing that. I have already updated the documentation to use our latest [EFLOW PowerShell functions](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06).
