### ISSUE TITLE
Copy-EflowVM error when trying to copy files to Eflow VM

### ISSUE THREAD

**Issue by bryangregoire** [Azure/iotedge-eflow#56]
**Describe the bug**
Got an error saying **Could not resolve hostname file : no such host is known**

**To Reproduce**
1. Just deployed AzureIoT Edge for Linux with Powershell command and provisionned it with DpsX509 method

**Expected behavior**
Should have copied files... the powershell command should be aware of the created VM.

**Screenshots**
![image](https://user-images.githubusercontent.com/87985593/127208435-3f7f1113-fe35-45b8-9f93-d99dc532edc5.png)

**Windows Host OS (please complete the following information):**
 - Edition: Windows IoT 10 Enterprise 21H1
 - Version: build 19043.1110
 - Virtual Machine: Physical box
 
**Additional context**

**Comment by fcabrera23** [comment]
Hi @bryangregoire,

Thanks for your detailed information.  I was able to reproduce your issue and I think is related to the way you are using the -fromFile flag.  Can you execute the command but without the _"file:///"_ and instead use this format `Copy-EflowVmFIle -fromFile "C:/Certs/....` ?

Thanks,
Francisco

**Comment by bryangregoire** [comment]
HI @fcabrera23 !

Yes, tried it and worked! Sorry, that was the only thing I didn't try! I'm on with copying my certificates files. Do you have by chance any updated documentation on how to configure certificates and options (the deamon.json file) in Eflow ? Does this change from earlier Windows native iotedge binaires ?

**Comment by fcabrera23** [comment]
Hi @bryangregoire,

Thanks for your confirmation. IoT Edge configuration on EFLOW should be the same as other Linux OS's.  Check [[Manage certificates on an IoT Edge device](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2018-06)  and [Configure an IoT Edge device to communicate through a proxy server](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2018-06). 

Thanks,
Francisco
