### ISSUE TITLE
Signer not trusted error during EFLOW deployment

### ISSUE THREAD

**Issue by Abvik** [Azure/iotedge-eflow#57]
I am facing '“Signer not trusted” error while deploying the EFLOW VM.
This issue is happening with both LTS (#AzureIoTEdge LTS 1.1.2106.1) and previous version(AzureIoTEdge).

Steps to Reproduce the error:
•	Install AzureIoTEdge (any version).
•	Connect the physical device to the internet.
•	Enable Hyper-V and Containers.
•	Enable the required services (like ICS, Windows Update, Server, Hyper-v..).
•	Make sure windows update service is enabled and running.
•	Deploy the Eflow VM using “Deploy-Eflow" command.
•	Even though Windows Update service is enabled, there is warning message saying that “WARNING: Microsoft Update is not enabled. Please enable manually to ensure Azure IoT Edge for Linux on Windows stays up to date."
•	Then deployment failed with error “Signer is not trusted (file: D:\AzureIoTEdge\wssdagent.exe, certificate Subject: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US) at line 4294"

**Comment by fcabrera23** [comment]
Hi @Abvik,

Did you follow the instructions from [Install and provision Azure IoT Edge for Linux on a Windows device
](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=powershell)? 

Do you have multiple PowerShell installations?

**Comment by Abvik** [comment]
Hi,

Yes I followed the instructions and issue#33, and it is working working most of the devices which are on open network.
But it is failing on certain devices where restricted network is there.
Is it possible to remove the "windows update" service dependency?
We don't want enable that services on our devices.

**Comment by fcabrera23** [comment]
Hi @Abvik,

Windows Update is not a dependency, you can opt-in/out for the EFLOW updates.  Could you share a screen capture of the error, and the deployment logs (under D:\Azure IoT Edge\)

**Comment by Abvik** [comment]
@fcabrera23
Thank you for your quick response.

I couldn't find deployment logs under "D:\Azure IoT Edge".
Attached screenshot of the deployment error.
![Error](https://user-images.githubusercontent.com/88108452/127708251-5e8d77b4-c0c5-45a5-8e47-f2849e4d4424.PNG)
![Logs](https://user-images.githubusercontent.com/88108452/127708252-6937b395-17a7-44b3-8deb-0cd1b3f5a073.PNG)

**Comment by Abvik** [comment]
@fcabrera23

Couldn't proceed with the deployment without "Windows Update" service.
Can you please provide instructions on how to do the deployment without "Windows Update" service?
I believe that will solve my issue.

**Comment by fcabrera23** [comment]
Hi @Abvik,

Thanks for your detailed information. We were able to find a bug related to the Windows Update requirement, and we will fix it it for the upcoming update.  We expect to have news in the upcoming days.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @Abvik 

We have released our latest EFLOW update that fixes the requirement of Windows Update during deployment.  For more information on our latest update, check 1[.1.2107.0 Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0).

Thanks,
Francisco
