### ISSUE TITLE
TPM provisioning fails for devices previously provisioned

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#60]
**Describe the Problem**
After using DpsTpm as provisioning type a first time, I wasn't able to re-provision the same device.
Use cases: change the hub device name or change the hub device type

**To Reproduce**

1. Running the command: `Provision-EflowVM -provisioningType "DpsTpm" -scopeId "scopId"`
2. Get the output: ` Provisioning successful. iotedge service running.`
3. No device was created on IotHub Portal.

**Expected behavior**
New IotEdge/IoT device created on the targeted hub

**Windows Host OS (please complete the following information):**
 - Edition: Enterprise
 - Version: build 19043.1110
 - Virtual Machine: No. I am using physical devices
 
**Additional context**
It is happening in 2 different devices

**Comment by hooligan495** [comment]
silly question here.. but how did you create teh enrollment.. there is a dropdown in the creation of the enrollment that allows you to specify "allow reprovisioning" or "never allow re-provisioning"

**Comment by ngmartins** [comment]
Thanks for the tip @hooligan495.
But I figured out what my problem was. I was using a wrong registration ID in the Individual Enrolment registration
