### ISSUE TITLE
Error at WAC connection to EFLOW

### ISSUE THREAD

**Issue by dmitriyteteruk** [Azure/iotedge-eflow#61]
**Describe the Problem**
Cannot connect to IoT Edge via Windows Admin Center

**To Reproduce**
1. Setup WAC
2. Deploy EFLOW
3. Reboot
4. Getting Error 
```
Connection error
RemoteException: The 'Verify-EflowVm' command was found in the module 'AzureEFLOW', but the module could not be loaded. For more information, run 'Import-Module AzureEFLOW'.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/34028526/128354875-42ead64c-a1f7-414e-8f11-33224d8e6abe.png)
![image](https://user-images.githubusercontent.com/34028526/128354996-51767fb0-559c-44a3-8799-3196e889e640.png)

**Windows Host OS (please complete the following information):**
 - Edition: IoT Ent 2019 LTSC
 - Version: 17763.2090
 - Virtual Machine: Local VM
 
**Additional context**
I can connect to VM using **Connect-EflowVm** command from elevated PowerShell and see that IoT Edge works fine.
Before VM reboot WAC worked fine.
![image](https://user-images.githubusercontent.com/34028526/128355256-8e73590a-1c30-4324-b6b8-ef581326a4ec.png)

**Comment by TerryWarwick** [comment]
@dmitriyteteruk,

Please try connecting to the PC Connection first on the Windows Admin Center home screen first.  It will prompt you for consent to connect to the device.  Once you have been able to access the PC Connection this should clear you for access to the Azure IoT Edge connection.

Terry Warwick
Microsoft

**Comment by dmitriyteteruk** [comment]
Thank you Terry! It works!
