### ISSUE TITLE
Creating Binds in your deployment manifest to share a folder to your module container, how should I expect it to work? 

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#62]
**Question Summary**
I am creating a Bind in my deployment manifest for a deployment to a module on my EFLOW (using the latest 1.1.2107.0).  The bind looks like this: 
"createOptions": "{\"HostConfig\":{\"Binds\":[\"/home/iotedge-user/storage:/app/storage\"]}}"

AS soon as I deploy to a blank edge device, if I haven't manually created the /home/iotedge-user/storage folder it seems EFLOW's deployment does.  This would be great, except that the folder is created with an owner of root and a permission mask of 755.  Meaning my modules will only be able to read from this folder.  

in my reading the default for the Binds statement is rw (the only other option is read only (ro).    

It seems odd to me that this folder is created with root ownership and group.  Maybe it's a docker thing?  But I'd like to get your take on this.   It turns out that in the all up solution I am creating I can have a piece of software on my host os run a check to invoke a chmod and chown command on this folder.  But I just found it odd that this folder was created with the Root as owner.  

Does this line up with what you'd expect to happen in this case?

**Comment by fcabrera23** [comment]
HI @hooligan495,

I was able to reproduce your scenario. This is something related to IoT Edge rather than EFLOW.  From their perspective, if you start a docker container with a host mount that doesn't exist, Docker creates it itself. Since dockerd runs as root, that's what the mount is created as.

Thanks,
Francisco
