### ISSUE TITLE
Azure IoT Edge for Linux on Windows is very unstable

### ISSUE THREAD

**Issue by owbeg** [Azure/iotedge-eflow#63]
**Azure IoT Edge for Linux on Windows stops working**
I installed successfully Azure IoT Edge  on Windows 10 IoT (Version 10.0.17763.2114).
Also I installed modules to support OPC UA communications with Azure Cloud (IoT Hub) - OPC Publisher, OPC Twin , OPC Discovery.
IoT Edge runtime worked for several days but then stopped to response:
- when i try to open Azure IoT Edge Manager in Windows Admin Center it doesn't display dashboard for several minutes
![error2](https://user-images.githubusercontent.com/9317171/129874697-0cce0154-b1d2-4fc8-b45c-58102bdc5c16.jpg)
 and then shows page as on attached screeshot
![error4](https://user-images.githubusercontent.com/9317171/129874705-42208fa2-ec7e-4d74-bedd-2f489261c392.jpg)

- also in Windows Admin Center displayed error "Unable to query host device for current version and available updates. RemoteException: Invalid class "win32reg_addremoveprograms"
![error1](https://user-images.githubusercontent.com/9317171/129874692-b9760e11-74d3-4838-bd0b-12f0fb022944.jpg)

- when I try to connect to Eflow VM from the Powershell session (with Connect-EflowVm command) it waits for several minutes and then display error "Could not resolve IP address for virtual machine at line 2223"
![error5](https://user-images.githubusercontent.com/9317171/129875272-d5d50802-8045-4bdb-8afb-5fc09c8cff73.jpg)

Restarting service "WSSD Agent Service" dosn't help.
Similar issues exists on other similar environment

Please help with diagnosing what is the reason for this issue.

**Comment by fcabrera23** [comment]
Hi @owbeg,

Thanks for all your detailed information. I'm sorry to hear you're facing those issues and will try to collaborate with you to diagnose the problem and fix it. It would be helpful if you could share the following information:

1) Are you using Default Switch or External Switch? If using Default Switch, are you using Static IP?
2) Could you please share the modules you are using, or the deployment manifest you are using so that we can repro your environment?
3) What's the CPU/Memory allocation for the EFLOW VM?
4) Is your PC domain joined?

Thanks,
Francisco

**Comment by owbeg** [comment]
Hi Francisco,

> 1. Are you using Default Switch or External Switch? If using Default Switch, are you using Static IP?
I think I used default switch because I didn't make any network configuration before installation IoT Edge Runtime.
Primarally IP address allocated dynamically. But we have a PC (and where I tried to install Iot Edge runtime) with 3 network devices:
- 1st Ethernet port connected to corporate network, IP address allocated automatrically
- 2nd ethernet port with static IP address (it is used to connect sensors via Ethertnet/IP protocol)
- WiFi adapter with static IP address (configured for WiFi hotspot and it is used for connecting external embedded computers)

> 2. Could you please share the modules you are using, or the deployment manifest you are using so that we can repro your environment?
I can provide image URI which I used during module installation
1) mcr.microsoft.com/iotedge/opc-publisher:latest
2) mcr.microsoft.com/iotedge/opc-twin:latest
3) mcr.microsoft.com/iotedge/discovery:latest
But I think it is doesn't matter which module installed - I have IoT edge runtime environment with installed module SimulatedTemperatureSensor (mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0) and this runtime is also doesn't work properly (with the same symthoms which I described)

> 3. What's the CPU/Memory allocation for the EFLOW VM?
CPU - Intel i3-7100E @ 2.9 GHz
total memory - 16 GB

> 4. Is your PC domain joined?
computers is not joined to corporate domain

Thanks,
Oleg

**Comment by fcabrera23** [comment]
Hi @owbeg,

Thanks for your information. I will try to reproduce your problem and let you know. 

Thanks,
Francisco

**Comment by jagadishmurugan** [comment]
HI @owbeg,
Can you run the following cmds and share the output:
1. hcsdiag list
2. hcsdiag console "EFLOW-VM-ID"
3. ifconfig
![image](https://user-images.githubusercontent.com/13490512/129943944-9e05804e-0f74-441c-af23-7000803d5cb9.png)

Also the ip address on the Default Switch:
![image](https://user-images.githubusercontent.com/13490512/129944164-aa3b9e7d-7157-432b-b2eb-c77c237a11c4.png)

Thanks!

**Comment by owbeg** [comment]
Unfortunately, command "hcsdiag console "EFLOW-VM-ID"" terminated with the error:

![req_1_01](https://user-images.githubusercontent.com/9317171/129948424-8aa4aaec-f33f-4bbc-928b-21ae157a5cec.jpg)

ip address on the Default Switch is 172.17.36.225

![req_1_02](https://user-images.githubusercontent.com/9317171/129948663-ae1f8660-92ab-43f9-ac36-2c2402a20c98.jpg)

**Comment by jagadishmurugan** [comment]
@owbeg , the ID is not correct. You should see an entry ending with WssdAgent (the one you have used is VMMS)

**Comment by fcabrera23** [comment]
@owbeg,

Can you first try to do `Start-EflowVm` and then do the `hcsdiag list`

![image](https://user-images.githubusercontent.com/21229385/129960508-f6170ecc-795d-4620-90de-313d0e25a891.png)

**Comment by owbeg** [comment]
@fcabrera23 , now after Start-EflowVm "hcsdiag console ..." is working:
![image](https://user-images.githubusercontent.com/9317171/130019499-abf27fd6-2482-4539-9a4a-299055f3b315.png)

`
C:\Windows\system32>hcsdiag console 19C7263F-EEA9-11EB-A820-00301A4ECFC8
sh-4.4# ifconfig
br-c331b51a94c4 Link encap:Ethernet  HWaddr 02:42:c5:84:96:5f
          inet addr:172.19.0.1  Bcast:172.19.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:c5ff:fe84:965f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:98 errors:0 dropped:0 overruns:0 frame:0
          TX packets:45 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:14236 (14.2 KB)  TX bytes:17535 (17.5 KB)

docker0   Link encap:Ethernet  HWaddr 02:42:67:84:0c:0f
          inet addr:172.18.0.1  Bcast:172.18.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 00:15:5d:ef:88:e4
          inet addr:172.17.36.235  Bcast:172.17.36.239  Mask:255.255.255.240
          inet6 addr: fe80::215:5dff:feef:88e4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:94 errors:0 dropped:0 overruns:0 frame:0
          TX packets:198 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:22378 (22.3 KB)  TX bytes:24746 (24.7 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6511 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6511 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:600584 (600.5 KB)  TX bytes:600584 (600.5 KB)

veth9ed3ace Link encap:Ethernet  HWaddr 3e:5c:66:2b:b3:e3
          inet6 addr: fe80::3c5c:66ff:fe2b:b3e3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:51 errors:0 dropped:0 overruns:0 frame:0
          TX packets:55 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:11522 (11.5 KB)  TX bytes:18331 (18.3 KB)

vethe6cb196 Link encap:Ethernet  HWaddr f6:c8:bd:04:07:f1
          inet6 addr: fe80::f4c8:bdff:fe04:7f1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:68 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:10035 (10.0 KB)  TX bytes:3471 (3.4 KB)

vethf4a63fd Link encap:Ethernet  HWaddr 72:95:f8:27:81:51
          inet6 addr: fe80::7095:f8ff:fe27:8151/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2661 (2.6 KB)  TX bytes:6759 (6.7 KB)

sh-4.4#
`

**Comment by owbeg** [comment]
@fcabrera23 , does it mean that for restaring Eflow VM is not enough to restart "WSSD Agent Service" Windows service (and we always need to execute Start-EflowVm command after service restart) ?

**Comment by jagadishmurugan** [comment]
@owbeg, If the host is rebooted then the EFLOW VM should be automatically started. But if Stop-EflowVm is executed, then Start-EflowVM is required to start the VM (restarting "WSSD Agent service" is not enough)...

**Comment by owbeg** [comment]
After executing command Start-EflowVm Eflow VM has been started and I could connect with "hcsdiag console" and Connect-EflowVm commands. And even on the Azure Portal I can see that Edge modules successfully connected to the cloud.
Later (I kept session opened with Connect-WflowVm active) I executed command to get log for edgeAgent module (with "sudo iotedge logs edgeAgent") - it output log (see attached text file) but then all commands "sudo iotedge ..." hung (even "sudo iotedge list").
And now it is impossible to connect to the Eflow VM with "hcsdiag console" and Connect-EflowVm commands.

[console_log.txt](https://github.com/Azure/iotedge-eflow/files/7019463/console_log.txt)

**Comment by owbeg** [comment]
Windows reports high CPU usage by Vmmem and wssdagent processes

![image](https://user-images.githubusercontent.com/9317171/130188484-988c30ab-bee5-4906-8659-dda45fa96aaf.png)

**Comment by owbeg** [comment]
I don't know what happened but now commands "sudo iotedge " executed as usually. CPU usage og the host PC decreased significantly (now Vmmem process takes several percents of the CPU time).

Log of the edgeAgent module contains a lot of network errors. I saved log to the file on Eflow VM. But how to transfer this file to host OS?

**Comment by TerryWarwick** [comment]
@owbeg,

Can you please check the version of EFLOW that you have installed on this device?  Go to Start - Settings - Apps and look for Azure IoT Edge LTS in the list.  Once you select this App it should show you the version.  I suspect that you are currently on 1.1.2106.1.  There is a newer update that can be applied through Windows Update that will upgrade you to 1.1.2107.0 [Release Notes](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2107.0) that will fix this CPU utilization issue.  

The Windows Admin Center plug-in for Azure IoT Edge, which is still in preview, may not be compatible with this newer release yet.  You can interact with EFLOW using our PowerShell interfaces [documented here](https://aka.ms/azeflow-powershell).

If the excessive CPU issue has already been resolved and you are on Azure IoT Edge LTS v. 1.1.2107.0 and you are now encountering another issue could you please close this issue and open a new issue for the different problems. 

Terry Warwick
Microsoft

**Comment by owbeg** [comment]
installed Azure IoT Edge LTS version 1.1.2107.0

![image](https://user-images.githubusercontent.com/9317171/130487061-a5e6ebac-acbd-4bf5-932a-6c0c9ad05a29.png)

**Comment by fcabrera23** [comment]
Hi @owbeg,

I'm suspecting that you could be having a memory issue problem.  Can you please open an elevated PowerShell session and run the following command and paste the output: ` Get-Eflowvm | Format-List`?

Also, connect to the EFLOW VM and run `sudo top` and share the output.

Thanks,
Francisco

**Comment by owbeg** [comment]
@fcabrera23 , please see attached screenshots
=============================  Get-Eflowvm | Format-List output =========================================
![image](https://user-images.githubusercontent.com/9317171/130566237-617498ea-6863-473c-aee4-5b6f0f909869.png)

PS C:\work_tsib\Edge> Get-Eflowvm | Format-List


VmConfiguration    : @{ID=1dcf38fc67836e2; name=DESKTOP-NTOELOP-EFLOW; properties=; tags=}
EdgeRuntimeVersion : @{IotEdgeVersion=1.1.4; MobyEngineVersion=19.03.15+azure; MobyCliVersion=19.03.15+azure}
EdgeRuntimeStatus  : @{SystemCtlStatus=System.Object[]; ModuleList=System.Object[]}
SystemStatistics   : @{TotalMemMb=727; UsedMemMb=500; AvailableMemMb=141; TotalStorageMb=9900; UsedStorageMb=1955;
                     AvailableStorageMb=7527; CpuCount=2; KernelVersion=5.10.42.1-3.cm1 #1 SMP Mon Jun 28 13:00:04 UTC
                     2021}



PS C:\work_tsib\Edge>
======================================================================

===============================     sudo top   =======================================
![image](https://user-images.githubusercontent.com/9317171/130566347-8a6c093d-693a-4c5e-9385-4220863e2361.png)

**Comment by fcabrera23** [comment]
@owbeg,

From your logs, I can see that you are using the default memory configuration (1GB of memory).  Also, I can see that you only have 150MB of free memory, so when you start deploying other modules or just having more usage of the actual modules, it may not be enough. 

My suggestion is to increase the memory allocation to the VM and check if you still have the same issue. To do so, you can use the command `Set-EflowVm`. You can find the full documentation at [PowerShell functions for IoT Edge for Linux on Windows](https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06).

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @owbeg,

Are you still facing issues?  I imagine that with the new memory allocation you're not having issues with memory. Are you still facing issues with `Connect-EflowVm`?

Thanks,
Francisco
