### ISSUE TITLE
EFLOW gets into a state that I cannot connect-eflowvm

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#64]
When I installed EFLOW I used the deploy-eflowvm command with all the defaults. (And I did DPSTPM provisioning)  It's been working ok for the past couple days.   I was doing some testing with a module adn now I can't connect-eflowvm.  IT's saying ssh: connect to host 172.25.78.57 port 22: Connection timed out
stop-eflowVM/Start-eflowVM still have the problem.
Reboot my computer still have the problem.  

I checked that the WSDD agent is running (it is)
Any thoughts on how to recover from this?

**Comment by fcabrera23** [comment]
Hi @hooligan495,

Thanks for all your detailed information. It would be helpful if you could share the following information:

1. Are you using Default Switch or External Switch? If using Default Switch, are you using Static IP?
2. Are you using any specific module? Are those modules publicly available so that we can try the deployment on our end
3. What's the CPU/Memory allocation for the EFLOW VM?
4. Is your PC domain joined?

Thanks,
Francisco

**Comment by hooligan495** [comment]
I think I did the default which was using the default switch ? (I installed EFLOW after your latest release a week or so ago)
I am developing a custom module and it is definitely has some problems.. (I'm trying to get it running in EFLOW adn then open ports so I can attach remote debugger) the VMMem process seems pegged at 2G.   CPU not so much. 
Yes... My computeri s part of a domain

**Comment by hooligan495** [comment]
the stop-eflowvm command doesn't really stop the eflow vm it seems when it's in this state.  I run that command and see the VMMem process still using 2G ram.  (Which is what I think the default allocation is)

Is there another way to force reboot the VM from teh outside?

**Comment by fcabrera23** [comment]
Hi @hooligan495,

When you installed EFLOW, did you just use the "Deploy-Eflow" command without any parameter for the switch or static IP right?  I'm starting a separate thread so that we can further debug the issue.

Thanks,
Francisco

**Comment by hooligan495** [comment]
yes

**Comment by fcabrera23** [comment]
Hi @hooligan495,

Thanks for all your help and information. The issue investigation has shown us that there are three potential problems that could be  causing connection issues

1. Lack of memory allocation to the EFLOW VM - Make sure you have enough free memory inside the VM. You can check the memory (assigned, free, used) using  `(Get-EflowVm).SystemStatistics | Format-List`
2. Lack of storage allocation to the EFLOW VM - Make sure you have enough free storage inside the VM.  You can check the storage (assigned, free, used) using  `(Get-EflowVm).SystemStatistics | Format-List`
3. Connectivity issues between the Windows host and the EFLOW VM - You can verify this by using the `hcsdiag list` and `hcsdiag console <vm-guid>`.
4. Too many attempts to establish an SSH connection. For security reasons, we limit the number of connections that can be attempted/established to the EFLOW VM within a period of time.

Thanks,
Francisco

**Comment by hooligan495** [comment]
Thanks.  What is the time window for ssh connection s and if that is hit how do we know.  

Jay
