### ISSUE TITLE
Uninstall and Deprovision

### ISSUE THREAD

**Issue by mvenanc** [Azure/iotedge-eflow#66]
Hello. 

I tried to find a way to uninstall Eflow or even deprovision it/device but I couldn´t find any documentation. 

**Detailed background**
I am testing EFlow a lot. I am using nested virtualization. I ran into some issues but I could overcome all of them. Reading the documetation a executing each step is enought to get iotedge ready. But there is a little detail. It is necessary to provision the right amount of memory and cores to the VM in order to run some containers. I got stuck until figured out that issue. 

The need to uninstall Eflow is to do not need to provision a new VM/machine each time I got some issue. I need a way to return to initial state prior to Eflow deployment.

**Comment by fcabrera23** [comment]
HI @mvenanc,

Thanks for your suggestion. We will take into consideration your feedback. Regarding the installation, you just need to follow these steps:

1. Open Settings on Windows 10
2. Select Add or Remove Programs
3. Select Azure IoT Edge LTS app
4. Select Uninstall

Once the Azure IoT Edge app is correctly removed from the target device, we can start the deployment again.
