### ISSUE TITLE
TPM+DPS provisioning - custom registration id

### ISSUE THREAD

**Issue by Thacai** [Azure/iotedge-eflow#68]
**Describe the Problem**
When using TPM provisoning with DPS, in our enterprise the physical hardware have our own "identifier", physically labelled too, and would therefor like to be able to use a custom registration id, example: HOSTNAME-EFLOW instead of the arbitrary generated registration id returned from "Get-EflowVmTpmProvisioningInfo"

**Expected behavior**
I would expect that a command like: 
`Provision-EflowVm -provisioningType DpsTPM -scopeId XXXX -registrationId HOSTNAME-EFLOW` would not only be valid for symmetric key.

**EFLOW version**
1.1.2107.0

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 Enterprise
 - Version: 20H2 (19042.1165)
 - Virtual Machine: None
 
**Additional context**
Would also make it cleaner for our use, when viewing DPS enrollments at a glance, that we wont need to extract the tags to figure out what device we're looking at

**Comment by fcabrera23** [comment]
Hi @Thacai,

Thanks for your detailed information. We will take your suggestion into account for our upcoming updates. 

Thanks,
Francisco
