### ISSUE TITLE
Get-EflowVmTpmProvisioningInfo - not returning expected object

### ISSUE THREAD

**Issue by Thacai** [Azure/iotedge-eflow#69]
**Describe the bug**
The docs, https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06#get-eflowvmtpmprovisioninginfo states that this function will return an object containing two properties: Endorsement Key and Registration Id.

This is not the case, it appears to be a simple multiline output

**To Reproduce**
1. Run: `Get-EflowVmTpmProvisioningInfo`
2. You'll now get 2 lines back, first line is the key, the second is the registration id: 
![image](https://user-images.githubusercontent.com/4174649/130494200-38c2664b-0f68-49ec-b312-d2e76dd79b03.png)

**Expected behavior**
I would expect it to be an object with properties as described, to allow easy use of the individual values

**EFLOW Version**
1.1.2107.0

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 Enterprise
 - Version: 20H2
 - Virtual Machine: None

**Comment by fcabrera23** [comment]
Hi @Thacai,

Thanks for your detailed information. We will take your suggestion into account for our upcoming updates. 

Thanks,
Francisco

**Comment by Thacai** [comment]
> Hi @Thacai,
> 
> Thanks for your detailed information. We will take your suggestion into account for our upcoming updates.
> 
> Thanks,
> Francisco

Hi Francisco, 
Personally i would consider this a bug, and not an enhancement, since the documentation states one thing, but the reality is another.

**Comment by fcabrera23** [comment]
@Thacai,

We will update the documentation and we'll fix to return an object in the upcoming updates.

Thanks,
Francisco
