### ISSUE TITLE
Accessing iotedge CLI from windows host

### ISSUE THREAD

**Issue by LukasSchwendemann** [Azure/iotedge-eflow#70]
**Question Summary**
Is it somehow possible to access the iotedge CLI from the Windows host?

**Detailed background**
Our Scenario:
On the edge side, we want to provide the capability to see which Azure IoT Edge modules are installed to a device and to restart them if necessary. Offline. Without any connection to IoT Hub. This should provide a way to troubleshoot issues without the need of any connectivity and without the knowledge of the Azure IoT Edge CLI.

Therefore, we implemented an .net core web app (running side by side with the Azure IoT Edge runtime) that gets information about installed modules through the iotedge CLI and display the modules for the customer. For restarting, we use the CLI as well.

On a Linux based system, there is no problem with that. But since eflow does not allow to change the VM by adding additional services because of the A / B Update scenario as stated [here ](https://github.com/Azure/iotedge-eflow/wiki/Support#how-can-i-install-a-linux-package). It is not viable to install our web app inside the Linux VM. Instead, we could install it on the windows host. But in that case, we do not have access to the CLI. An alternative was to open an SSH Tunnel from the host to the VM to be able to run the CLI commands to get the needed information. But that one is disabled as well, as [stated here](https://github.com/Azure/iotedge-eflow/wiki/SSH-EFLOW-VM ).

How can we solve these challenges regarding our use case the best way by using Azure IoT Edge for Linux on a Windows device. Is there some other kind of interopt to access the Linux VM From Windows I did not found?

Thanks in advance.

**Comment by LukasSchwendemann** [comment]
Thanks for your reply. I think using the Invoke command to call the "iotedge list" command could be a solution. I hoped that we can have a solution where we don't need to run our application as administrator. Because the Invoke command needs Admin privileges. And I indeed got an exmaple running with the Invoke-EflowVmCommand that gives us all the information about running modules that we need.

**Comment by fcabrera23** [comment]
@LukasSchwendemann,

Thanks for all your feedback. Please make sure to create a new request on the [IoT Edge Github](https://github.com/Azure/iotedge/issues).
