### ISSUE TITLE
SSH connection management

### ISSUE THREAD

**Issue by hooligan495** [Azure/iotedge-eflow#78]
**Question Summary**
What are the rules for when you deny SSH connections

**Detailed background**
in issue #64 you mentioned:
Too many attempts to establish an SSH connection. For security reasons, we limit the number of connections that can be attempted/established to the EFLOW VM within a period of time.

I would like to understand what the rules are that decide "too many attempts" means... Are you saying that attempts that fail?  or attempts in general.

Is there any way to detect that any of the conditions you list in #64 are getting close?  Does EFLOW have it's own sort of "watchdog" capability we could leverage from the host os to know that somethign is close to going wrong? 

In general how are you sharing file space between the EFLOW vm and any docker images?  From just poking around are you reserving like 300m (on a 10G eflow disk size) for the OS and 9.7 as overlays for all docker images?    

Thanks!
Jay

**Comment by fcabrera23** [comment]
Hi @hooligan495,

You can check all the SSH configurations under using the commands `sudo systemctl show sshd.socket` and `sudo cat /etc/ssh/sshd_config`.  Regarding the attempts, here's the official documentation:

_MaxAuthTries : Specifies the maximum number of authentication attempts permitted per connection. Once the number of failures reaches half this value, additional failures are logged. The default is 6._.

Finally, regarding memory and storage usage, we are currently investigating workarounds and functions to limit the usage.

Thanks,
Francisco

**Comment by hooligan495** [comment]
If the max auth attempts is hit what happens in EFLOW does it refuse all SSH attempts from that point on?

**Comment by fcabrera23** [comment]
Hi @hooligan495,

Not exactly, we limit the SSH attempts for a period of time, but then will be back to normal.  For more information, you can check [this guide](https://dailydoseoftech.com/how-to-setup-ssh-brute-force-protection-with-iptables/).
