### ISSUE TITLE
DPS Individual Enrollment Registration ID

### ISSUE THREAD

**Issue by jdbelo** [Azure/iotedge-eflow#85]
**Question Summary**
How can I change the registration ID returned by the `Get-EflowVmTpmProvisioningInfo` command? Can I set a customized registration ID?

**Detailed background**
The idea behind these questions is to be able to create the Individual Enrollment before installing the Azure IoT Edge on the device, as it was possible in the past (before Eflow). 
Before Eflow, I was able to create the individual enrollments providing the TPM Endorsement Key and setting up the device id and the registration Id, both device id and registration Id could be chosen by me. Although it continues to be technically possible, it seems the registration Id is generated, somehow, during the Eflow installation process and must not be changed. This means that I am not able to create the Individual Enrollment before installing Azure IoT Edge and executing some commands. The `Provision-EflowVm` allows providing a registration Id, however, it doesn't work with the TPM assertion mechanism.
Before Eflow, a had fully automated process to provision a device without having to install any application to create the enrollment. The enrollment and provisioning steps were completely segregated.
With Eflow, the installation of the Azure IoT Edge is needed in order to get the registration Id, which slightly mixes the steps. So, suggestions to automate the whole process are welcoming.

**Comment by fcabrera23** [comment]
Hi @jdbelo,

We already support that, although is not documented, as we may change it in the future. When doing the `Set-EflowVmFeature` you can add the parameter _-headless_ and it won't ask for confirmation. 

Thanks,
Francisco
