### ISSUE TITLE
Performance problems using Windows Server 2019 Datacenter - Gen2 image

### ISSUE THREAD

**Issue by vipeller** [Azure/iotedge-eflow#90]
**Describe the Problem**
Using an Azure VM with "Windows Server 2019 Datacenter - Gen2", edge becomes slow and some commands unresponsive. At the end even shutting down the vm ends up in an error message. The same tests work well using Windows 10 Pro image.

**To Reproduce**
1. Deloy elfow using an azure vm/winserver 2019 image, using Standard_D2s_v3 size
2. Provision an edge device
3. Add 7 temperature sensor modules to the edge device
4. Wait until the deployment happens
5. Check the deployment using 'sudo docker ps' command. As modules start, the command gets slower and slower
6. Try to get a module log e.g 'sudo iotedge logs edgeHub'
7. Try to stop the vm - it returns an error

**Expected behavior**
Similar behavior than on Windows 10
 explain your problem.

**Windows Host OS:**
 - Edition: Windows Server 2019 Datacenter - Gen2
 - Version: 1809 Build 17763.2237
 - Virtual Machine: Azure VM D2s_v3 (happens with
 
**Additional context**
This is related to https://github.com/Azure/iotedge/issues/5087
The customer has TLS related errors on windows server when uses more modules. The error message indicates that the certificate being used does not have corresponding private key. An isolated test (importing and using certificates) showed that repeating the operation 200ms later, the system already has the information about the private key.

Although it is not necessarily comes from the performance issue, there are two things indicates that it might be related: the customer does not see the error on Windows 10 (which does not have the performance problem), and the 200ms delay makes the certificate work.

The certificate problem is mentioned only for context; I am reporting the performance problem. My approach to "solve" the certificate problem is to make the Windows Server setup as performant as the Win 10 one and see if the problem still occurs.

**Comment by fcabrera23** [comment]
Hi @vipeller,

I think you are having a memory issue. Could you please indicate what was your "Deploy-Eflow" command you used? I suspect that you are using the default memory allocation (1024MB) and when you deploy the 7 temperature modules, you're running out of memory.

Thanks,
Francisco

**Comment by vipeller** [comment]
@fcabrera23 I followed this walk-through: https://docs.microsoft.com/en-us/azure/iot-edge/quickstart?view=iotedge-2018-06

I did not specify any parameters for Deploy-Eflow, so you maybe be right. Is it different the default for Win 10?

**Comment by fcabrera23** [comment]
@vipeller,

The default values are the same for both Client and Server SKUs (1 vCpu Core, 1024MB of memory). Can you try reinstalling, but this time, deploy the EFLOW VM using 2 or 4GB of memory. You can do that by specifying the -memoryInMb flag. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @vipeller,

Did you test your scenario with a bigger memory allocation? If so, are you still facing the same issue?

Thanks,
Francisco

**Comment by vipeller** [comment]
Hi @fcabrera23 sorry, I have not taken the time yet, will test it soon.

**Comment by vipeller** [comment]
@fcabrera23 it works well with bigger memory set, thank you. You can close this ticket now.
