### ISSUE TITLE
Not able to configure transparent gateway

### ISSUE THREAD

**Issue by mpoeckl** [Azure/iotedge-eflow#93]
I configured a transparent edge gateway (Eflow with Edge 1.1 LTS on Windows 11). The initial installation and configuration of Edge Gateway (SAS or self-signed X.509 device identity cert) worked well, gateway successfully connects to IoT Hub. 
When I am trying to configure the (self-signed) root CA and edge CA certificate and the key needed for transparent gateway setup by manually editing the `certificates` section of the YAML file the daemon mgmt endpoint stopped working after restart. 
iotedge check shows the following error:
```
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (ConnectionRefused) : Connection refused /var/lib/iotedge/mgmt.sock
    One or more errors occurred. (Got bad response: )
        caused by: docker returned exit code: 1, stderr = SocketError - SocketErrorCode (ConnectionRefused) : Connection refused /var/lib/iotedge/mgmt.sock
                   One or more errors occurred. (Got bad response: )
```
As soon as I remove the `certificates `section from the YAML file everything is working fine again.

**Comment by mpoeckl** [comment]
The files (certificates and keys) copied using the `Copy-EflowVmFile` command sets the owning user and group to user '_iotedge-user_'. However the iotedge security domain is accessing the files using the user '_iotedge_' and is therefore not able to access the files.
By running `sudo chown iotedge:iotedge /home/iotedge-user/certs/<filename>.pem` for Root CA, Device CA and Device PK files the daemon is able to start successfully.
Device identity certificates and key (X509 self-signed device identity certs) configured through the `Provision-EflowVm -provisioningType ManualX509 ...` command are automatically set to the correct user ('_iotedge_').

**Comment by fcabrera23** [comment]
Hi @mpoeckl.

Thanks for your detailed information.  I'm glad to hear you were able to fix your issue. By default, the `Copy-EflowVmFile` will always set the ownership of the copied files/folders to iotedge-user. 

We have some sample PS functions for Get/Set IoT Edge certificates: [EFLOW-Util](https://github.com/Azure/iotedge-eflow/tree/main/eflow-util).

Thanks,
Francisco

**Comment by mpoeckl** [comment]
Hi @fcabrera23 ,

It would be great to add a link to these additional PS scripts to the official MS docs site for Eflow PS commands: https://docs.microsoft.com/en-us/azure/iot-edge/reference-iot-edge-for-linux-on-windows-functions?view=iotedge-2018-06. That would help to avoid misconfiguration of the YAML file and and ownership/access related issues.
