### ISSUE TITLE
Deploy-Eflow is not working on an elevated Powershell 7.2

### ISSUE THREAD

**Issue by Cyprien84** [Azure/iotedge-eflow#94]
**Describe the bug**
The Deploy-Eflow command return an the following error
 "The term 'EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. (L5656)"

**To Reproduce**
1. Open an elevated session of powershell 7.2
2. run the commands 
$msiPath = $([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest "https://aka.ms/AzEflowMSI" -OutFile $msiPath

Start-Process -Wait msiexec -ArgumentList "/i","$([io.Path]::Combine($env:TEMP, 'AzureIoTEdge.msi'))","/qn"
Deploy-Eflow
3. type "Y" to agree and "R" for Required
4. See the error:  
[11/16/2021 18:44:32] Exception caught!!!

 - The term 'EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again. (L5656)

[11/16/2021 18:44:32] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

Write-EventLog: The term 'Write-EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Expected behavior**
Expect the deployement to run directly
**Screenshots**

**Windows Host OS (please complete the following information):**
 - Edition: Windows 10 enterprise
 - Version: 21H1 [ build 19043.1288]
 - Virtual Machine: [None]
 
**Additional context**

**Comment by fcabrera23** [comment]
Hi @Cyprien84,

Thanks for your information. We do not currently support PS7 or PS6. We plan to bring support in the upcoming updates. Please use PowerShell 5.1 for installation.

Thanks,
Francisco

**Comment by Cyprien84** [comment]
Hi @fcabrera23 Thanks for the precision. I didn't find the information in the requirements. Everything is working now with PS 5.1. Thanks!

**Comment by fcabrera23** [comment]
Hi @Cyprien84,

FYI - The latest [EFLOW 1.1.2202.21022](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2202.21022) added support for PowerShell 7 and PowerShell SDK.

Thanks,
Francisco
