### ISSUE TITLE
Get-EflowVmTpmProvisioningInfo returns truncated TPM key

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#97]
**Describe the bug**
By running the command `Get-EflowVmTpmProvisioningInfo` the returned TPM endorsement key is not completely presented.
Because of the big size of the endorsement key, just the first part of the key is returned followed by "..." .

**To Reproduce**
1. Install EFLOW v1.1.2111.17111
2. Deploy EFLOW VM
3. Enable TMP provisioning
4. Run the command `Get-EflowVmTpmProvisioningInfo`

**Expected behavior**
Get the complete TPM endorsement key.

**Windows Host OS (please complete the following information):**
 - Edition: Enterprize
 - Version: [build 17763]
 - Virtual Machine: [19042.1348]
 
**Additional context**
Without this command returning the complete endorsement key, it is not possible to go ahead with the provisioning

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for your question. The TPM EK is not truncated, this is how PowerShell manages visualization for objects with long strings.  You can check the whole EK and RegistrationId using the command `Get-EflowVmTpmProvisioningInfo | Format-List`

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello @fcabrera23,

Yup, I confirm that adding the format part allows seeing the entire Endorsement key.
Even being PowerShell output issue I would suggest updating [this documentation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-on-windows-tpm?view=iotedge-2018-06&tabs=physical-tpm%2Cpowershell#retrieve-the-tpm-information-from-your-device) with the suggested command.

Thanks,

Nuno

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for the suggestion. We will update the documentation.

Thanks,
Francisco
