### ISSUE TITLE
Provision-EflowVM always reports success no matter the the device was provisioning or not

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#98]
**Describe the Problem**
Provision-EflowVM command always returns "Provisioning successful", even when the device has not been provisioned at all.
It happens for instance:
-  when there is no Enrolment Created on the DPS portal side
-  when we trigger the provisioning command with a wrong registration ID

**To Reproduce**
1. Install EFLOW v1.1.2111.17111
2. Deploy a VM
3. Run the provisioning command (I tried DpsTpm type) without DPS enrolment entity created on the portal OR with a wrong registration Id.
4. Se the success outcome message.

**Expected behavior**
If the Device is not provisioned and no IoTHub device is created I expect that the provisioning command returns an error.

**Windows Host OS (please complete the following information):**
 - Edition: [Enterprise]
 - Version: [19042.1348]
 - Virtual Machine: [None]

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for the information.  We will try to reproduce the issue and let you know.

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello @fcabrera23  any updates on this?

**Comment by ngmartins** [comment]
Hello, any update on this?

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Sorry for the delayed response. I was able to repro your issue; during the Provision-EFlowVm we only check that the IoT Edge service is running, but we don't check if the provisioning was successful or not. We will try to address this issue in our next update end of January. 

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello and thanks for the feedback.

Just to align expectations on our side: the team will address the issue in a way of introducing the validation or just changing the command's output message?

Thanks,


Nuno

**Comment by fcabrera23** [comment]
Hi @ngmartins,

We plan to add some extra checks to the IoT Edge module status apart from the IoT Edge service. This will probably be included in our end of January update.

Thanks,
Francisco

**Comment by ngmartins** [comment]
Hello @fcabrera23,

The IoTEdge module run successfully just when the device is correctly provisioned?

Thanks,
Nuno

**Comment by fcabrera23** [comment]
Hi @ngmartins,

There are two different things.

1) The IoT Edge linux service needs to be running without issues - This is what we are checking right now
2) The IoT Edge device provisioning was successful and the device is provisioned - Right now we only check that the provisioning was completed (apply all the configurations needed), but we don't check the final result if the device was porivsion successfully.

We will introduce two changes:

1) We are changing the messaging from _**"Provisioning successful. iotedge service running**_" to _**"Provisioning completed. iotedge service running"**_
2) We are adding an extra check to see if the Provisioning was successful or not, and will add another messaging. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @ngmartins ,

The messaging was fixed with the [EFLOW 1.1.2201.04022 update](https://aka.ms/AzEFLOW-1_1_2201_04022). For EFLOW 1.1 LTS version, there's no supported way from the IoT Edge team to check if the provision was successful. For IoT Edge 1.2, we will include an API query to check it. 

Thanks,
Francisco
