### ISSUE TITLE
TPM Provision is not working for custom RegistrationID

### ISSUE THREAD

**Issue by ngmartins** [Azure/iotedge-eflow#99]
**Describe the bug**
Renning the command `Provision-EflowVM -provisioningType "DpsTpm" -scopeId "<ScopId>" -registrationId "custom-reg-id"`
I get a success message, however, the provisioning didn't happen.
I can check under the DPS portal individual enrolment that the status remains unassigned. and no device has been created.

**To Reproduce**
1. Install EFLOW v1.1.2111.17111
2. Deploy a VM
3. Create a DPS individual enrolment with the device TPM endorsement key and a custom registration id
4. Run the provisioning command (DpsTpm type) using the parameter `-registrationId "custom-reg-id"`
5. Check in the output that Provisioning command are using the right registration id and scope id
6. Chek in the DPS portal that the individual enrollment wasn't used. Check that no IoT Hub device had been created.

**Expected behavior**
I expect a similar behavior to the one of running the command with no `-registrationId "custom-reg-id"` parameter and the default registration id was used.

**Screenshots**
DPS portal - Individual Enrolment after the provisioning command returns success:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/24669761/143266221-dba30492-5f36-4990-9d96-a55d8f274fec.png">

**Windows Host OS (please complete the following information):**
 - Edition: [Enterprise
 - Version: [19042.1348]
 - Virtual Machine: [None]

**Comment by fcabrera23** [comment]
Hi @ngmartins,

Thanks for your detailed information. I've just tested using a custom registrationId and worked perfectly fine.

![image](https://user-images.githubusercontent.com/21229385/143275404-f2321a3f-c1e1-43e9-a94d-407d51eadbdf.png)

Thanks,
Francisco

**Comment by ngmartins** [comment]
Great: so I may be doing something wrong. 
Can you please describe your steps and validate the command I am using?

Thanks,

Nuno

**Comment by ngmartins** [comment]
@fcabrera23 just figured out: I may not use the char `"` around the parameter values.
Without the char, it works as expected.
Thanks for the help
